<?php if($this->elementClass == 'RecipientCountry' || $this->elementClass == 'RecipientRegion'): ?>
    <div class="default-info">
        Your activity may contain either recipient-country or recipient-region but not both. In case of multiple countries or regions, the total percentage should amount to 100%. For more information visit the IATI Activity Standard <a href="http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/recipient-country/#example-usage">page</a> for recipient-country or recipient-region.
    </div>
<?php endif;?>

<?php
    $activityInfo = $this->activityInfo;
?>
<?php if($activityInfo): ?>
<?php
    $title = "(" ;
    $title .= ($activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>
<?php endif; ?>
<div class="activity-title">
    <div class="element-edit-activity-info-wrapper">
        <span class="activity_identifier"> <?php print $activityInfo['activity_identifier']; ?> </span>
        <span class="activity_title"> <?php print $title;?> </span>
    </div>
    <?php if(Iati_Aidstream_ElementSettings::isHandledIndividually($this->elementClass)): ?>
        <span class="viewer-link"><?php echo $this->l('View ' .strtolower ($this->displayName).' list', 'activity/list-elements/?classname=Activity_'.$this->elementClass.'&activity_id='. $activityInfo['id'])?> | <?php echo $this->l('View Activity', 'activity/view-activity-info/?activity_id='. $activityInfo['id'])?></span>
    <?php else: ?>
        <span class="viewer-link"><?php echo $this->l('View Activity', 'activity/view-activity-info/?activity_id='. $activityInfo['id'])?></span>
    <?php endif; ?>
    <div class="clear"></div>
</div>
<div class="second-title">Adding <span><?php print $this->displayName ?>...</span></div>
    
<?php print $this->form; ?>