<?php
    $activityInfo = $this->activityInfo;
?>
<? if($activityInfo): ?>
<?
    $title = "(" ;
    $title .= ($activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>
<? endif; ?>
<div class="activity-title">
    <div class="element-edit-activity-info-wrapper">
        <span class="activity_identifier"> <?php print $activityInfo['activity_identifier']; ?> </span>
        <span class="activity_title"> <?php print $title;?> </span>
    </div>
    <?php if(Iati_Aidstream_ElementSettings::isHandledIndividually($this->elementClass)): ?>
        <span class="viewer-link"><?php echo $this->l('View ' .strtolower ($this->elementClass).' list', 'activity/list-elements/?classname=Activity_'.$this->elementClass.'&activity_id='. $activityInfo['id'])?> | <?php echo $this->l('View Activity', 'activity/view-activity-info/?activity_id='. $activityInfo['id'])?></span>
    <?php else: ?>
        <span class="viewer-link"><?php echo $this->l('View Activity', 'activity/view-activity-info/?activity_id='. $activityInfo['id'])?></span>
    <?php endif; ?>
    <div class="clear"></div>
</div>
<div class="second-title">Editing <span><?php print $this->displayName ?>...</span></div>
    
<?php
print $this->form;
?>