<?php
    $activityInfo = $this->activityInfo;
?>
<? if($activityInfo): ?>
<?
    $title = "(" ;
    $title .= ($activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>
<? endif; ?>
<div class="activity-title">
    <span class="activity_identifier"> <?php print $activityInfo['iati_identifier']; ?> </span>
    <span class="activity_title"> <?php print $title;?> </span>
    <span class="viewer-link"><?php echo $this->l('View Activity', 'wep/view-activity/'. $activityInfo['id'])?></span>
</div>

<?php if(!empty($this->data)):?>
<?php echo $this->partial("partials/list/".$this->className.".phtml" , array(
                                                                                'data' => $this->data ,
                                                                                'elementClass' => $this->elementClass ,
                                                                                'activityId' => $this->activityId,
                                                                                'activityInfo' => $this->activityInfo
                                                                            )
                          );
?>
<? else : ?>
There is no <?php echo $this->className; ?> 
<? endif; ?>
<div class="add-more-link"><a href="<?php echo $this->baseUrl();?>/activity/add-element?classname=<?php echo $this->elementClass;?>&activity_id=<?php echo $this->activityId;?>">Add More</a></div>