<?php
    $activityInfo = $this->activityInfo;
?>
<? if($activityInfo): ?>
<?
    $title = "(" ;
    $title .= ($activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>
<? endif; ?>
<div class="activity-title">
    <span class="activity_identifier"> <?php print $activityInfo['activity_identifier']; ?> </span>
    <span class="activity_title"> <?php print $title;?> </span>
    <span class="viewer-link"><?php echo $this->l('View Activity', 'activity/view-activity-info/?activity_id='. $activityInfo['id'])?></span>
</div>
<div class="element-list-title"><?php echo $this->displayName; ?></div>

<?php if(!empty($this->data)):?>
<?php echo $this->partial("partials/list/".$this->className.".phtml" , array(
                                                                                'data' => $this->data ,
                                                                                'elementClass' => $this->elementClass ,
                                                                                'displayName' => $this->displayName,
                                                                                'activityId' => $this->activityId,
                                                                                'activityInfo' => $this->activityInfo
                                                                            )
                          );
?>
<div class="add-more-link"><a href="<?php echo $this->baseUrl();?>/activity/add-element?className=<?php echo $this->elementClass;?>&activity_id=<?php echo $this->activityId;?>&isMultiple=0">Add More <?php echo $this->displayName;?></a></div>
<? else : ?>
<span class="no-budget">There is no <?php echo $this->displayName; ?></span>
<div class="add-more-link"><a href="<?php echo $this->baseUrl();?>/activity/add-element?className=<?php echo $this->elementClass;?>&activity_id=<?php echo $this->activityId;?>&isMultiple=0">Add New <?php echo $this->displayName;?></a></div>
<? endif; ?>

<?php if($this->className == 'Transaction'):?>
<span class="btn-or">or</span>
<div id="transaction-upload">
    <?php echo $this->l('Upload Transaction' , "wep/upload-transaction?activity_id={$this->activityId}");?>
</div>
<?php endif; ?>
