<div class="default-info">
    All your activities have been migrated to IATI Standard V2.01. However, you need to manually publish your migrated activities to V2.01 compliant XML. Please consider going through your activities data to ensure that data are intact. Your previous activities (IATI V1.05) are maintained for read-only at <a href="http://v105.aidstream.org/wep/view-activities" target="_blank">Aidstream</a>. If you see any anomalies in the migrated data or if you have any confusion, please let us know at <a href="mailto:support@iatistandard.org">support@iatistandard.org</a>.
</div>

<?php 
    $activities = $this->activities;
    $change_status_form = $this->status_form;
    $model_user = new Model_User();
?>

<div class= "activity-state">
    <?php if($userPermission && $permission == '1'):?>
    <span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            . $this->activityInfo['id'])?></span>

    <?php endif; ?>
    <?php if(!$userPermission): ?>
    <span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                                . $this->activityInfo['id'])?></span>

    <?php endif; ?>
</div>
<?php
    $title = "(" ;
    $title .= ($this->activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>

<div class="activity-title">
    <div class="activity-inner-title">
      <span class="activity_identifier"> <?php print $this->activityInfo['activity_identifier']; ?> </span>
      <span class="activity_title"> <?php print $title;?> </span>
    </div>
    <div class="print-page">
      <a onclick="window.print();">Print Activity</a>
  </div>
</div>

<div class= "activity-state">
    <div class="state-display">
        <ul class='state-<?php echo $this->state;?>'>
            <li class='label'>Activity State</li>
            <?php foreach(Iati_WEP_ActivityState::getStatus() as $state_value => $state_name):?>
                <li <?php if($this->state == $state_value) {print "id='current-state'";}?> ><span class='<?php print (!in_array($state_value,Iati_WEP_ActivityState::getRemainingStates($this->state)))?'visited-state':'not-visited-state'; ?>'><?php print $state_name ?></span></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php if(!Model_User::checkHasPublished() && $this->state != Iati_WEP_ActivityState::STATUS_PUBLISHED):?>
      <?php if(!$model_user->getHelpState(Iati_WEP_ActivityState::getNextStatus($this->state))): ?>
        <div class="activity-state">
          <div id="change-state-description" class="custom-tooltip-dialog tooltip-left state-<?php echo strtolower(Iati_WEP_ActivityState::getStatus($this->state));?>">
          <span class="custom-tooltip-pointer"></span>
              <span id="close-dialog" class="close-dialog close-dialog-button">X</span>
              <div class="dialog-content">
                  <p><?php echo Model_Help::getHelpMessageForStates($this->state);?></p>
                   <div class="close close-dialog-button" value="<?php echo Iati_WEP_ActivityState::getNextStatus($this->state); ?>">Got it. Thanks</div>
              </div>
          </div>
        </div>
      <?php endif; ?>
    <?php endif; ?>
    <div class='change-state'>
        <div class="change-state-info-section">This activity is in <span class="change-state-current-state"><?php print(Iati_WEP_ActivityState::getStatus($this->state));?></span> State. <?php if($this->state != Iati_WEP_ActivityState::STATUS_PUBLISHED): ?>Mark it as <?php print($change_status_form)?><?php endif; ?>
        </div>
        <div class="change-state-help-section"><span class="change-state-help"><a href="#">what's this?</a></span></div>
    </div>
</div>

<div class="activity-container">
    <?php foreach ($activities as $activity) : ?>

        <!--Activity Default Start-->
        <?php echo $this->partial("partials/view-activity/activity-default.phtml" , array(
                                                                                        'activityInfo' => $activity ,
                                                                                    )
                                );
        ?>
        <!--Activity Default End-->
        
        <!--Reporting Activity Starts-->
        <?php if(!empty($activity['ReportingOrg'])) : ?> 
              <?php echo $this->partial("partials/view-activity/reporting-org.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['ReportingOrg'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Reporting Activity Ends-->
        
        <!--Iati Identifier Starts-->
        <?php if(count($activity['IatiIdentifier'])) : ?>
              <?php echo $this->partial("partials/view-activity/identifier.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['IatiIdentifier'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Iati Identifer Ends-->
     
        <!--Other Activity Identifer Starts-->
        <?php if(count($activity['OtherActivityIdentifier'])) : ?>
              <?php echo $this->partial("partials/view-activity/other-identifier.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['OtherActivityIdentifier'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Other Activity Identifer Ends-->
        
        <!--Title Starts-->
        <?php if(count($activity['Title'])) : ?>
              <?php echo $this->partial("partials/view-activity/title.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['Title'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Title Ends-->
        
        <!--Description Starts-->
        <?php if(count($activity['Description'])) : ?>
              <?php echo $this->partial("partials/view-activity/description.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['Description'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Description Ends-->
        
        <!--Activity Status Starts-->
        <?php if(count($activity['ActivityStatus'])) : ?>
              <?php echo $this->partial("partials/view-activity/activity-status.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['ActivityStatus'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Activity Status Ends-->
        
        <!--Activity Date Starts-->
        <?php if(count($activity['ActivityDate'])) : ?>
              <?php echo $this->partial("partials/view-activity/activity-date.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['ActivityDate'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Activity Date Ends-->
        
        <!--ContactInfo Starts-->
        <?php if(count($activity['ContactInfo'])) : ?>
              <?php echo $this->partial("partials/view-activity/contact-info.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['ContactInfo'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--ContactInfo Ends-->
        
        <!--Activity Scope Starts-->
        <?php if(count($activity['ActivityScope'])) : ?>
              <?php echo $this->partial("partials/view-activity/activity-scope.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['ActivityScope'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Activity Scope Ends-->
        
        <!--Participating Org Starts-->
        <?php if(count($activity['ParticipatingOrg'])) : ?>
              <?php echo $this->partial("partials/view-activity/participating-org.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['ParticipatingOrg'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Participating Org Ends-->
        
        <!--Recipient Country Starts-->
        <?php if(count($activity['RecipientCountry'])) : ?>
              <?php echo $this->partial("partials/view-activity/recipient-country.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['RecipientCountry'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Recipient Country Ends-->
        
        <!--Recipient Region Starts-->
        <?php if(count($activity['RecipientRegion'])) : ?>
              <?php echo $this->partial("partials/view-activity/recipient-region.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['RecipientRegion'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Recipient Region Ends-->
        
        <!--Location Starts-->
        <?php if(count($activity['Location'])) : ?>
              <?php echo $this->partial("partials/view-activity/location.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['Location'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Location Ends-->
        
        <!--Sector Starts-->
        <?php if(count($activity['Sector'])) : ?>
              <?php echo $this->partial("partials/view-activity/sector.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['Sector'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Sector Ends-->
        
        <!--PolicyMarker Starts-->
        <?php if(count($activity['PolicyMarker'])) : ?>
              <?php echo $this->partial("partials/view-activity/policy-marker.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['PolicyMarker'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--PolicyMarker Ends-->
        
        <!--Collaboration Type Starts-->
        <?php if(isset($activity['CollaborationType'])) : ?>
              <?php echo $this->partial("partials/view-activity/collaboration-type.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['CollaborationType'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Collaboration Type Ends-->
        
        <!--Default Flow Type Starts-->
        <?php if(count($activity['DefaultFlowType'])) : ?>
              <?php echo $this->partial("partials/view-activity/defaultFlow-type.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['DefaultFlowType'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Default Flow Type Ends-->
        
         <!--Default Finance Type Starts-->
        <?php if(count($activity['DefaultFinanceType'])) : ?>
              <?php echo $this->partial("partials/view-activity/defaultFinance-type.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['DefaultFinanceType'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Default Finance Type Ends-->
        
        <!--Default Aid  Type Starts-->
        <?php if(count($activity['DefaultAidType'])) : ?>
              <?php echo $this->partial("partials/view-activity/defaultAid-type.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['DefaultAidType'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Default Aid  Type Ends-->
        
        <!--Default Tied Status Starts-->
        <?php if(count($activity['DefaultTiedStatus'])) : ?>
              <?php echo $this->partial("partials/view-activity/defaultTiedStatus.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['DefaultTiedStatus'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Default Tied Status Ends-->
        
        <!--Country Budget Items Starts-->
        <?php if(count($activity['CountryBudgetItems'])) : ?>
              <?php echo $this->partial("partials/view-activity/country-budget-items.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['CountryBudgetItems'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Country Budget Items Ends-->
        
        <!--Budget Starts-->
        <?php if(count($activity['Budget'])) : ?>
              <?php echo $this->partial("partials/view-activity/budget.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,
                                                                                'activityInfo' => $activity ,
                                                                                'elements' => $activity['Budget'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Budget Ends-->
        
        <!--PlannedDisbursements Starts-->
        <?php if(count($activity['PlannedDisbursement'])) : ?>
              <?php echo $this->partial("partials/view-activity/plannedDisbursements.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,
                                                                                'activityInfo' => $activity ,
                                                                                'elements' => $activity['PlannedDisbursement'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--PlannedDisbursements Ends-->
        
        <!--Capital Spend Starts-->
        <?php if(count($activity['CapitalSpend'])) : ?>
              <?php echo $this->partial("partials/view-activity/capital-spend.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,
                                                                                'activityInfo' => $activity ,
                                                                                'elements' => $activity['CapitalSpend'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--PlannedDisbursements Ends-->
        
        <!-- Transaction Starts -->
        <?php if(count($activity['Transaction'])):?>
            <?php echo $this->partial("partials/view-activity/transactions.phtml" , array(
                                                                                            'activityInfo' => $activity ,
                                                                                            'transactions' => $activity['Transaction'] ,
                                                                                        )
                                    );
            ?>
        <?php endif; ?>
        <!-- Transaction Ends -->
        
        <!--Document Link Starts-->
        <?php if(count($activity['DocumentLink'])) : ?>
              <?php echo $this->partial("partials/view-activity/documentLink.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['DocumentLink'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Document Link Ends-->
        
        <!--Activity Website Starts-->
        <?php if(count($activity['ActivityWebsite'])) : ?>
              <?php echo $this->partial("partials/view-activity/activityWebsite.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['ActivityWebsite'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Activity Website Ends-->
        
        <!--Related Activity Starts-->
        <?php if(count($activity['RelatedActivity'])) : ?>
              <?php echo $this->partial("partials/view-activity/relatedActivity.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['RelatedActivity'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Related Activity Ends-->
        
         <!--Conditions Starts-->
        <?php if(count($activity['Conditions'])) : ?>
              <?php echo $this->partial("partials/view-activity/conditions.phtml" , array(
                                                                                'activity_id' => $activity['id'] ,  
                                                                                'elements' => $activity['Conditions'] ,
                                                                            )
                          );
               ?>
        <?php endif; ?>
        <!--Conditions Ends-->
        
        <!-- Result Starts -->
        <?php if(count($activity['Result'])):?>
            <?php echo $this->partial("partials/view-activity/result.phtml" , array(
                                                                                            'activityInfo' => $this->activityInfo ,
                                                                                            'results' => $activity['Result'] ,
                                                                                        )
                                    );
            ?>        
        <?php endif; ?>
        <!-- Result Ends -->
        
        <!-- Legacy Data Starts -->
        <?php if(count($activity['LegacyData'])):?>
            <?php echo $this->partial("partials/view-activity/legacy-data.phtml" , array(
                                                                                            'activity_id' => $activity['id'] ,  
                                                                                            'activityInfo' => $this->activityInfo ,
                                                                                            'elements' => $activity['LegacyData'] ,
                                                                                        )
                                    );
            ?>        
        <?php endif; ?>
        <!-- Legacy Data Ends -->
        
    <?php endforeach; ?>
</div>
