<?php $model = new Model_Wep(); ?>
<?php $data = Iati_ElementSorter::sortElementsData($this->data , array('TransactionDate' =>'@iso_date') , array('TransactionValue' => '@value_date')); ?>

<table class="activity-list-table">
    <thead>
        <tr>
            <th class="empty"><input type="checkbox" class="selectalltransaction"></th>
            <th>Internal Ref</th>
            <th>Transaction Type</th>
            <th>Transaction Value</th>
            <th>Transaction Date</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
<?php foreach($data as $element): ?>
        <tr>
            <td><input type="checkbox" name="<?php echo $element['@ref']; ?>" value="<?php echo $element['id'];?>"></td>
            <td><b><?php echo $element['@ref']; ?></b></td>
            <td><?php echo Iati_Core_Codelist::getCodeByAttrib('TransactionType' , '@code' , $element['TransactionType']['@code'], 'Name') ?></td>
            <td><?php echo $this->numberFormat()->localization($element['TransactionValue']['text']); ?></td>
            <td><?php echo $element['TransactionDate']['@iso_date']?></td>
            <td colspan=3>
                <span value="<?php echo $this->baseUrl();?>/activity/view-element?classname=<?php echo $this->elementClass;?>&id=<?php echo $element['id'];?>" class="view-element-link">View</span> |
                <a href='<?php echo $this->baseUrl();?>/activity/edit-element?className=<?php echo $this->elementClass;?>&id=<?php echo $element['id'];?>&activity_id=<?php echo $this->activityId; ?>&isMultiple=0'>Edit</a> |
                <a href='<?php echo $this->baseUrl();?>/activity/delete-element?classname=<?php echo $this->elementClass;?>&id=<?php echo $element['id'];?>&activity_id=<?php echo $this->activityId;?>' class="delete-element-link">Delete</a>
            </td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<form id="transactions_form" name="transactions" enctype="application/x-www-form-urlencoded" method="post" action="/activity/delete-elements?classname=Activity_Transaction&activity_id=<?php echo $this->activityId; ?>">
    <input type="hidden" name="id" value="" id="transactions">
    <button name="delete" id="delete-transactions" type="button" class="form-submit">Delete</button>
</form>