<?php
    $userName = $this->account['username'];
    $oRole = new User_Model_DbTable_Role();
    $role = $oRole->getRoleById($this->row['role_id'])->toArray();
    $roleName = $role['role'];
    $accountObj = new User_Model_DbTable_Account();
    if($roleName != 'superadmin' && $roleName != 'groupadmin'){
        $fileName = $accountObj->getFileName($userName);
        $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
        $filePath = $baseUrl.'/uploads/image/'.$fileName['file_name'] ; 
    }
?>

<h1 class="my-profile-title">
    My Profile
    <?php if($roleName != 'superadmin'):?>
    <span class = "edit-this"><?php print $this->l('Edit','user/user/edit/user_id/'.$this->row->user_id)?></span>
    <?php endif;?>
    
    <?php if($roleName == 'admin' || $roleName == 'groupadmin'):?>
    <span>|</span>
    <span class="change-username"><?php print $this->l('Change Username','user/user/changeusername/user_id/'.$this->row->user_id)?></span>
    <?php endif; ?>

    <span>|</span>
    <span class = "change-password"><?php print $this->l('Change Password','user/user/changepassword/user_id/'.$this->row->user_id)?></span>
</h1>



<div class = "profile-info">
    <div class="profile-info-inner">

        <div class="individual-name profile-item">
            <span class="profile-item-label">Name:</span>
            <span class="profile-item-value"><?php print $this->profile->first_name .
                                      (($this->profile->middle_name)? " ".
                                       $this->profile->middle_name ." " : " ") .
                                       $this->profile->last_name;?></span>
        </div>

        <div class="individual-email profile-item">
            <span class="profile-item-label">Email:</span>
            <span class="profile-item-value"><?php print $this->row->email?></span>
        </div>

        <div class="individual-username profile-item last">
            <span class="profile-item-label">Username:</span>
            <span class="profile-item-value"><?php print $this->row->user_name?></span>
        </div>
    
    </div>
</div>

<?php if($roleName != 'superadmin' && $roleName != 'groupadmin'): ?>

    <div id="organization-info">

        <h2>Organisation Details</h2>

        <?php if($fileName['file_name']): ?>
               <div id="organization-logo"><img src="<?php print $filePath; ?>" alt="logo"/></div>

        <?php else: ?>

                <div id="organization-logo"><img src="<?php echo $this->baseUrl().'/images/default-logo.png' ?>" alt="logo"/></div>

        <?php endif ?>

                <div id="organization-details">
                    <div class="organization-name organization-detail-item">
                            <span class="profile-item-label">Organisation Name:</span>
                            <span class="profile-item-value"><?php print $this->account['name']; ?></span>
                    </div>

                    <div class="organization-address organization-detail-item">
                            <span class="profile-item-label">Organisation Address:</span>
                            <span class="profile-item-value"><?php print $this->account['address']; ?></span>
                    </div>

                    <div class="organization-url organization-detail-item">
                        <span class="profile-item-label">Organisation Url:</span>
                        <span class="profile-item-value"><?php print $this->account->url?></span>
                    </div>

                    <div class="organization-telephone organization-detail-item">
                        <span class="profile-item-label">Organisation Telephone:</span>
                        <span class="profile-item-value"><?php print $this->account->telephone?></span>
                    </div>

                    <div class="organization-twitter organization-detail-item">
                        <span class="profile-item-label">Organisation Twitter:</span>
                        <span class="profile-item-value"><?php print $this->account->twitter?></span>
                    </div>

                    <div class="organization-comments organization-detail-item last">
                        <span class="profile-item-label">Disqus Comments:</span>
                        <span class="profile-item-value"><?php print ($this->account->disqus_comments==1)? 'Enabled' : 'Disabled'; ?></span>
                    </div>
                </div>
        <div class="clear"></div>
    </div>

<?php endif ?>