<h2><?php print $this->row->user_name?></h2>
<div class = "profile-info">
<table class = "profile-table">

    <tr>
        <td><?php 
        print $this->profile->first_name . 
                            (($this->profile->middle_name)? " ".$this->profile->middle_name ." " : " ") .
                             $this->profile->last_name;?></td>
    </tr>
    <tr>
        <td class="account-email"><?php print $this->row->email?></td>
    </tr> 
</table>
</div>
<!--<div class = "edit-button"><?php print $this->l('Edit','user/user/edit/user_id/'.$this->row->user_id)?></div>-->
<div class = "change-password"><?php print $this->l('Change Password','user/user/changepassword/user_id/'.$this->row->user_id)?></div>
