<div id="block-activity-menu" class="block">
    <div class="block-inner">
        <h2 class="title">Activity Menu</h2>
        <div class="content">
            <ul>
            
            <?php
            $identity = $this->userInfo();
            $url = Zend_Controller_Front::getInstance()->getRequest()->getParams();
            $paramValue = $url['class'];
            $model = new Model_Wep();
            
            $defaultField = $model->getDefaults('default_field_groups', 'account_id', $identity->account_id);
            
            $class = '';
            print 'Identification';
            $href2 = $this->baseUrl(). "/wep/edit-activity-elements/?activity_id=". $url['activity_id'] ."&class=ReportingOrg";
            $attributes = (getRowSet('ReportingOrg', $url['activity_id']))?'class = "active"':'';
            if($paramValue == 'ReportingOrg'){
                $class = "class = highlight";
            }
            print "<li $class><div class='help reporting_org'></div><a $attributes href=$href2>Reporting Organisation</a></li>";
            
            $attributes = (getRowSet('Identifier', $url['activity_id']))?'class = "active"':'';
            $href1 = $this->baseUrl() . "/wep/edit-activity-elements/?activity_id=". $url['activity_id'] ."&class=Identifier";
            $class = '';
            if($paramValue == 'Identifier'){
                $class = "class = highlight";
            }
            print "<li $class ><div class='help identifier'></div><a $attributes href=$href1>Iati Identifier</a></li>";
            
            $allowed_elements = $defaultField->getProperties();
            $titleArray = array('','Basic Activity Information','Participating Organisations','Geopolitical Information','Classifications','Financial','Related Documents','Relations','Performance');            
            $elements = array(
                                array('other_activity_identifier'),
                                array('title','description','activity_status','activity_date','contact_info'),
                                array ('participating_org'),
                                array('recipient_country','recipient_region','location'),
                                array('sector','policy_marker','collaboration_type','default_flow_type','default_finance_type','default_aid_type','default_tied_status'),
                                array ('budget','planned_disbursement','transaction'),
                                array ('document_link','activity_website'),
                                array ('related_activity'),
                                array ('conditions','result'),
                            );
            $i= '0';
            foreach($elements as $value)
            {
                foreach($value as $element ){                        
                    if($allowed_elements[$element])
                    {
                        print $titleArray[$i];
                        $attributes = '';
                        if(getRowSet($element, $url['activity_id'])){
                            $attributes = 'class = "active"';
                        }
                    
                        $key = ucwords(str_replace("_"," ",$element));
                        $href = $this->baseUrl()."/wep/edit-activity-elements/?activity_id=". $url['activity_id'] ."&class=".str_replace(" ", "", $key);
                        $class = '';
                        if(str_replace(" ", "", $key) == $paramValue){
                            $class = "class = highlight";
                        }
                        if(Iati_WEP_ActivityConstants::hasDisplayName($element)){
                            $key = Iati_WEP_ActivityConstants::getDisplayName($element);
                        }
                        print "<li $class><div class='help ".$element."'></div><a $attributes href='". $href ."'>" .$key ."</a></li>";
                    }
                }
                $i++;
            }       
            ?>
            
            </ul>
        </div>
</div>
</div>

<?php 
function getRowSet($name, $id)
{
    $tableName = "";
    $tableMapper = new Iati_WEP_TableClassMapper();
    $string = "Iati_Activity_Element_". $tableMapper->convertUnderscoreToCamelCase($name);
    $obj = new $string ();
    $name = $obj->getType();
    unset($obj);
    $tableName = $tableMapper->getTableName($name);
    $wepModel = new Model_Wep();
    $rowSet = $wepModel->getRowsByFields($tableName, 'activity_id', $id);
    if($rowSet)
        $rowSet = true;
    return $rowSet;
}
?>