
<?php 
$url = Zend_Controller_Front::getInstance()->getRequest()->getParams();
$paramValue = str_replace("Activity_" , "" , $url['className']);
 $titleArray = array('Basic Activity Information','Participating Organisations','Geopolitical Information','Classifications','Financial','Related Documents','Relations','Performance');
$elements = array(
                 array('Title','Description','ActivityStatus','ActivityDate','ContactInfo'),
                 array ('ParticipatingOrg'),
                 array('RecipientCountry','RecipientRegion','Location'),
                 array('Sector','PolicyMarker','CollaborationType','DefaultFlowType','DefaultFinanceType','DefaultAidType','DefaultTiedStatus'),
                 array ('Budget','PlannedDisbursement','Transaction'),
                 array ('DocumentLink','ActivityWebsite'),
                 array ('RelatedActivity'),
                 array ('Conditions','Result','LegacyData'),
               );
?>
<!--Starts Displaying elements menu of an activity-->
<div id="block-activity-menu" class="block">
    <div class="block-inner">
        <h2 class="title">Element Menu</h2>
        <div class="content">
            <ul>
                
                <!--Starts of identification block-->
                <li>
                    <div class="menu-category-title">Identification</div>
                    <ul class="menu-leaf">                        
                        <?php
                        // Reporting activity Element           
                        $attributes = (getRowSet('ReportingOrg' , $url['activity_id'])) ? 'class = "active"' : '';
                        $href1 = $this->baseUrl() . "/activity/edit-element/?activity_id=" . $url['activity_id'] . "&className=Activity_ReportingOrg";
                        $class = '';
                        if ($paramValue == 'ReportingOrg')
                        {
                            $class = "class = highlight";
                        }
                        print "<li $class><div class='help Activity_ReportingOrg'></div><a $attributes href=$href1>Reporting Organisation</a></li>";

                        //Iati Identifier Element
                        $attributes = (getRowSet('IatiIdentifier' , $url['activity_id'])) ? 'class = "active"' : '';
                        $href2 = $this->baseUrl() . "/activity/edit-element/?activity_id=" . $url['activity_id'] . "&className=Activity_IatiIdentifier";
                        $class = '';
                        if ($paramValue == 'IatiIdentifier')
                        {
                            $class = "class = highlight";
                        }
                        print "<li $class ><div class='help Activity_Identifier'></div><a $attributes href=$href2>Iati Identifier</a></li>";

                        // OtherActivityIdentifier Element
                        if (getRowSet('OtherActivityIdentifier' , $url['activity_id']))
                        {
                            $attributes = 'class = "active"';
                            $href3 = $this->baseUrl() . "/activity/edit-element/?activity_id=" . $url['activity_id'] . "&className=Activity_OtherActivityIdentifier" . $element;
                        } else
                        {
                            $attributes = '';
                            $href3 = $this->baseUrl() . "/activity/add-element/?activity_id=" . $url['activity_id'] . "&className=Activity_OtherActivityIdentifier" . $element;
                        }
                        $class = '';
                        if ($paramValue == 'OtherActivityIdentifier')
                        {
                            $class = "class = highlight";
                        }
                        print "<li $class ><div class='help Activity_OtherActivityIdentifier'></div><a $attributes href=$href3>Other Activity Identifier</a></li>";
                        ?>                
                    </ul><!--End .menu-leaf-->
                </li>
                <!--Ends of identification block-->
                
                <!--Starts displaying another block-->
                <?php
                $i = '0';
                foreach ($elements as $value)
                {
                    print "<li>";
                    print '<div class="menu-category-title">' . $titleArray[$i] . '</div>';
                    print '<ul class="menu-leaf">';
                    foreach ($value as $element)
                    {
                        if (getRowSet($element , $url['activity_id']))
                        {
                            $attributes = 'class = "active"';
                            $href = $this->baseUrl() . "/activity/edit-element/?activity_id=" . $url['activity_id'] . "&className=Activity_" . $element;
                        } else
                        {
                            $attributes = '';
                            $href = $this->baseUrl() . "/activity/add-element/?activity_id=" . $url['activity_id'] . "&className=Activity_" . $element;
                        }
                        $className = "Iati_Aidstream_Element_activity_" . $element;
                        $classObj = new $className;
                        $displayName = $classObj->getDisplayName();
                        $key = $displayName;
                        $class = '';
                        if ($element == $paramValue)
                        {
                            $class = "class = highlight";
                        }
                        
                        // For Transaction and Result
                        if($element == 'Result'){
                                $paramValue = end(explode('_', $paramValue));
                                if(str_replace(" ", "", $key) == $paramValue){
                                $class = "class = highlight";
                                }
                                $href = $this->baseUrl()."/activity/list-elements/?classname=Activity_Result&activity_id=".$url['activity_id'];
                            }
                            
                            if($element == 'Transaction'){
                                $paramValue = end(explode('_', $paramValue));
                                if(str_replace(" ", "", $key) == $paramValue){
                                $class = "class = highlight";
                                }
                                $href = $this->baseUrl()."/activity/list-elements?classname=Activity_Transaction&activity_id=".$url['activity_id'];
                            }
                            
                        print "<li $class><div class='help Activity_" . $element . "'></div><a $attributes href='" . $href . "'>" . $displayName . "</a></li>";
                    }
                    print "</ul>";
                    print "</li>";
                    $i++;
                }
                ?>
                <!--Ends displaying another block-->
                
            </ul>
        </div><!-- End .content-->
    </div><!-- End .block-inner-->
</div><!-- End #block-activity-menu-->
<!--Endss Displaying elements menu of an activity-->

<?php

/**
 * Check If Value Exist For An Element Of An Activity
 * @param type $name, className
 * @param type $id, parentId
 * @return boolean 
 */
function getRowSet($name , $id)
{
    $string = "Iati_Aidstream_Element_Activity_" . $name;
    $obj = new $string;
    $rowSet = $obj->fetchData($id , true);
    if (!$rowSet)
        $rowSet = false;
    else
        $rowSet = true;
    return $rowSet;

}
?>