<?php $identity = Zend_Auth::getInstance()->getIdentity();

?>

<?php
$container = new Zend_Navigation();
$this->navigation($container);

switch($identity->role){
    case 'superadmin' :
        $container->addPage(
            array(
                'label' => 'Dashboard',
                'module' => 'default',
                'controller' => 'admin',
                'action' => 'dashboard',
                'pages' => array(
                    array(
                        'label' => 'Register Organisation',
                        'module' => 'default',
                        'controller' => 'wep',
                        'action' => 'register',
                    ),
                    array(
                        'label' => 'List Help Topics',
                        'module' => 'default',
                        'controller' => 'admin',
                        'action' => 'list-help',
                    ),
                    array(
                        'label' => 'Awaiting Request',
                        'module' => 'default',
                        'controller' => 'admin',
                        'action' => 'awaiting',
                    ),

                    array(
                        'label' => 'View',
                        'module' => 'default',
                        'controller' => 'admin',
                        'action' => 'view',
                    ),
                    array(
                        'label' => 'My Profile',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'myaccount',
                        'pages' => array(
                            array(
                                'label' => 'Edit Profile',
                                'module' => 'user',
                                'controller' => 'user',
                                'action' => 'edit',
                            ),
                            ),
                    ),
                    array(
                        'label' => 'Change Password',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'changepassword',
                    ),
                ),
            )
        );
        break;
    case 'admin':
        $container->addPage(
            array(
                'label' => 'Dashboard',
                'module'     => 'default',
                'controller' => 'wep',
                'action'     => 'dashboard',
                'pages'      => array(
                    array(
                        'label' => 'Change Defaults',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'edit-defaults',
                    ),
                    array(
                        'label' => 'List Published Files',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'list-published-files',
                    ),
                    array(
                        'label' => 'Add Activity',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'add-activity',
                    ),
                    array(
                        'label' => 'Edit Activity',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'edit-activity',
                    ),
                    array(
                        'label' => 'View Organisation Elements',
                                'module'     => 'default',
                                'controller' => 'organisation',
                                'action'     => 'view-elements',
                                'pages' => array(
                                        array(
                                            'label' => 'Add-Element',
                                            'module'     => 'default',
                                            'controller' => 'organisation',
                                            'action'     => 'add-elements',
                                        ),
                                        array(
                                            'label' => 'Edit-Element',
                                            'module'     => 'default',
                                            'controller' => 'organisation',
                                            'action'     => 'edit-elements',
                                        ),      
                                )
                    ),
                    array(
                        'label' => 'My Profile',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'myaccount',
                        'pages' => array(
                            array(
                                'label' => 'Edit Profile',
                                'module' => 'user',
                                'controller' => 'user',
                                'action' => 'edit',
                            ),
                            ),
                    ),
                    array(
                        'label' => 'Change Password',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'changepassword',
                    ),
                    array(
                        'label' => 'List Activities',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'view-activities',
                        'pages' => array(
                            array(
                                'label' => 'View Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'view-activity',
                            ),
                            array(
                                'label' => 'Add',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'add-activity-elements',
                            ),
                            array(
                                'label' => 'Edit',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'edit-activity-elements',
                            ),
                            array(
                                'label' => 'Edit',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'edit-element',
                            ),
                            array(
                                'label' => 'Add',
                                'module'     => 'default',
                                'controller' => 'activity',
                                'action'     => 'add-element',
                            ),
                            array(
                                'label' => 'Edit',
                                'module'     => 'default',
                                'controller' => 'activity',
                                'action'     => 'edit-element',
                            ),
                            array(
                                'label' => 'List elements',
                                'module'     => 'default',
                                'controller' => 'activity',
                                'action'     => 'list-elements',
                            ),
                        ),
                    ),
                    array(
                        'label' => 'List Users',
                        'module'     => 'default',
                        'controller' => 'admin',
                        'action'     => 'list-users',
                        'pages' => array(
                            array(
                                'label' => 'User Profile',
                                'module' => 'default',
                                'controller' => 'admin',
                                'action' => 'view-profile',
                            ),
                            array(
                                'label' => 'Edit User Permission',
                                'module' => 'default',
                                'controller' => 'admin',
                                'action' => 'edit-user-permission',
                            ),
                            array(
                                'label' => 'User Register',
                                'module' => 'default',
                                'controller' => 'admin',
                                'action' => 'register-user',
                            ),
                            array(
                                'label' => 'Reset User Password',
                                'module' => 'default',
                                'controller' => 'admin',
                                'action' => 'reset-user-password',
                            ),
                        ),
                    ),

                ),
            )
        );
        $container->addPage(
            array(
                'label'         => 'Dashboard',
                'module'        => 'simplified',
                'controller'    => 'default',
                'action'        => 'dashboard',
                'pages'         =>  array(
                    array(
                        'label' => 'List Activities',
                        'module'     => 'simplified',
                        'controller' => 'default',
                        'action'     => 'view-activities',
                        'pages' => array(
                            array(
                                'label' => 'View Activity',
                                'module'     => 'simplified',
                                'controller' => 'default',
                                'action'     => 'view-activity',
                            ),
                            array(
                                'label' => 'Add Activity',
                                'module'     => 'simplified',
                                'controller' => 'default',
                                'action'     => 'add-activity',
                            ),
                            array(
                                'label' => 'Edit Activity',
                                'module'     => 'simplified',
                                'controller' => 'default',
                                'action'     => 'edit-activity',
                            ),
                        )
                    )
                )
            )
        );
        break;
    case 'user':
        $container->addPage(
            array(
                'label' => 'Dashboard',
                'module'     => 'default',
                'controller' => 'wep',
                'action'     => 'dashboard',
                'pages'      => array(
                    array(
                        'label' => 'Published Files',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'list-published-files',
                    ),
                    array(
                        'label' => 'Add Activity',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'add-activity',
                    ),
                    array(
                        'label' => 'Edit Activity',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'edit-activity',
                    ),
                    array(
                        'label' => 'List',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'view-activities',
                        'pages' => array(
                            array(
                                'label' => 'Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'add-activity-elements',
                            ),
                            array(
                                'label' => 'Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'edit-activity-elements',
                            ),
                            array(
                                'label' => 'Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'view-activity',
                            ),
                        ),
                    ),
                    array(
                        'label' => 'My Profile',
                        'module'     => 'user',
                        'controller' => 'user',
                        'action'     => 'myaccount',
                        'pages' => array(
                            array(
                                'label' => 'Edit Profile',
                                'module' => 'user',
                                'controller' => 'user',
                                'action' => 'edit',
                            ),
                            ),
                    ),
                    array(
                        'label' => 'Change Password',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'changepassword',
                    ),

                ),
            )
        );
        break;
    default :
    $container->addPage(
        array(
            'label' => 'Home',
            'module' =>'default',
            'controller' => 'index',
            'action' =>'index',
            'pages' =>array(
                        array(
                            'label' => 'Log In',
                            'module'     => 'user',
                            'controller' => 'user',
                            'action'     => 'login',
                        ),

                        array(
                            'label' => 'Register',
                            'module'     => 'user',
                            'controller' => 'user',
                            'action'     => 'register',
                        ),
                        array(
                            'label' => 'Forgot Password',
                            'module'     => 'user',
                            'controller' => 'user',
                            'action'     => 'forgotpassword',
                        ),
                    )
            )
    );
    break;

}
echo '<div class="breadcrumbs">';
echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();
echo '</div>';




