<?php $identity = Zend_Auth::getInstance()->getIdentity();

?>

<?php  
$container = new Zend_Navigation();
$this->navigation($container);

switch($identity->role){
    case 'superadmin' :
        $container->addPage(
            array(
                'label' => 'Dashboard',
                'module' => 'default',
                'controller' => 'admin',
                'action' => 'dashboard',
                'pages' => array(
                    array(
                        'label' => 'Register Organisation',
                        'module' => 'default',
                        'controller' => 'wep',
                        'action' => 'register',
                    ),
                    array(
                        'label' => 'List Organisation',
                        'module' => 'default',
                        'controller' => 'admin',
                        'action' => 'list-organisation',
                        'pages' => array(
                            array(
                                'label' => 'Edit Organisation',
                                'module' => 'default',
                                'controller' => 'admin',
                                'action' => 'edit-organisation',
                            ),
                            ),
                    ),
                    array(
                        'label' => 'Awaiting Request',
                        'module' => 'default',
                        'controller' => 'admin',
                        'action' => 'awaiting',
                    ),
                    
                    array(
                        'label' => 'View',
                        'module' => 'default',
                        'controller' => 'admin',
                        'action' => 'view',
                    ),
                    array(
                        'label' => 'My Profile',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'myaccount',
                    ),
                    array(
                        'label' => 'Change Password',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'changepassword',
                    ),
                ),
            )
        );
        break;
    case 'admin':
        $container->addPage(
            array(
                'label' => 'Dashboard',
                'module'     => 'default',
                'controller' => 'wep',
                'action'     => 'dashboard',
                'pages'      => array(
                    array(
                        'label' => 'Change Defaults',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'edit-defaults',
                    ),
                    array(
                        'label' => 'Add Activity',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'add-activity',
                    ),
                    array(
                        'label' => 'Edit Activity',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'edit-activity',
                    ),
                    array(
                        'label' => 'My Profile',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'myaccount',
                    ),
                    array(
                        'label' => 'Change Password',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'changepassword',
                        'param' => array(
                            'user_id' => $identity->user_id,
                        )
                    ),
                    array(
                        'label' => 'List',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'view-activities',
                        'pages' => array(
                            array(
                                'label' => 'View Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'view-activity',
                            ),
                            array(
                                'label' => 'Add Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'add-activity-elements',
                            ),
                            array(
                                'label' => 'Edit Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'edit-activity-elements',
                            ),
                        ),
                    ),
                    array(
                        'label' => 'List User',
                        'module'     => 'default',
                        'controller' => 'admin',
                        'action'     => 'list-users',
                        'pages' => array(
                            array(
                                'label' => 'User Profile',
                                'module' => 'default',
                                'controller' => 'admin',
                                'action' => 'view-profile',
                            ),
                            array(
                                'label' => 'Edit User Permission',
                                'module' => 'default',
                                'controller' => 'admin',
                                'action' => 'edit-user-permission',
                            ),
                            array(
                                'label' => 'User Register',
                                'module' => 'default',
                                'controller' => 'admin',
                                'action' => 'register-user',
                            ),
                            array(
                                'label' => 'Reset User Password',
                                'module' => 'default',
                                'controller' => 'admin',
                                'action' => 'reset-user-password',
                            ),
                        ),
                    ),
                    
                ),
            )
        );
        break;
    case 'user':
        $container->addPage(
            array(
                'label' => 'Dashboard',
                'module'     => 'default',
                'controller' => 'wep',
                'action'     => 'dashboard',
                'pages'      => array(
                    array(
                        'label' => 'Add Activity',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'add-activity',
                    ),
                    array(
                        'label' => 'Edit Activity',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'edit-activity',
                    ),
                    array(
                        'label' => 'List',
                        'module'     => 'default',
                        'controller' => 'wep',
                        'action'     => 'view-activities',
                        'pages' => array(
                            array(
                                'label' => 'Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'add-activity-elements',
                            ),
                            array(
                                'label' => 'Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'edit-activity-elements',
                            ),
                            array(
                                'label' => 'Activity',
                                'module'     => 'default',
                                'controller' => 'wep',
                                'action'     => 'view-activity',
                            ),
                        ),
                    ),
                    array(
                        'label' => 'My Profile',
                        'module'     => 'user',
                        'controller' => 'user',
                        'action'     => 'myaccount',
                    ),
                    array(
                        'label' => 'Change Password',
                        'module' => 'user',
                        'controller' => 'user',
                        'action' => 'changepassword',
                        'param' => array(
                            'user_id' => $identity->user_id,
                        )
                    ),
                    
                ),
            )
        );
        break;

}
echo '<div class="breadcrumbs">';
echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();
echo '</div>';



    
    