<div id="block-download-data-menu" class="block">
    <div class="block-inner">
	<div class="content clearfix">
	    <div class="action-icon"><?php print $this->l('Download My Data', 'wep/download-my-data');?></div>            
                <?php print $this->l('Download My Data', 'wep/download-my-data');?>           
	    <div>Download all your activities data in CSV format with one-click.</div>	    
	</div>
    </div>
</div>