

<div id="block-list-menu" class="block clearfix">
    <div class="block-inner">
	<div class="content">
	    <div class="action-icon"><?php print $this->l('List Organisations', 'organisation/list-organisations');?></div>            
                <?php print $this->l('List Organisations', 'organisation/list-organisations');?>           
	    <div>You can list organisations using this link.</div>
	</div>
    </div>
</div>


