
<div id="block-list-published-files" class="block clearfix">
    <div class="block-inner">
	<div class="content">
	    <div class="action-icon"><?php print $this->l('List Organisation Published Files', 'organisation/list-published-files');?></div>
	    <?php print $this->l('List Organisation Published Files', 'organisation/list-published-files');?>
	    <div>You can list organisation published files using this link.</div>
	</div>
    </div>
</div>
