
<div id="block-add-menu" class="block">
    <div class="block-inner">
	<div class="content clearfix">
	    <div class="action-icon"><?php print $this->l('Organisation Data', 'organisation/organisation-data');?></div>            
                <?php print $this->l('Organisation Data', 'organisation/organisation-data');?>           
	    <div>You can add new organisation using this link.</div>	    
	</div>
    </div>
</div>