
<?php
    $url = Zend_Controller_Front::getInstance()->getRequest()->getParams();
    $paramValue = str_replace("Organisation_" , "" , $url['classname']);
    $titleArray = array('Budgets' , 'Documents');
    $elements = array(
                    array('RecipientOrgBudget' , 'RecipientCountryBudget' , 'TotalBudget') ,
                    array('DocumentLink')
                );
?>

<div id="block-activity-menu" class="block">
    <div class="block-inner">
        <h2 class="title">Element Menu</h2>
        <div class="content">
            <ul>

                <li>
                    <div class="menu-category-title">Identification</div>
                    <ul class="menu-leaf">
                        <?php
                            // Reporting Organisation Menu           
                            $attributes = (getRowSet('ReportingOrg' , $url['parent_id'])) ? 'class = "active"' : '';
                            $href1 = $this->baseUrl() . "/organisation/edit-elements/?parent_id=" . $url['parent_id'] . "&classname=Organisation_ReportingOrg";
                            $class = '';
                            if ($paramValue == 'ReportingOrg')
                            {
                                $class = "class = highlight";
                            }
                            print "<li $class><div class='help Organisation_ReportingOrg'></div><a $attributes href=$href1>Reporting Organisation</a></li>";

                            // Identifier Menu
                            $attributes = (getRowSet('Identifier' , $url['parent_id'])) ? 'class = "active"' : '';
                            $href2 = $this->baseUrl() . "/organisation/edit-elements/?parent_id=" . $url['parent_id'] . "&classname=Organisation_Identifier";
                            $class = '';
                            if ($paramValue == 'Identifier')
                            {
                            $class = "class = highlight";
                            }
                            print "<li $class ><div class='help Organisation_Identifier'></div><a $attributes href=$href2>Identifier</a></li>";

                            // Name Menu
                            $attributes = (getRowSet('Name' , $url['parent_id'])) ? 'class = "active"' : '';
                            $href3 = $this->baseUrl() . "/organisation/edit-elements/?parent_id=" . $url['parent_id'] . "&classname=Organisation_Name";
                            $class = '';
                            if ($paramValue == 'Name')
                            {
                            $class = "class = highlight";
                            }
                            print "<li $class ><div class='help Organisation_Name'></div><a $attributes href=$href3>Name</a></li>";
                        ?>                
                    </ul><!--End .menu-leaf-->
                </li>
                

                <?php
                    $i = '0';
                    foreach ($elements as $value)
                    {
                        print "<li>";
                        print '<div class="menu-category-title">' . $titleArray[$i] . '</div>';
                        print '<ul class="menu-leaf">';
                        foreach ($value as $element)
                        {
                            $attributes = '';
                            if (getRowSet($element , $url['parent_id']))
                            {
                                $attributes = 'class = "active"';
                            }
                            $className = "Iati_Aidstream_Element_Organisation_" . $element;
                            $classObj = new $className;
                            $href = $this->baseUrl() . "/organisation/edit-elements/?parent_id=" . $url['parent_id'] . "&classname=Organisation_" . $element;
                            $displayName = $classObj->getDisplayName();
                            $key = $displayName;
                            $class = '';
                            if ($element == $paramValue)
                            {
                                $class = "class = highlight";
                            }
                            print "<li $class><div class='help Organisation_".$element . "'></div><a $attributes href='" . $href . "'>" . $displayName . "</a></li>";
                        }
                        print "</ul>";
                        print "</li>";
                        $i++;
                    }
                ?>
            </ul>
        </div><!-- End .content-->
    </div><!-- End .block-inner-->
</div><!-- End #block-activity-menu-->

<?php

function getRowSet($name , $id)
{
    $string = "Iati_Aidstream_Element_Organisation_" . $name;
    $obj = new $string;
    $rowSet = $obj->fetchData($id , true);

    if (!$rowSet)
        $rowSet = false;
    else
        $rowSet = true;
    return $rowSet;

}
?>