
<div id="block-add-menu" class="block">
    <div class="block-inner">
	<div class="content clearfix">
	    <div class="action-icon"><?php print $this->l('Add New Organisation', 'organisation/add-organisation');?></div>            
                <?php print $this->l('Add New Organisation', 'organisation/add-organisation');?>           
	    <div>You can add new organisation using this link.</div>	    
	</div>
    </div>
</div>