<?php
    $identity = $this->userInfo();
    if($identity->role == 'user'){
        $model = new Model_Wep();
        $userPermission = $model->getUserPermission($identity->user_id);
        $permission = $userPermission->hasPermission(Iati_WEP_PermissionConts::EDIT_ACTIVITY);
    }
    
?>

<?php if(($userPermission && $permission == '1') || !$userPermission):?>
<div id="block-activity-menu" class="block">
    <div class="block-inner">
       <!-- <h2 class="title">Activity Menu</h2>-->
        <div>
            <ul>
            <li><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            . $this->activityInfo['id'])?></li>
            </ul>
        </div>
    </div>
</div>  
<?php endif; ?>
<?php //if(!$userPermission): ?>
<!--<span class = "override-link"><?php //echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            //. $this->activityInfo['id'])?></span>-->
  
<?php //endif; ?>