
<div id="block-list-menu" class="block clearfix">
    <div class="block-inner">
	<div class="content">
	    <div class="action-icon"><?php print $this->l('List Activities', 'wep/view-activities');?></div>
            <?php  if(Simplified_Model_Simplified::isSimplified()): ?>
                <?php print $this->l('List Activities', 'simplified/default/view-activities');?>
            <?php else: ?>
                <?php print $this->l('List Activities', 'wep/view-activities');?>
            <?php endif; ?>
	    <div>You can list activities using this link.</div>
	</div>
    </div>
</div>


