<?php //var_dump($this->activities_id);exit;?>

<div id="block-list-menu" class="block clearfix">
    <div class="block-inner">
	<div class="content">
	    <div class="action-icon"><?php print $this->l('List Activities', 'wep/view-activities');?></div>
	    <?php print $this->l('List Activities', 'wep/view-activities');?>
	    <div>You can list activities using this link.</div>
	</div>
    </div>
</div>

