<div id="block-list-menu" class="block block-info-menu clearfix">
    <div class="block-inner">
	<div class="content">
            <div class="simplified-info">You are using simplified version of aidstream.
            If you want to use the complete version please contact us at
	    <a href="mailto:support@aidstream.org">support@aidstream.org</a><br><br>
	    <?php echo  $this->l( 'Learn more'  , 'how-to-simplified');?> on how to use Simplified AidStream
	    </div>
	    <div class="simplified-how-to-link"></div>
	</div>
    </div>
</div>
