
<div id="block-list-menu" class="block clearfix">
    <div class="block-inner">
	<div class="content">
	    <div class="action-icon"><?php print $this->l('List Organisation', 'admin/list-organisation');?></div>
	    <?php print  $this->l('List Organisation', 'admin/list-organisation');?>
	    <div>You can list organisations using this link.</div>
	</div>
    </div>
</div>
<div id="block-add-menu" class="block clearfix">
    <div class="block-inner">
	<div class="content">
	    <div class="action-icon"><?php print $this->l('Add Organisation', 'wep/register');?></div>
	    <?php print  $this->l('Add Organisation', 'admin/register');?>
	    <div>You can add organisations using this link.</div>
	</div>
    </div>
</div>
<div id="block-list-help" class="block clearfix">
    <div class="block-inner">
	<div class="content">
	    <div class="action-icon"><?php print $this->l('List Help Topics', 'admin/list-help');?></div>
	    <?php print  $this->l('List Help Topics', 'admin/list-help');?>
	    <div>You can view and edit help messages for all elements.</div>
	</div>
    </div>
</div>
<div id="block-list-activity-states" class="block clearfix">
    <div class="block-inner">
	<div class="content">
	    <div class="action-icon"><?php print $this->l('Activity States' , 'admin/list-activity-states');?></div>
	    <?php print  $this->l('Activity States', 'admin/list-activity-states');?>
	    <div>You can view activities in different states for each organisation</div>
	</div>
    </div>
</div>
<div id="block-validate-xml-files" class="block clearfix">
    <div class="block-inner">
	<div class="content">
	    <div class="action-icon"><?php print $this->l('Validate XML' , 'admin/validate-xml-files');?></div>
	    <?php print  $this->l('Validate XML', 'admin/validate-xml-files');?>
	    <div>You can validate XML files of organisation.</div>
	</div>
    </div>
</div>
<div id="block-generate-published-xml-files" class="block clearfix">
	<div class="block-inner">
	<div class="content">
		<div class="action-icon"><?php print $this->l('Generate Published XML Files' , 'admin/generate-published-xml-files');?></div>
		<?php print $this->l('Generate Published XML Files', 'admin/generate-published-xml-files');?>
		<div>You can generate XML of the XML files that are published to the IATI Registry.</div>
	</div>	
	</div>
</div>
