<div id="support-wrapper" class="grid_5 push_7">
        <div class="support-form">
                <div>
                        If your query is related to IATI Standared, got to <a href= "http://iatistandard.org" target="_blank" >Iati Standard</a>
                        If your query is related to IATI Registry, got to <a href= "http://iatiregistry.org" target="_blank" >Iati Registry</a>
                </div>
                <div class="support-info">All the fields below are compulsary.</div>
                <?php $supportForm = new Form_General_Support()?>
                <?php echo $supportForm;?>
        </div>
        <div class="support">Support</div>
</div>