<div id="support-wrapper" class="grid_5 push_7">
        <div class="support-form">
                <div class="support-links">
                        Your query will be sent to the central IATI support team.
                </div>
                <div class="support-info">All the fields below are compulsary.</div>
                <?php $supportForm = new Form_General_Support()?>
                <?php echo $supportForm;?>
        </div>
        <div class="support">Support</div>
</div>
