<div id="block-uploaded-doc-menu" class="block">
    <div class="block-inner">
	<div class="content clearfix">
	    <div class="action-icon"><?php print $this->l('Uploaded Docs', 'wep/list-uploaded-documents');?></div>            
                <?php print $this->l('Uploaded Docs', 'wep/list-uploaded-documents');?>           
	    <div>You can view your uploaded docs using this link.</div>	    
	</div>
    </div>
</div>