Dear <?php echo $this->name ?>,<br />
<br />
You have requested to reset your account password.You may do so by clicking on the link below or copying and pasting it in your browser:<br />
<br />
<a href='<?php echo $this->reset_url; ?>'><?php echo $this->reset_url; ?></a><br />
<br />
Your Aidstream username: <?php echo $this->username; ?><br />
<br />
<br />
Thank you.<br />
<br />
------<br />
AidStream<br />