<li class="element-activity">

    <div class="element-title ">
        <?php echo "Document Link"; ?>
    </div>    

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/organisation/edit-elements/?parentId=<?php echo $this->parentId ?>&className=Organisation_DocumentLink">Edit</a></div>

    <?php $i = 0; ?>
    <?php foreach ($this->elements as $element): ?>
        <?php if ($i == '0'): ?>
            <div class="highlight first">
            <?php else: ?>
                <div class="highlight">
                <?php endif; ?>

                <ul class="style-4 first">
                    <li>
                        <span class="name">Url:</span>
                        <span class="infom sub-details"><?php echo $element['@url']; ?></span>
                    </li>
                    <li>
                        <span class="name">Format:</span>
                        <span class="infom sub-details"><?php echo Iati_Core_Codelist::getCodeByAttrib('DocumentLink' , '@format' , $element['@format'],'Name');
                                                              if($element['@format'])
                                                              {
                                                                  printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('DocumentLink' , '@format' , $element['@format']));
                                                              }    
                                                         ?>
                        </span>
                    </li>

                </ul>

                <!--Language Starts-->
                <?php if (!empty($element['Language'])): ?>
                       <ul class="style-1 style-4">
                            <h2>Language</h2>
                            <?php foreach ($element['Language'] as $language): ?>
                                <li>
                                    <span class="name">Code</span>
                                    <span class="infom"><?php if ($language['@code'])
                                                                {
                                                                    printf("%s [%s]" ,Iati_Core_Codelist::getCodeByAttrib('Language' , '@xml_lang' , $language['@code'],'Name'), Iati_Core_Codelist::getCodeByAttrib('Language' , '@xml_lang' , $language['@code']));
                                                                }
                                                        ?> 
                                    </span>
                                </li>
                            <?php endforeach; ?>
                        </ul> 
                <?php endif; ?>
                <!--Language Ends-->

                <!--Category Starts-->
                <?php if (!empty($element['Category'])): ?> 
                    <ul class="style-1 style-4">
                        <h2>Category</h2>
                        <?php foreach ($element['Category'] as $category): ?>
                            <li>
                                <span class="name">Code:</span>
                                <span class="infom"><?php if($category["@code"])
                                                          {
                                                              printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('Category' , '@code' , $category["@code"],'Name'),Iati_Core_Codelist::getCodeByAttrib('Category' , '@code' , $category["@code"]));
                                                          } 
                                                    ?>
                                </span>
                            </li>
                        <?php endforeach; ?>
                    </ul>            
                <?php endif; ?>
                <!--Category Ends-->


                <!--Title Starts-->
                <?php $title = $element['Title'];  ?>
                <?php if (isset($title)): ?> 
                    <?php $narratives = $title['Narrative']; ?>
                    <ul class="style-1 style-4">
                        <h2>Title</h2>
                        <?php foreach ($narratives as $narrative): ?>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"> <?php if ($narrative['text'] != "") print ($narrative['text']); ?>
                                        <?php
                                            if ($narrative['@xml_lang'])
                                            {
                                                printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('DocumentLink_Title' , '@xml_lang' , $narrative['@xml_lang']));
                                            }
                                        ?> 
                                    </span>
                                </li>
                            <?php endforeach; ?>    
                    </ul>            
                <?php endif; ?>
                <!--Recipient Country Ends-->
                <?php if (!empty($element['RecipientCountry'])): ?> 
                    <ul class="style-1 style-4">
                        <h2>Recipient Country</h2>
                        <?php foreach ($element['RecipientCountry'] as $recipientcountry): ?>
                            <li> 
                                <span class="name">Text:</span>
                                <span class="infom"><?php if ($recipientcountry['text'] != "") print ($recipientcountry['text']); ?></span>
                            </li>
                            <li>
                                <span class="name">Code:</span>
                                <span class="infom"><?php if($recipientcountry["@code"])
                                                          {
                                                              printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@code' , $recipientcountry["@code"],'Name'),Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@code' , $recipientcountry["@code"]));
                                                          } 
                                                    ?>
                                </span>
                            </li>
                        <?php endforeach; ?>
                    </ul>            
                <?php endif; ?>
                <!--Recipient Country Ends-->

            </div><!--Ends .highlight-->
            <?php $i = $i + 1; ?>

        <?php endforeach; ?>


</li><!-- end of element-activity -->