<li class="element-activity">

    <div class="element-title ">
        <?php echo "Document Link"; ?>
    </div>    

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/organisation/edit-elements/?parentId=<?php echo $this->parentId ?>&className=Organisation_DocumentLink">Edit</a></div>

    <?php $i = 0; ?>
    <?php foreach ($this->elements as $element): ?>
        <?php if ($i == '0'): ?>
            <div class="highlight first">
            <?php else: ?>
                <div class="highlight">
                <?php endif; ?>

                <ul class="style-4 first">
                    <li>
                        <span class="name">Url:</span>
                        <span class="infom sub-details"><?php echo $element['@url']; ?></span>
                    </li>
                    <li>
                        <span class="name">Format:</span>
                        <span class="infom sub-details"><?php echo $element['@format']; ?></span>
                    </li>

                </ul>

                <!--Language Starts-->
                <?php if (isset($element['Language'])): ?>
                       <ul class="style-1 style-4">
                            <h2>Language</h2>
                            <?php foreach ($element['Language'] as $language): ?>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php echo Iati_Core_Codelist::getCodeByAttrib('DocumentLink_Language' , '@xml_lang' , $language["text"]); ?></span>
                                </li>
                            <?php endforeach; ?>
                        </ul> 
                <?php endif; ?>
                <!--Language Ends-->

                <!--Category Starts-->
                <?php if (isset($element['Category'])): ?> 
                    <ul class="style-1 style-4">
                        <h2>Category</h2>
                        <?php foreach ($element['Category'] as $category): ?>
                            <li> 
                                <span class="name">Text:</span>
                                <span class="infom"><?php echo $category["text"]; ?></span>
                            </li>
                            <li>
                                <span class="name">Code:</span>
                                <span class="infom"><?php echo $category["@code"]; ?></span>
                            </li>
                            <li>
                                <span class="name">Language:</span>
                                <span class="infom"><?php echo Iati_Core_Codelist::getCodeByAttrib('DocumentLink_Category' , '@xml_lang' , $category["@xml_lang"]); ?></span>
                            </li>
                        <?php endforeach; ?>
                    </ul>            
                <?php endif; ?>
                <!--Category Ends-->


                <!--Title Starts-->
                <?php if (isset($element['Title'])): ?> 
                    <ul class="style-1 style-4">
                        <h2>Title</h2>
                        <li>
                            <span class="name">Text:</span>
                            <span class="infom"><?php echo $element['Title']["text"]; ?></span>
                        </li>
                        <li>
                            <span class="name">Language:</span>
                            <span class="infom"><?php echo Iati_Core_Codelist::getCodeByAttrib('DocumentLink_Title' , '@xml_lang' , $element['Title']["@xml_lang"]); ?></span>
                        </li>
                    </ul>            
                <?php endif; ?>
                <!--Title Ends-->
            </div><!--Ends .highlight-->
            <?php $i = $i + 1; ?>

        <?php endforeach; ?>


</li><!-- end of element-activity -->