<li class="element-activity">

    <div class="element-title ">
        <?php echo "Identifier"; ?>


        <div class="element-info">
            <div class="element-values">
                <?php if($this->elements['text']):?>
                    <span class="attrib-label">Text:</span>					
                    <span class="attrib-value"><?php echo $this->length()->adjustSingleLength($this->elements['text']); ?></span>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="highlight">
        <ul class="style-1">
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php echo $this->elements['text']; ?></span>
            </li>
        </ul>
    </div>



</li><!-- end of element-activity -->