<li class="element-activity">
    <div class="element-title ">
        <?php echo "Name"; ?>
        <div class="element-info">
            <div class="element-values">
                <?php if($this->elements['Narrative'][0]['text']):?>
                    <span class="attrib-label">Text:</span>                 
                    <span class="attrib-value"><?php echo $this->length()->adjustSingleLength($this->elements['Narrative'][0]['text']); ?></span>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/organisation/edit-elements/?parentId=<?php echo $this->parentId ?>&className=Organisation_Name">Edit</a></div> 

    <div class="highlight">
        <ul class="style-1">
            <?php if (!empty($this->elements)): ?>
                <?php $narratives = $this->elements['Narrative']; ?>
                <?php foreach ($narratives as $narrative): ?>
                    <li>
                        <span class="name">Text:</span>
                        <span class="infom"><?php echo $narrative['text'];
                                    if ($narrative['@xml_lang'])
                                    {
                                        printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('Name' , '@xml_lang' , $narrative['@xml_lang']));
                                    }
                            ?>                            
                        </span>
                    </li>
                <?php endforeach; ?>
              <?php endif; ?>
        </ul>           
    </div><!--Ends .highlight-->

</li><!-- end of element-activity -->