<li class="element-activity">

    <div class="element-title ">
        <?php echo "Name"; ?>
    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/organisation/edit-elements/?parentId=<?php echo $this->parentId ?>&className=Organisation_Name">Edit</a></div> 

    <div class="highlight">
        <ul class="style-1">
            <?php if (!empty($this->elements)): ?>
                <?php foreach ($this->elements as $element): ?>
                    <li>
                        <span class="name">Text:</span>
                        <span class="infom"><?php echo $element['text'];
                                                if ($element['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('Name' , '@xml_lang' , $element['@xml_lang']));
                                                }
                                            ?>                            
                        </span>
                    </li>
                <?php endforeach; ?>
              <?php endif; ?>
        </ul>           
    </div><!--Ends .highlight-->





</li><!-- end of element-activity -->