<li class="element-activity">

    <div class="element-title element-current">
        <?php echo "Recipient Country Budget"; ?>
    </div>    

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/organisation/edit-elements/?parentId=<?php echo $this->parentId ?>&className=Organisation_RecipientCountryBudget">Edit</a></div>

    <?php foreach ($this->elements as $element): ?>
        <div class="current">
            <ul class="style-2 arrow">
                <li><span class="down-arrow"> <?php if (isset($element['Value'])): ?>
                            <?php if($element['Value']["@currency"])
                                    {
                                        printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $element['Value']["@currency"]));
                                    }
                                    else
                                    {
                                         printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $this->defaultCurrency));
                                    }
                            ?>
                            <?php echo $this->numberFormat()->localization($element['Value']["text"]); ?>
                            <?php if ($element['Value']["text"] && $element['Value']["@value_date"]) echo " ; " . $element['Value']["@value_date"]; ?>
                        <?php endif; ?>
                    </span>

                    <!--Recipient Country Starts-->
                    <?php if (isset($element['RecipientCountry'])): ?>
                        <ul class="style-1 style-4">
                            <h2>Recipient Country</h2> 
                            <li>
                                <span class="name">Code:</span>
                                <span class="infom"><?php
                                                    if($element['RecipientCountry']["@code"])
                                                    {
                                                        printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@code' , $element['RecipientCountry']["@code"],'Name'),Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@code' , $element['RecipientCountry']["@code"]));
                                                    }    
                                                    ?>
                                </span>
                            </li>
                            <?php $narratives = $element['RecipientCountry']['Narrative']; ?>
                            <?php foreach ($narratives as $narrative): ?>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"> <?php if ($narrative['text'] != "") print ($narrative['text']); ?>
                                            <?php
                                                if ($narrative['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@xml_lang' , $narrative['@xml_lang']));
                                                }
                                            ?> 
                                    </span>
                                </li>
                            <?php endforeach; ?>    
                        </ul>            
                    <?php endif; ?>
                    <!--Recipient Country Ends-->

                    <!--Value Starts-->
                    <?php if (isset($element['Value'])): ?> 
                        <ul class="style-1 style-4">
                            <h2>Value</h2>
                            <li>
                                <span class="name">Text:</span>
                                <span class="infom"><?php echo $this->numberFormat()->localization($element['Value']["text"]); ?></span>
                            </li>
                            <li>
                                <span class="name">Value Date:</span>
                                <span class="infom"><?php echo $element['Value']["@value_date"]; ?></span>
                            </li>
                            <li>
                                <span class="name">Currency:</span>
                                <span class="infom"><?php echo Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $element['Value']["@currency"],"Name");
                                                          if($element['Value']["@currency"]) 
                                                          {
                                                              printf(" [%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $element['Value']["@currency"])); 
                                                          }
                                                     ?>
                                </span>
                            </li>
                        </ul>            
                    <?php endif; ?>
                    <!--Value Ends-->


                    <!--PeriodStart Starts-->
                    <?php if (isset($element['PeriodStart'])): ?> 
                        <ul class="style-1 style-4">
                            <h2>Period Start</h2>
                            <li>
                                <span class="name">Iso Date:</span>
                                <span class="infom"><?php echo $element['PeriodStart']["@iso_date"]; ?></span>
                            </li>
                        </ul>            
                    <?php endif; ?>
                    <!--PeriodStart Ends-->

                    <!--PeriodStart Starts-->
                    <?php if (isset($element['PeriodEnd'])): ?>
                        <ul class="style-1 style-4">
                            <h2>Period End</h2>
                            <li>
                                <span class="name">Iso Date:</span>
                                <span class="infom"><?php echo $element['PeriodEnd']["@iso_date"]; ?></span>
                            </li>
                        </ul>            
                    <?php endif; ?>
                    <!--PeriodStart Ends-->
                    <!--BudgetLine Starts-->
                <?php
                $budgetlines = $element['BudgetLine'];
                ?>
                <?php if (!empty($budgetlines)): ?>
                    <?php foreach ($budgetlines as $budgetline): ?>
                        <ul class="style-1 style-4"> 

                            <h2>Budget Line</h2>
                            <li>
                                <span class="name">Reference:</span>
                                <span class="infom"><?php if ($budgetline['@ref'] != "") print ($budgetline['@ref']); ?></span>
                            </li>
                            <li>
                                <span class="name">Text:</span>
                                <span class="infom"><?php if ($budgetline['text'] != "") print ($budgetline['text']); ?></span>
                            </li>

                            <?php $value = $budgetline['Value']; ?>
                            <?php if (!empty($value)): ?>
                                <h2>Value</h2>
                                <li>
                                    <span class="name">Value Date:</span>
                                    <span class="infom"><?php if ($value['@value_date'] != "") print ($value['@value_date']); ?></span>
                                </li>
                                <li>
                                    <span class="name">Amount:</span>
                                    <span class="infom"><?php if ($value['text'] != "") print ($value['text']); ?></span>
                                </li>
                                <li>
                                <span class="name">Currency:</span>
                                <span class="infom"><?php echo Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $value["@currency"],"Name");
                                                          if($value["@currency"]) 
                                                          {
                                                              printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $value["@currency"])); 
                                                          } 
                                                     ?>
                                                
                                </span>                                
                            </li>

                            <?php endif; ?>
                       
                        </ul>
                    <?php endforeach; ?>    
                <?php endif; ?>
                <!--BudgetLine Ends-->

                </li>
            </ul><!--Ends .style-2-->

        </div><!--Ends .current-->
    <?php endforeach; ?>


</li><!-- end of element-activity -->