<li class="element-activity">

    <div class="element-title element-current">
        <?php echo "Recipient Organisation Budget"; ?>
    </div>    

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/organisation/edit-elements/?parentId=<?php echo $this->parentId ?>&className=Organisation_RecipientOrgBudget">Edit</a></div>

    <?php foreach ($this->elements as $element): ?>
        <div class="current">
            <ul class="style-2 arrow">
                <li><span class="down-arrow"> <?php if (isset($element['Value'])): ?>
                            <?php if($element['Value']["@currency"])
                                    {
                                        printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $element['Value']["@currency"]));
                                    }
                                    else
                                    {
                                         printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $this->defaultCurrency));
                                    }
                            ?>
                            <?php echo $this->numberFormat()->localization($element['Value']["text"]); ?>
                            <?php if ($element['Value']["text"] && $element['Value']["@value_date"]) echo " ; " . $element['Value']["@value_date"]; ?>
                        <?php endif; ?>
                    </span>

                    <!--Recipient Organisation Starts-->
                    <?php if (isset($element['RecipientOrg'])): ?> 
                        <ul class="style-1 style-4">
                            <h2>Recipient Country</h2>
                                <li>
                                    <span class="name">Ref:</span>
                                    <span class="infom"><?php echo $element['RecipientOrg']["@ref"]; ?></span>
                                </li>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php echo $element['RecipientOrg']["text"];
                                                   if($element['RecipientOrg']["@xml_lang"])
                                                   {
                                                       printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('RecipientOrgBudget_RecipientOrg' , '@xml_lang' , $element['RecipientOrg']["@xml_lang"]));
                                                   }
                                                ?>
                                    </span>
                                </li>
                        </ul>            
                    <?php endif; ?>
                    <!--Recipient Organisation Ends-->

                    <!--Value Starts-->
                    <?php if (isset($element['Value'])): ?> 
                        <ul class="style-1 style-4">
                            <h2>Value</h2>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php echo $this->numberFormat()->localization($element['Value']["text"]); ?></span>
                                </li>
                                <li>
                                    <span class="name">Value Date:</span>
                                    <span class="infom"><?php echo $element['Value']["@value_date"]; ?></span>
                                </li>
                                <li>
                                    <span class="name">Currency:</span>
                                    <span class="infom"><?php echo Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $element['Value']["@currency"],"Name");
                                                         if($element['Value']["@currency"]) 
                                                          {
                                                              printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $element['Value']["@currency"])); 
                                                          }
                                                     ?> 
                                    </span>
                                </li>
                        </ul>            
                    <?php endif; ?>
                    <!--Value Ends-->
                   

                    <!--PeriodStart Starts-->
                    <?php if (isset($element['PeriodStart'])): ?>
                        <ul class="style-1 style-4">
                            <h2>Period Start</h2> 
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php echo $element['PeriodStart']["text"]; ?></span>
                                </li>
                                <li>
                                    <span class="name">Iso Date:</span>
                                    <span class="infom"><?php echo $element['PeriodStart']["@iso_date"]; ?></span>
                                </li>
                        </ul>            
                    <?php endif; ?>
                    <!--PeriodStart Ends-->

                    <!--PeriodStart Starts-->
                    <?php if (isset($element['PeriodEnd'])): ?> 
                        <ul class="style-1 style-4">
                            <h2>Period End</h2>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php echo $element['PeriodEnd']["text"]; ?></span>
                                </li>
                                <li>
                                    <span class="name">Iso Date:</span>
                                    <span class="infom"><?php echo $element['PeriodEnd']["@iso_date"]; ?></span>
                                </li>
                        </ul>            
                    <?php endif; ?>
                    <!--PeriodStart Ends-->
                </li>
            </ul><!--Ends .style-2-->

        </div><!--Ends .current-->

    <?php endforeach; ?>


</li><!-- end of element-activity -->