<li class="element-activity">

    <div class="element-title ">
         <?php  echo "Reporting Organisation"; ?>
        
            <div class="element-info">
                <div class="element-values">
                    <?php if($this->elements['@ref']): ?>
                        <span class="attrib-label">Ref:</span>
                        <span class="attrib-value"><?php echo $this->length()->adjustDoubleLength($this->elements['@ref']); ?></span>  
                    <?php endif; ?>
                </div>
            </div>
        </div> 
    
        <div class="highlight">
            <ul class="style-1">
                <li>
                    <span class="name">Ref:</span>
                    <span class="infom"><?php echo $this->elements['@ref']; ?></span>
                </li>
                <li>
                    <span class="name">Type:</span>
                    <span class="infom"><?php if($this->elements['@type'])
                                                {   
                                                     $wepModel = new Model_Wep();
                                                     $types = $wepModel->getRowsByFields('OrganisationType','id', $this->elements['@type']);
                                                     printf("%s [%s]",$types[0]['Name'],$types[0]['Code']);
                                                }
                                        ?> 
                    </span>
                </li>
                <?php $narratives = $this->elements['Narrative']; ?>
                <?php foreach ($narratives as $narrative): ?>
                    <li>
                        <span class="name"> Narrative Text:</span>
                        <span class="infom"> <?php if ($narrative['text'] != "") print ($narrative['text']); ?>
                            <?php
                                if ($narrative['@xml_lang'])
                                {
                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@xml_lang' , $narrative['@xml_lang']));
                                }
                            ?> 
                        </span>
                    </li>
                <?php endforeach; ?>

            </ul>
        </div>
   


</li><!-- end of element-activity -->