<li class="element-activity">

    <div class="element-title element-current">
        <?php echo "Total Budget"; ?>
    </div>    

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/organisation/edit-elements/?parentId=<?php echo $this->parentId ?>&className=Organisation_TotalBudget">Edit</a></div>

    <?php foreach ($this->elements as $element): ?>
        <div class="current">
            <ul class="style-2 arrow">
                <li><span class="down-arrow"> <?php if (isset($element['Value'])): ?>
                                                    <?php if($element['Value']["@currency"])
                                                    {
                                                        printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $element['Value']["@currency"]));
                                                    }
                                                    else
                                                    {
                                                        printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $this->defaultCurrency));
                                                    }    
                                                    ?>
                                                    <?php echo $this->numberFormat()->localization($element['Value']["text"]); ?>
                                                    <?php if($element['Value']["text"] && $element['Value']["@value_date"]) echo " ; ".$element['Value']["@value_date"];?>
                                              <?php endif; ?>
                    </span>
                    
                    <!--Value Starts-->
                    <?php if (isset($element['Value'])): ?> 
                        <ul class="style-1 style-4">
                            <h2>Value</h2>
                            <li>
                                <span class="name">Text:</span>
                                <span class="infom"><?php echo $this->numberFormat()->localization($element['Value']["text"]); ?></span>
                            </li>
                            <li>
                                <span class="name">Value Date:</span>
                                <span class="infom"><?php echo $element['Value']["@value_date"]; ?></span>
                            </li>
                            <li>
                                <span class="name">Currency:</span>
                                <span class="infom"><?php echo Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $element['Value']["@currency"],"Name");
                                                          if($element['Value']["@currency"]) 
                                                          {
                                                              printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $element['Value']["@currency"])); 
                                                          } 
                                                     ?>
                                                
                                </span>                                
                            </li>
                        </ul><!--Ends .style-1-->              
                    <?php endif; ?>
                    <!--Value Ends-->


                    <!--PeriodStart Starts-->
                    <?php if (isset($element['PeriodStart'])): ?> 
                        <ul class="style-1 style-4">        
                            <h2>PeriodStart</h2>
                            <li>
                                <span class="name">Iso Date:</span>
                                <span class="infom"><?php echo $element['PeriodStart']["@iso_date"]; ?></span>
                            </li>
                        </ul><!--Ends .style-1-->            
                    <?php endif; ?>
                    <!--PeriodStart Ends-->

                    <!--PeriodEnd Starts-->
                    <?php if (isset($element['PeriodEnd'])): ?> 
                        <ul class="style-1 style-4">  
                            <h2>PeriodEnd</h2>
                            <li>
                                <span class="name">Iso Date:</span>
                                <span class="infom"><?php echo $element['PeriodEnd']["@iso_date"]; ?></span>
                            </li>
                        </ul><!--Ends .style-1-->              
                    <?php endif; ?>
                    <!--PeriodEnd Ends-->

                    <!--BudgetLine Starts-->
                    <?php
                    $budgetlines = $element['BudgetLine'];
                    ?>
                    <?php if (!empty($budgetlines)): ?>
                        <?php foreach ($budgetlines as $budgetline): ?>
                            <ul class="style-1 style-4">
                                <h2>Budget Line</h2>
                                <li>
                                    <span class="name">Reference:</span>
                                    <span class="infom"><?php if ($budgetline['@ref'] != "") print ($budgetline['@ref']); ?></span>
                                </li>

                                <?php $value = $budgetline['Value']; ?>
                                <?php if (!empty($value)): ?>
                                    <h2>Value</h2>
                                    <li>
                                        <span class="name">Value Date:</span>
                                        <span class="infom"><?php if ($value['@value_date'] != "") print ($value['@value_date']); ?></span>
                                    </li>
                                    <li>
                                        <span class="name">Amount:</span>
                                        <span class="infom"><?php if ($value['text'] != "") print ($value['text']); ?></span>
                                    </li>
                                    <li>
                                    <span class="name">Currency:</span>
                                    <span class="infom">
                                    <?php echo Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $value["@currency"],"Name");
                                          if($value["@currency"]) 
                                          {
                                              printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $value["@currency"])); 
                                          } 
                                     ?>          
                                    </span>                                
                                </li>
                                <?php endif; ?>

                                <?php $narratives = $budgetline['Narrative']; ?>
                                <?php if (!empty($narratives)): ?>
                                    <h2>Narrative</h2>
                                    <?php foreach ($narratives as $narrative):  ?>
                                         <li>
                                            <span class="name">Text:</span>
                                            <span class="infom"> <?php if ($narrative['text'] != "") print ($narrative['text']); ?>
                                                <?php
                                                        if ($narrative['@xml_lang'])
                                                        {
                                                            printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('BudgetLine_Narrative' , '@xml_lang' , $narrative['@xml_lang']));
                                                        }
                                                ?> 
                                            </span>
                                        </li>
                                    <?php endforeach; ?>
                                <?php endif; ?>    
                            </ul>
                        <?php endforeach; ?>
    
                    <?php endif; ?>
                    <!--BudgetLine Ends-->                 
                </li>
            </ul><!--Ends .style-2-->

        </div><!--Ends .current-->

    <?php endforeach; ?>

</li><!-- end of element-activity -->