<?php if($this->docUrl):?>
    Your document has been uploaded. Your document's url is
    <a href="<?php echo $this->docUrl; ?>" target="__blank"><?php echo $this->docUrl;?></a>.
    Please <a href="<?php echo $this->docUrl;?>" class="use-this">Use this</a>
<?php else:?>
    <div class="information">
        You can upload your document here. Once your document is uploaded, a link will be provided.
        You can then select the link to use it.
    </div>
<?php endif;?>

<div>
    <?php echo $this->form;?>
</div>

<?php if($this->docs):?>
<table>
    <thead>
        <tr>
            <th>S No.</th>
            <th>Document Link</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php $count = 1;?>
        <?php foreach($this->docs as $document):?>
        <?php $url = "http://" . $_SERVER['HTTP_HOST']. $this->baseUrl().'/files/documents/'.$document['filename'];?>
        <tr>
            <td><?php echo $count;?></td>
            <td><?php echo $url?></td>
            <td><a href="<?php echo $url; ?>" class="use-this">Use this</a></td>
        </tr>
        <?php $count++;?>
        <?php endforeach;?>
    </tbody>
</table>
        
<?php endif;?>
