<?php if($this->docs):?>
<table>
    <thead>
        <tr>
            <th class="s-num">S No.</th>
            <th class="doc-link">Document Link</th>
            <th class="use-this"></th>
        </tr>
    </thead>
    <tbody>
        <?php $count = 1;?>
        <?php foreach($this->docs as $document):?>
            <?php $url = "http://" . $_SERVER['HTTP_HOST']. $this->baseUrl().'/files/documents/'.$document['filename'];?>
            <tr>
                <td><?php echo $count;?></td>
                <td><?php echo $url?></td>
                <td><a href="<?php echo $url; ?>" class="use-this">Use this</a></td>
            </tr>
        <?php $count++;?>
        <?php endforeach;?>
    </tbody>
</table>
<?php else: ?>
    Sorry no documents were uploaded previously.    
<?php endif;?>