<?php
    $publishedFilesOfOrganisation = $this->published_files_organisation;
?>
<div class="files">
    <?php if(empty($publishedFilesOfOrganisation)): ?>
        <div class="no-data">You haven't published any organisation files yet. Please go to
        <?php print $this->l('Organisation data' , 'organisation/organisation-data') ?>
        to publish your completed organisation file. </div>

    <?php else: ?>
        <table class="activity-list-table published-files-of-organisation-list-table">
            <thead>
                <?php if($this->publish_permission): ?>
                <th></th>
                <?php endif; ?>
                <th>Filename</th>
                <th>Published Date</th>
                <th class="registered-info"'>Registered in IATI Registry</th>
                <th>Preview As</th>
                <th></th>
            </thead>
            <?php foreach ($publishedFilesOfOrganisation as $fileOfOrganisation): ?>
            <tr>
                <?php if($this->publish_permission): ?>
                <td><?php if(!$this->update_to_registry): ?><input type="checkbox" name="file_<?php echo $fileOfOrganisation['id']?>" value="<?php echo $fileOfOrganisation['id']?>"<?php ($fileOfOrganisation['status'])? print("checked='checked'") : print("disabled='disabled'"); ?>" /><?php endif; ?></td>
                <?php endif; ?>

                <td><a href="<?php echo $this->baseUrl().Zend_Registry::get('config')->xml_folder.$fileOfOrganisation['filename']?>" target="_blank"><?php echo $fileOfOrganisation['filename'] ?></a></td>
                <td><?php echo $fileOfOrganisation['published_date'] ?></td>
                <td>
                <?php if( $fileOfOrganisation['pushed_to_registry']): ?>
                	<?php $dataset = preg_replace('/.xml$/' , '' , $fileOfActivities['filename']); ?>
                	<a href="http://iatiregistry.org/dataset/<?php echo $dataset; ?>"  target='_blank' title="view file in IATI Registry">Yes</a>
                <?php else:?>
                	No
                <?php endif; ?>
                </td>
                <td><a href='http://tools.aidinfolabs.org/showmydata/index.php?url=http://<?php echo $_SERVER['SERVER_NAME'].$this->baseUrl().Zend_Registry::get('config')->xml_folder.$fileOfOrganisation['filename']?>' target='_blank'>IATI Data</a> | <a href='http://tools.aidinfolabs.org/csv/direct_from_registry/?xml=http://<?php echo $_SERVER['SERVER_NAME'].$this->baseUrl().Zend_Registry::get('config')->xml_folder.$fileOfOrganisation['filename']?>' target='_blank'>CSV</a></td>
                <?php
                    $class = "delete-files";
                    if($fileOfOrganisation['pushed_to_registry']){
                        $class .= " published";
                    } else {
                        $class .= " unpublished";
                    }
                ?>
                <td><?php (!$fileOfOrganisation['status'])? print $this->l('Delete' , 'organisation/delete-published-file?file_id='.$fileOfOrganisation['id'] , array('attributes'=>array('class'=>"$class" , 'title' => 'delete file'))):''; ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
            <?php if($this->publish_permission): ?>
                <?php echo $this->formForOrganisation; ?>
		
		<?php if(Model_Help::showHelpforPushToRegistry()): ?>
		<div class="tooltip-wrapper">
		<div class="custom-tooltip-dialog tooltip-up custom-tooltip-registry">
		       <div class="custom-tooltip-wrapper">
			<span class="custom-tooltip-pointer"></span>
		       <p>To push the organisation XML files to IATI Registry, please click on "Register to IATI Registry" button.</p>
		       </div>
		</div>
		</div>
	    <?php endif; ?>
            <?php endif; ?>
    <?php endif; ?>
</div>