<?php
    print $this->blockManager()->get('partial/override-activity.phtml');
    print $this->blockManager()->get('partial/activitymenu.phtml');
    print $this->blockManager()->get('partial/primarymenu.phtml');
    print $this->blockManager()->get('partial/add-activity-menu.phtml');
    print $this->blockManager()->get('partial/usermgmtmenu.phtml');
    print $this->blockManager()->get('partial/superadmin-menu.phtml');
?>