	<div class="about-tagline">
		A <span>better and easy way</span> to publish Aid data in IATI format.
	</div>
	<div class="description-container">
	<div class="description">
		<h2>background</h2>
		<p>The issue of foreign aid transparency and aid effectiveness has been a topic of debate and discussion at an international level since quite some time.</p>
	</div>
	</div>	
	<div class="format-container">
		<div class="top-container">
			<div class="left-container">
			<h3>NEED FOR A STANDARD FORMAT</h3>
			<p>Making aid data openly available in uniform standard format, both from donors and recipients, is a vital step in making foreign aid more transparent. This open availability of aid data enables individuals and organisations to access aid data , analyse them and ask questions regarding proper implementation of aid driven activities thereby enhancing aid effectiveness and accountability.</p>
		</div>
		<div class="right-container">
			<img src="<?php echo $this->baseUrl();?>/images/img-1.png" width="274" height="195" alt="">
		</div>
		</div>
		<div class="bottom-container">
			<div class="left-container">
			<img src="<?php echo $this->baseUrl();?>/images/img-2.png" width="257" height="61" alt="">			
			</div>
			<div class="right-container">
				<h3>IATI FORMAT</h3>
				<p>International Aid Transparency Initiative (IATI) is one such format endorsed by many countries, governments and donor agencies. This comprehensive format of publishing aid data is envisioned to be used by both donor agencies and reporting organisations. </p>
			</div>
		</div>
		<div class="in-block">However, there seems to be an acute need of a platform to expedite the process of entering and publishing the aid data.</div>
	</div>
	<div class="aid-container">
		<div class="introduction-container">
		<div class="introduction-block">
			<h2>INTRODUCING <span>Aid<span class="stream">Stream</span></span></h2>
			<img src="<?php echo $this->baseUrl();?>/images/img-3.png" width="725" height="255" alt="">
		</div>
		</div>
		<div class="aid-block">
		<div class="aid-top-block">
		<h3>AidStream stands as one such platform, that presents complexity of the IATI in an understandable and a consumable way. </h3>
		<p>User friendly interfaces within the platform enhance an effortless entry, update and publish of the aid data in the IATI format for organisations that want to publish IATI data. The system hides all the complexities and technicalities of the xml. With AidStream, the necessity to understand the details of the IATI standard becomes lesser. All that needs to be done is to register into the system, enter the data and publish it. The data will be easily published to the IATI registry . In addition, AidStream guarantees high security, proper maintenance and easy accessability of the aid data. </p>
		</div>
		<div class="aid-bottom-block">
		<h2>Behind AidStream</h2>
		<div class="aid-left-block">
			<a href="http://aidinfo.org" target="__blank"><img src="<?php echo $this->baseUrl();?>/images/aidinfo-logo.png" width="248" height="136" alt=""></a>
			<p>Aidinfo is based in the UK and works to accelerate poverty reduction by making aid more transparent, particularly through its support of the <a href="http://iatistandard.org" target="__blank">International Aid Transparency Initiative</a>. It acts as the secretariat and provides logistical support for the IATI Technical Advisory Group.</p>
		</div>
		<div class="aid-right-block">
			<a href="http://yipl.com.np" target="__blank"><img src="<?php echo $this->baseUrl();?>/images/yipl-logo.png" width="272" height="76" alt=""></a>
		<p>YoungInnovations is a Nepal-based company providing cutting-edge software and web solutions to a wide range of partners in Nepal and abroad. Currently it is implementing the "<a href="http://mobilenepal.net" target="__blank">Mobile Social Networking Nepal</a>" initiative in partnership with the World Bank's <a href="http://infodev.org" target="__blank">infoDev</a> programme to build a community around mobile technologies. YoungInnovations is also becoming increasingly involved in the open data arena.</p>
		</div>
		</div>
		</div>
