<div class="section black" id="What-is-AidStream">
        <div id="content"> 
            <div id="what-as"><!---Start what-as--->   	
            	<div class="container_12">
                	<div class="grid_12">          	
                        <h1 class="page-title">What is <span class="aid">Aid</span><span class="stream">Stream</span>?</h1>
                        <p class="pragraph-first">Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br /> Aenean pulvinar mauris quis neque rhoncus accumsan.</p>
                        <p class="paragraph-second">Praesent leo ipsum, blandit nec venenatis nec, aliquam vel tortor. Cras ut tellus ac elit<br /> sagittis pellentesque vel non sapien. Nam rutrum sodales erat, molestie facilisis felis<br /> ultrices id. Aenean faucibus dictum commodo. Suspendisse sollicitudin ipsum nec<br /> ante rutrum nec sagittis sem aliquam.</p>
                 	</div>
                </div> 
                <div class="clear"></div>               
            </div><!---Close what-as--->
         </div><!---Close content--->         
         </div><!---Close section block What-is-AidStream--->
         
         <div class="section black" id="How-to-use-AidStream">
         <div id="content">   	
            <div id="how-as"><!---start how-as---> 
            	<div class="container_12">
                	<div class="grid_12">
                    	<h1 class="page-title">How to use <span class="aid">Aid</span><span class="stream">Stream</span>?</h1>
                        <p class="pragraph-first">Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br /> Aenean pulvinar mauris quis neque rhoncus accumsan.</p>	
                        <div class="registration">
                        	<span>Registration</span><br />Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                             Aenean pulvinar mauris quis neque rhoncus accumsan.
                        </div>
                        <div class="data-entry">
                            <span>Data Entry</span><br />Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                             Aenean pulvinar mauris quis neque rhoncus accumsan.
                        </div>
                        <div class="publish">
                            <span>Publish</span><br />Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                             Aenean pulvinar mauris quis neque rhoncus accumsan.
                        </div>                      
                    </div>
                </div>
                <div class="clear"></div>
            </div><!---Close how-as--->
         </div><!---Close content--->         
         </div><!---Close section block How-to-use-AidStream--->
            	
         <div class="section black" id="Contacts">
         <div id="content">    
            <div id="contact-us">
            	<div class="container_12">
                	<div class="grid_12">
                    	<h1 class="page-title">Contact Us</h1>
                        <p class="pragraph-first">Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br /> Aenean pulvinar mauris quis neque rhoncus accumsan.</p>
                        <form>
                        	<table>
                            	<tr>
                                	<td><label>Name</label></td>
                                    <td><input name="name" type="text" /></td>
                                </tr>
                                <tr class="note">
                                	<td></td>
                                    <td>So that we know who to rely.</td>
                                </tr>
                                <tr>
                                	<td><label>Email</label></td>
                                    <td><input name="email" type="text" /></td>
                                </tr>
                                <tr class="note">
                                	<td></td>
                                    <td>So that we know who to reply.</td>
                                </tr>
                                <tr>
                                	<td style="vertical-align:top"><label>Massage</label></td>
                                    <td><textarea name="massage" cols="20" rows="8"></textarea></td>
                                </tr>
                                <tr class="note">
                                	<td></td>
                                	<td>So that we know who to reply.</td>
                                </tr>
                                <tr>
                                	<td></td>
                                	<td><input id="send-bottom" type="button" name="send" value="Send" /></td>
                                </tr>
                            </table>
                        </form>   
                    </div>
                </div>
            </div><!---Close contact--->
        </div><!---Close content--->         
       	</div><!---Close section block Contacts--->