<div class="banner-container">
	<div class="banner">
		<div class="banner-content">
			<div class="tagline">
			A better and easy way to publish <a href="http://iatiregistry.org" target="__blank">Aid Data</a> in <a href="http://iatistandard.org" target="__blank">IATI Format</a>.
			</div>
			<p>
			AidStream is an online platform for organisations that wish to publish aid data in the International Aid Transparency Initiative(IATI) format without getting into complexities of IATI. <?php echo $this->l('Learn More', 'about', array('attributes' => array('class' => 'learn-more'))); ?>
			</p>
			<?php echo $this->l('Register Now', 'user/user/register', array('attributes' => array('class' => 'register-now'))); ?>
			<?php echo $this->l('Try a Demo', '/demo.aidstream.org', array('attributes' => array('class' => 'try-demo'))); ?>
		</div>	
		<div class="banner-slideshow">	
		
		<!--<ul class="bjqs">
		  <li><div class="organization-wrapper">
			<a href="#"><div class="organization-start"><div class="count"><span>120</span></div>
				<p><span class="organization">Organizations</span>have already started using it.</p></div>
		  <img src="images/slider1.png" title=""></a></div></li>
		  <li><a href="#"><img src="<?php echo $this->baseUrl();?>/images/slider2.png" title=""></a></li>
		</ul>--> 
        <div id="banner-slide">
        <div class="carousel">
      <ul>
           <li><div class="organization-wrapper">
			<a href="<?php echo $this->baseUrl();?>/users"><div class="organization-start"><div class="count"><span><?php echo $this->orgCount;?></span></div>
				<p><span class="organization">Organizations</span>have already started using it.</p></div>
		  <img src="<?php echo $this->baseUrl();?>/images/slider1.png" title=""></a></div></li>
           <li><a href="#"><img src="<?php echo $this->baseUrl();?>/images/slider2.png" title=""></a></li>
       </ul>
     
   </div> 
     <button class="prev">prev</button>
	<button class="next">next</button>
	</div>
		</div>
	</div>
</div>

<div class="info-block">
	<h1>
		Using AidStream is <span class="easy">easy</span>
	</h1>
	<ul>
		<li><img src="<?php echo $this->baseUrl();?>/images/register.png" width="100" height="100">
			<h2>Register</h2>
			<p><?php echo $this->l('Register'  , 'user/user/register');?> in AidStream with required information.</p>
		</li>
		<li><img src="<?php echo $this->baseUrl();?>/images/entry.png" width="100" height="100">
			<h2>Data Entry</h2>
			<p>You can login and enter the data in an easy manner. </p>
		</li>
		<li class="last"><img src="<?php echo $this->baseUrl();?>/images/publish.png" width="100" height="100">
			<h2>Publish</h2>
			<p>Finally you can publish your activities to IATI-Registry. </p>
		</li>
	</ul>
	<div class="guide-block">
		<span class="guideline">A comprehensive guideline on how to use AidStream is available here:</span>
		<a href="<?php echo $this->baseUrl();?>/how-to" class="learn-more guide">How to use<span>arrow</span></a>
		<div class="section-video">
			<span class="guideline">Watch videos on how to use Aidstream on our</span>
			<a href="https://www.youtube.com/channel/UCAVH1gcgJXElsj8ENC-bDQQ/videos" target="_blank">YouTube</a>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
$(".carousel").jCarouselLite({
      btnNext: ".next",
      btnPrev: ".prev",	
	  visible: 2,
	  scroll: 1,
	  auto: 3000,
	  speed: 800,
	  pauseInterval:3000
 
  });
});

</script>
