<?php
$handler = $this->handler;
$config = new Zend_Config_Ini(APPLICATION_PATH.'/configs/application.ini', APPLICATION_ENV);
$shortname = $config->disqus->shortname;
$identifier = $_GET['reporting_org'];
if (isset($this->organisation_array)):
$organisation = $this->organisation_array;
endif;
?>
<div id="data-wrapper">
    <div class="left-block">
        <?php if (isset($this->total)): ?>
        <div id="aidstream-stats" class="inner-block">
            <h3>AidStream Statistics</h3>
            <p><span><span class="count"><?php print $this->total['organisations']; ?></span>Total no. of Organisations</span></p>
            <p><span><span class="count"><?php print $this->total['activities']; ?></span>Total no. of Actvities</span></p>
            <p><span><span class="count"><?php print $this->total['published']; ?></span>Total no. of Activities published to IATI Registry</span></p>
        </div>
        <?php endif; ?>
        <?php if ($organisation): ?>
        <div class="organisation-data inner-block">
            <div id="organisation-info">
                <h3><?php print $organisation['name']; ?></h3>
                <?php 
                    $filePath = '/uploads/image/'.$organisation['image'];
                    if ($organisation['image']) {
                ?>
                <div id="organization-logo"><img src="<?php print $filePath; ?>" alt="logo"/></div>
                <?php
                    } else {
                ?>
                <div id="organization-logo"><img src="<?php echo '/images/default-user.png' ?>" alt="logo"/></div>
                <?php
                    }
                ?>

                <div id="organisation-contact-info">
                    <h4>Contact Details</h4>
                    <ul>
                        <li><span>Address:</span> <div class="value"><?php print $organisation['address']; ?></div></li>
                        <li><span>Email:</span> <div class="value"><a href="mailto:<?php print $organisation['email']; ?>"><?php print $organisation['email']; ?></a></div></li>
                        <li><span>Website:</span>
                            <div class="value">
                            <?php if ($organisation['website'] != 'Not Available'){ ?>
                                <a href="<?php print $organisation['website']; ?>" target="_blank"><?php print $organisation['website']; ?></a></li>
                            <?php } else { ?>
                                <?php print $organisation['website']; ?></div></li>
                            <?php } ?>
                        <li><span>Telephone:</span> <div class="value"><?php print $organisation['telephone']; ?></div></li>
                        <li><span>Twitter:</span>
                            <div class="value">
                            <?php if ($organisation['twitter'] != 'Not Available'){ ?>
                                <a href="http://twitter.com/<?php print preg_replace("/@/", "", $organisation['twitter'], 1); ?>" target="_blank"><?php print $organisation['twitter']; ?></a></li>
                            <?php } else { ?>
                                <?php print $organisation['twitter']; ?></div></li>
                            <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
        <?php endif; ?>
</div>
<?php if ($handler->get('activities') || (isset($this->total))):?>
<div class="right-block">
    <div class="transaction-wrapper inner-block">
        <h3>Transaction<span id="transaction-info" class="dialog-box-open">help</span></h3>
        <div class="transaction-block">
            <?php $transactions = $handler->get('transaction');?>
            <div class="transactions">
                <div class="heading">Total Commitments</div>
                <div class="value">$<?php echo number_format($transactions->total_commitments->value , 2);?></div>
            </div>
            <div class="transactions">
                <div class="heading">Total Disbursements</div>
                <div class="value">$<?php echo number_format($transactions->total_disbursements->value , 2);?></div>
            </div>
            <div class="transactions">
                <div class="heading">Total Expenditures</div>
                <div class="value">$<?php echo number_format($transactions->total_expenditure->value , 2);?></div>
            </div>
            <div class="transactions">
                <div class="heading">Total Incoming Funds</div>
                <div class="value">$<?php echo number_format($transactions->total_incoming_funds->value , 2);?></div>
            </div>
        </div>
    </div>
</div>

<div class="load-more">Load More...</div>
<div class="block-wrapper">
    <div class="block-inner-wrapper">
        <div class="left-block">
            <div id="inner-block">
                <?php $activities = $handler->getTop3Activities();?>
                <?php if($activities):?>
                <?php $activityCount = $handler->getActivityCount(); ?>
                <div id="published-files" class="inner-block">
                    <h3>Activities<?php if($activityCount > 3): ?><a href="#" class="activities-more">View all (<?php echo $activityCount; ?> activities)</a><?php endif; ?><span id="activities-info" class="dialog-box-open">help</span></h3>
                    <div class="published-block">
                        <ul>
                            <?php foreach($activities as $activityId => $activityTitle): ?>
                            <li><span><?php print $activityId?></span>
                                <div class="value"><?php print $activityTitle; ?></div>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                        <?php if(isset($this->registry_url)): ?>
                        <li><a href="http://iatiregistry.org<?php echo $this->registry_url; ?>" target="_blank">View publisher in IATI Registry</a></li>
                        <?php endif; ?>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
        <div class="right-block">
            <div class="sector-wrapper inner-block">
                <h3>Sector(Top 3)<a href="#inline_content" class="inline">View all</a><span id="sector-info" class="dialog-box-open">help</span></h3>
                <div class="sector">
                    <?php $sectors = $handler->getTop3Sectors(); ?>
                    <?php if($sectors):?>
                    <?php foreach($sectors as $sectorName=>$sectorCount):?>
                    <div><span class="count"><?php echo $sectorCount;?></span><span><?php echo $sectorName;?></span></div>
                    <?php endforeach;?>
                    <?php else: ?>
                    <div class="no-data">No Data Available</div>
                    <?php endif;?>
                </div>
            </div>
        </div> 
    </div>
    <div class="block-inner-wrapper">
        <div id="left-block">
            <div class="inner-block">
                <h3>Activity Status<span id="activity-status-info" class="dialog-box-open">help</span></h3>
                <div id="activity-status"></div>
            </div>
        </div>

        <div id="right-block">
            <div class="block">
                <h3>Recipient Region/Country<span id="recipient-region-country-info" class="dialog-box-open">help</span></h3>
                <div id="recipient-info"></div>
            </div>
        </div>
    </div>
</div>

<?php $sectors = $handler->get('sectors'); ?>
<div style='display:none'>
    <div id='inline_content' style='background:#fff;'>
        <div class="sectors-block">
            <h3>SECTORS</h3>
            <?php if($sectors): ?>
            <?php foreach($sectors as $sectorName=>$sector):?>
            <div class="sector-details"><span class="name"><?php echo $sectorName;?> : </span><span><?php echo $sector->count;?></span></div>
            <?php endforeach;?>
            <?php else :?>
            <div class="no-data">No Data Available</div>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php $activities = $handler->get('activities'); ?>
<div style='display:none'>
    <div id='content' style='background:#fff;'>
        <div class="activities-block">
            <h3>ACTIVITIES</h3>
            <?php if($activities): ?>
            <?php foreach($activities as $activityId=>$activityTitle):?>
            <div class="activity-details"><span class="name"><?php echo $activityId;?></span><span><?php echo $activityTitle;?> </span></div>
            <?php endforeach;?>
            <?php else :?>
            <div class="no-data">No Data Available</div>
            <?php endif; ?>
        </div>
    </div>
</div>

<!-- Help Messages -->
<div style="display:none" >
    <div id='about'>
        <p>
            Snapshot is an overview of aid data published by organisations through AidStream into IATI Registry.
            There are <?php echo sizeof($reportingOrgs) - 1; ?> organisations that have published data into IATI through Aidstream.
            The overview can be viewed for a single organisation or for all the organisations as a whole.
        </p>
        <p>
            The data of activity status, transaction, activity date, sector, recipient country/region
            are presented in the graphical forms for easy understanding. Here, the transaction values
            from all the projects reported by an organisation are summed up and are
            converted into USD using the exchange rates from www.openexchange.org.
        </p>
    </div>
</div>
<div style="display:none" >
    <div id='help-activity-status-info' title="Activity Status">
        <p>
            The following bar graph shows the number of activities in different states. <a href="http://iatistandard.org/codelists/activity_status/" target="__blank">IATI Standard</a>
            defines 5 status for the activity. Any activity can have only one status at a time.
        </p>
    </div>
</div>
<div style="display:none" >
    <div id='help-transaction-info' title="Transaction" class="dialog-box">
        <p>
            The transactions amount under different heading shows the total amount in USD for a given transaction type.
            IATI defines number of transactions types like committment, disbursements.
            The following table show amounts for selected types only. <a href="http://iatistandard.org/codelists/transaction_type/" target="__blank">IATI Standard</a> gives
            the details on the meaning of each transaction type.
        </p>
    </div>
</div>
<div style="display:none" >
    <div id='help-sector-info' title="Sector">
        <p>
            Sectors shows the number of activities under each sector. An activity may fall under more than one sector.
        </p>
    </div>
</div>
<div style="display:none" >
    <div id='help-recipient-region-country-info' title="Recipient Region/Country">
        <p>
            The bar graph shows the number of activities that are benefiting each of the listed regions/countries.
            A single activity may benefit multiple countries.
        </p>
    </div>
</div>
<div style="display:none" >
    <div id='help-activities-info' title="Activities" class="dialog-box">
        <p>
            More details about the activities can be found in <a href="http://iatiregistry.org" target="__blank">IATI registry</a>
        </p>
    </div>
</div>
<?php else: ?>
<div class="data-info">
    <h2>This organisation has no activity published to the IATI registry.</h2>
</div>
<?php endif; ?>
</div>

<?php if($shortname && ($organisation['disqus_comments']==1) || $identifier=='all'): ?>
<!-- Disqus Thread Starts Here -->
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = '<?php print $shortname ?>'; // Set shortname
    var disqus_identifier = '<?php print $identifier; ?>';
    var disqus_disable_mobile = true;

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
<?php endif; ?>