<?php $images = $this->usersWithImage;?>
<?php $users = $this->usersWithoutImage; ?>

<div id="organisation-total">
    <div class="org-count">
        <span><?php echo $this->count;?> Organisations</span>
        are using aidstream.
    </div>
    <div class="learn-how">
        Aidstream makes it easy to publish data in IATI format without getting into complexities
        <?php echo $this->l('Learn How'  , 'how-to');?>
    </div>
</div>

<div id="organisation-logos">
	<ul>
	<?php foreach($images as $image):?>
		<li>
		<?php if($image['name']):?>
        	<a href='organisation?reporting_org=<?php echo rawurlencode($image['name']); ?>'>
            <div class="img-holder">
		    <img src="<?php echo '/uploads/image/'.$image['file_name']; ?>"
			alt="<?php echo $image['file_name']; ?>"></div>
		    <span class="caption"><?php echo $image['name'];?></span>
            </a>
		<?php endif;?>
		</li>
	<?php endforeach; ?>
	<?php foreach($users as $user): ?>
	    <li>
		<?php if($user['name']):?>
        	<a href='organisation?reporting_org=<?php echo rawurlencode($user['name']); ?>'>
            <div class="img-holder">
		    <img src="<?php echo '/images/default-user.png'; ?>" alt="<?php echo $user['name']; ?>"></div>
		    <span class="caption"><?php echo $user['name'];?></span>
            </a>
		</li>
	<?php endif; ?>
	<?php endforeach;?>
	</ul>
</div>