    <div class="block-wrapper">
        <div id="left-block">
        <div class="organisation-data inner-block">
        <div id="organisation-info">
            <h3><?php print $organisation['name']; ?></h3>
            <?php 
                $filePath = $baseUrl.'/uploads/image/'.$organisation['image']; 
                if ($organisation['image']) {
            ?>
                <div id="organization-logo"><img src="<?php print $filePath; ?>" alt="logo"/></div>
            <?php       
                } else {    
            ?>
                <div id="organization-logo"><img src="<?php echo $this->baseUrl().'/images/default-user.png' ?>" alt="logo"/></div>
            <?php
                }
            ?>
       
        <div id="organisation-contact-info">
            <h4>Contact Details</h4>    
            <ul>    
                <li>Address: <?php print $organisation['address']; ?></li>
                <li>Telephone: <?php print $organisation['telephone']; ?></li>
                <li>Email: <a href="mailto:<?php print $organisation['email']; ?>"><?php print $organisation['email']; ?></a></li>

                <li>Website: 
                <?php if ($organisation['website'] != 'Not Available'){ ?>
                    <a href="<?php print $organisation['website']; ?>" target="_blank"><?php print $organisation['website']; ?></a></li><?php } else { ?>
                    <?php print $organisation['website']; ?></li>
                <?php } ?>
                <li>Twitter:
                <?php if ($organisation['twitter'] != 'Not Available'){ ?>
                    <a href="http://twitter.com/<?php print preg_replace("/@/", "", $organisation['twitter'], 1); ?>" target="_blank"><?php print $organisation['twitter']; ?></a></li><?php } else { ?>
                    <?php print $organisation['twitter']; ?></li>
                <?php } ?>
                
            </ul>
        </div>
         </div>
    </div>
            <div class="inner-block">
                <h3>Activity Status<span id="activity-status-info" class="dialog-box-open">help</span></h3>
                <div id="activity-status">
                </div>
            </div>
            
            <div class="inner-block">
                <h3>Activity Dates<span id="activity-date-info" class="dialog-box-open">help</span></h3>
                <div id="activity-dates"></div>
            </div>
            
            <div class="block">
                <h3>Recipient Region/Country<span id="recipient-region-country-info" class="dialog-box-open">help</span></h3>
                <div id="recipient-info">
                </div>
            </div>
        </div>
        
        <div id="right-block">

           <div class="transaction-wrapper inner-block">
                <h3>Transaction<span id="transaction-info" class="dialog-box-open">help</span></h3>
                <div class="transaction-block">
                <?php $transactions = $handler->get('transaction');?>         
                        <div class="transactions">
                            <div class="heading">Total Commitments</div>
                            <div class="value">$<?php echo number_format($transactions->total_commitments->value , 2);?></div>
                        </div>
                        <div class="transactions">
                            <div class="heading">Total Disbursements</div>
                            <div class="value">$<?php echo number_format($transactions->total_disbursements->value , 2);?></div>
                       
                        </div>
                  
                       <div class="transactions">
                            <div class="heading">Total Expenditures</div>
                            <div class="value">$<?php echo number_format($transactions->total_expenditure->value , 2);?></div>
                        </div>
                        <div class="transactions">
                            <div class="heading">Total Incoming Funds</div>
                            <div class="value">$<?php echo number_format($transactions->total_incoming_funds->value , 2);?></div>
                        </div>              
             
            </div>
        
            <div class="sector-wrapper inner-block">
                <h3>Sector(Top 3)<a href="#inline_content" class="inline">View all</a><span id="sector-info" class="dialog-box-open">help</span></h3>
                <div class="sector">
                <?php $sectors = $handler->getTop3Sectors(); ?>
                <?php if($sectors):?>
                    <?php foreach($sectors as $sectorName=>$sectorCount):?>
                        <div><span class="count"><?php echo $sectorCount;?></span><span><?php echo $sectorName;?></span></div>
                    <?php endforeach;?>
                <?php else: ?>
                    <div class="no-data">No Data Available</div>
                <?php endif;?>
                </div>
            </div>
            
            <div class="activities-wrapper inner-block">
                <?php $activities = $handler->get('activities');?>
                <?php if($activities):?>
                <h3>Activities<span id="activities-info" class="dialog-box-open">help</span></h3>
                <div class="activities-block">
                <ul>
                    <?php foreach($activities as $activityId => $activity):?>
                        <li><span><?echo $activityId;?></span></li>
                    <?php endforeach;?>
                </ul>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    </div>