<?php
    $this->headLink()->prependStylesheet($this->baseUrl() . '/js/select2/select2.css');

    $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-min-1.7.js', $type = 'text/javascript'); 
    $this->headScript()->appendFile($this->baseUrl() . '/js/select2/select2.js', $type = 'text/javascript');
    
?>

<div>
<?php echo $this->form;?>
</div>

<script>
    $(document).ready(function() {
            $("#sector").select2({
                placeholder: "Select Anyone",
            });
        });
</script>