<?php
    $this->headLink()->appendStylesheet($this->baseUrl() . '/js/select2/select2.css');

    $this->headScript()->prependFile($this->baseUrl() . '/js/jquery-min-1.7.js', $type = 'text/javascript'); 
    $this->headScript()->appendFile($this->baseUrl() . '/js/select2/select2.js', $type = 'text/javascript');
    
?>
<?php
    $activityInfo = $this->activityInfo;
?>
<? if($activityInfo): ?>
<?
    $title = "(" ;
    $title .= ($activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>
<div class="activity-title">
    <span class="activity_identifier"> <?php print $activityInfo['iati_identifier']; ?> </span>
    <span class="activity_title"> <?php print $title;?> </span>
    <span class="viewer-link"><?php echo $this->l('View Activity', 'wep/view-activity/'. $activityInfo['id'])?></span>
</div>
<div class="second-title">Editing <span><?php print ('Activity Default') ?>...</span></div>
<? endif; ?>
<?php print $this->form?>

<script>
    $(document).ready(function() {
            $("#sector").select2({
                placeholder: "Select Anyone",
            });
        });
</script>