<?php
    $activityData = $this->activityData;
    $activityId = $this->activity_id;
    $change_status_form = $this->status_form;
    $model = new Model_Wep();
?>

<div id="simplified_activity">
    <div class="title-edit-wrapper">
        <div class = "edit-link"><?php echo $this->l('Edit this Activity', 'simplified/default/edit-activity/?activity_id='
                                                                    . $this->activityInfo['id'])?>
            </div>
        <div class="activity-title"> <?php print ($activityData['title'])?$activityData['title']:'No Title' ?></div>

        <div class="activity-identifier"> <span class="activity-identifier-title">Project Identifer: </span><span class="activity-identifier-value"><?php print $this->activityInfo['activity_identifier']?></span></div>
        <div class="clear"></div>
    </div>
    
    <div class= "activity-state">
        <div class="state-display">
            <ul class='state-<?php echo $this->state;?>'>
                <li class='label'>Activity State</li>
                <?php foreach(Iati_WEP_ActivityState::getStatus() as $state_value => $state_name):?>
                    <li <?php if($this->state == $state_value) {print "id='current-state'";}?> ><span class='<?php print (!in_array($state_value,Iati_WEP_ActivityState::getRemainingStates($this->state)))?'visited-state':'not-visited-state'; ?>'><?php print $state_name ?></span></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class='change-state'>
            <div class="change-state-info-section">This activity is in <span class="change-state-current-state"><?php print(Iati_WEP_ActivityState::getStatus($this->state));?></span> State. <?php if($this->state != Iati_WEP_ActivityState::STATUS_PUBLISHED): ?>Mark it as <?php print($change_status_form)?><?php endif; ?></div>
            <div class="change-state-help-section"><span class="change-state-help"><a href="#">what's this?</a></span></div>
        </div>
    </div>

    <div class="activity-elements-view-wrapper">
        <div class="activity-elements-view-title">
            Project Information
        </div>
        <table class="activity-elements-view" id="project-info-view">
            <tr class="activity_view_first"><td class="activity_view_label">Description</td><td><?php echo $activityData['description'];?></td></tr>
            <tr><td class="activity_view_label">Funding Organisation</td><td><?php if($activityData['funding_org']) { foreach($activityData['funding_org'] as $fundingOrg) { echo $fundingOrg."<br>";}}?></td></tr>
            <tr><td class="activity_view_label">Actual Start Date</td><td><?php echo $activityData['start_date'];?></td></tr>
            <tr><td class="activity_view_label">Actual End Date</td><td><?php echo $activityData['end_date'];?></td></tr>
            <?php if($activityData['sector']): ?>
            <tr><td class="activity_view_label">Sector</td><td><?php foreach($activityData['sector'] as $sector) { echo $model->fetchValueById('Sector' , $sector, 'Name');echo "<br>";} ?></td></tr>
            <?php endif;?>
        </table>
    </div>
    
    
    <div class="activity-elements-view-wrapper">
        <div class="activity-elements-view-title">
            Location Information
        </div>
        <table class="activity-elements-view" id="document-info-view">
            <thead>
                <tr class="table-header"><th>District</th><th>Vdcs</th></tr>
            </thead>
            <?php if ($activityData['location']): ?>
            <?php foreach($activityData['location'] as $location):?>
                <tr>
                    <td class="table-width"><?php echo ($location['location_name'])?$location['location_name']:'-';?></td>
                    <td><?php echo ($location['location_vdcs'])? ($location['location_vdcs']):'-';?></td></td>
                </tr>
            <?php endforeach;?>
            <?php endif; ?>
        </table>
    </div>

    <div class="activity-elements-view-wrapper">
        <div class="activity-elements-view-title">
            Document Information
        </div>
        <table class="activity-elements-view" id="document-info-view">
            <thead>
                <tr class="table-header"><th>Url</th><th>Title</th><th>Category Code</th></tr>
            </thead>
            <?php if ($activityData['document']): ?>
            <?php foreach($activityData['document'] as $document):?>
                <tr><td class="table-width"><?php echo ($document['url'])?$document['url']:'-';?></td><td><?php echo ($document['title'])?$document['title']:'-';?></td><td><?php if($document['category_code']) { echo $model->fetchValueById('DocumentCategory' , $document['category_code']); } else { echo "-";}?></td></tr>
            <?php endforeach;?>
            <?php endif; ?>
        </table>
    </div>

    <div class="activity-elements-view-wrapper">
        <div class="activity-elements-view-title">
            Budget Information
        </div>
        <table class="activity-elements-view" id="budget-info-view">
            <thead>
                <tr class="table-header"><th>Amount</th><th>Start Date</th><th>End Date</th><th>Currency</th><th>Contract Signed Date</th></tr>
            </thead>
            <?php if ($activityData['budget']): ?>
            <?php foreach($activityData['budget'] as $budget):?>
                <tr><td><?php echo ($budget['amount'])?$budget['amount']:"-";?></td><td><?php echo ($budget['start_date'])?$budget['start_date']:'-';?></td><td><?php echo ($budget['end_date'])?$budget['end_date']:'-';?></td><td><?php if($budget['currency']) { echo $model->fetchValueById('Currency' , $budget['currency']); } else {echo "-";} ?></td><td><?php echo ($budget['signed_date'])?$budget['signed_date']:'-';?></td></tr>
            <?php endforeach;?>
            <?php endif; ?>
        </table>
    </div>

    <div class="activity-elements-view-wrapper">
        <div class="activity-elements-view-title">
            Incoming Fund Information
        </div>
        <table class="activity-elements-view" id="incomming-fund-info-view">
            <thead>
                <tr class="table-header"><th>Amount</th><th>Date</th><th>Currency</th></tr>
            </thead>
            <?php if($activityData['incommingFund']): ?>
            <?php foreach($activityData['incommingFund'] as $incommingFund):?>
                <tr><td><?php echo ($incommingFund['amount'])?$incommingFund['amount']:"-";?></td><td><?php echo ($incommingFund['start_date'])?$incommingFund['start_date']:"-";?></td><td><?php if($incommingFund['currency']) { echo $model->fetchValueById('Currency' , $incommingFund['currency']); } else {echo "-";}?></td></tr>
            <?php endforeach;?>
            <?php endif;?>
        </table>
    </div>

    <div class="activity-elements-view-wrapper">
        <div class="activity-elements-view-title">
            Expenditure Information
        </div>
        <table class="activity-elements-view" id="expenditure-info-view">
            <thead>
                <tr class="table-header"><th>Amount</th><th>Date</th><th>Currency</th></tr>
            </thead>
            <?php if ($activityData['expenditure']): ?>
            <?php foreach($activityData['expenditure'] as $expenditure):?>
                <tr><td><?php echo ($expenditure['amount'])?$expenditure['amount']:'-';?></td><td><?php echo ($expenditure['start_date'])?$expenditure['start_date']:'-';?></td><td><?php if($expenditure['currency']) { echo $model->fetchValueById('Currency' , $expenditure['currency']); } else { echo "-"; }?></td></tr>
            <?php endforeach;?>
            <?php endif; ?>
        </table>
    </div>
    
    <div class="activity-elements-view-wrapper">
        <div class="activity-elements-view-title">
            Results Information
        </div>
        <table class="activity-elements-view" id="expenditure-info-view">
            <thead>
                <tr class="table-header"><th>Result Type</th><th>Title</th><th>Description</th><th>Indicator</th><th>Acheivement</th><th>End Date</th></tr>
            </thead>
            <?php if ($activityData['result']): ?>
            <?php foreach($activityData['result'] as $result):?>
                <tr>
                    <td><?php echo ($result['result_type'])?$result['result_type']:'-';?></td>
                    <td><?php echo ($result['title'])?$result['title']:'-';?></td>
                    <td><?php echo ($result['description'])?$result['description']:'-';?></td>
                    <td><?php echo ($result['indicator'])?$result['indicator']:'-';?></td>
                    <td><?php echo ($result['achievement'])?$result['achievement']:'-';?></td>
                    <td><?php echo ($result['end_date'])?$result['end_date']:'-';?></td>
                </tr>
            <?php endforeach;?>
            <?php endif; ?>
        </table>
    </div>
</div>