<table id="users-list">
  <tr class="th-border">
    <th>User</th>
    <!--<th>Sign Up Date</th>-->
    <th>View Details</th>
    <th>Operation</th>
  </tr>
  
  <?php //var_dump($this->data);exit();
    $class = "odd";
        foreach($this->data as $value):?>
  <tr id = "<?php print $class;?>">
    <td><?php print $value["email"]?></td>
    <!--<td><?php /*print $value['created']*/?></td>-->
    <td><?php print $this->l('View Detail','admin/view/id/'.$value['user_id']);?></td>
    <td>
        <?php print $this->l('Approve','admin/approve/id/'.$value['user_id']);?>
        <?php print $this->l('Reject','admin/reject/id/'.$value['user_id'], array('attributes'=>array('onclick' => "javascript: retutn confirm('Do you want to reject?')")));?>
    </td>
  </tr>
  <?php endforeach;?>
</table>
