<table id="list-org">
<thead>
<tr>
    <th>S.N.</th><th>Organisation Name</th><th>Users</th><th>Activities</th><th>Status</th><th>Simplified</th><th>Displayed In Footer</th><th>Action</th>
<!--    <th>Action</th>-->
</tr>
</thead>

<?php //print_r($this->rowSet);exit;?>
<?php $i = 1;?>
<tbody>
    <?php foreach($this->rowSet as $key=>$row):?>
    <?php $newStatus = ($row['status'])? 0: 1; ?>
    <?php $newDisplay = ($row['display_in_footer'])? 0:1;?>
    <?php $newSimplified = ($row['simplified'])? 0:1;?>
    <tr>
    <td><?php print $i;?></td>
    <td><?php print $row['name']?></td>
    <td><?php print $row['users_count']?></td>
    <td><?php print $row['activity_count']?></td>
    <td class='toggle-status' value='<?php echo $row['status'] ?>'><?php print ($row['status'])?'Enabled': 'Disabled';?></td>
    <td><?php print $this->l((($row['simplified'])?'Yes':'No'),"admin/set-simplified/?org_id=".$row['id']."&simplified=".$newSimplified);?>
    <?php if($row['file_name']):?>
    <td><?php print $this->l((($row['display_in_footer'])?'Yes':'No'),"admin/change-footer-display/?org_id=".$row['id']."&display=".$newDisplay);?>
    <?php else: ?>
    <td><?php print 'No'; ?></td>
    <?php endif;?>


    <td>
        <?php print $this->l('Edit', 'admin/edit-organisation/?id='.$row['id']);?>
        |
        <?php print $this->l('Masquerade', "user/user/masquerade?org_id=".$row['id']."&user_id=".$row['user_id']);?>
        |
        <?php print $this->l((($row['status'])?'Disable':'Enable'),"admin/change-organisation-status/?org_id=".$row['id']."&status=".$newStatus); ?>
        |
        <?php print $this->l('Delete',"admin/delete-organisation/?org_id=".$row['id'] , array("attributes" => array('class' => 'delete-item'))); ?>
    </td>
    </tr>
    <?php $i++;?>
    <?php endforeach;?>
</tbody>

</table>