<?php if (!isset($this->errors)): ?>
<div id="xml-list">
	<?php print $this->xmlForm; ?>
	<ul id="tabs">
    <li><a id="tab1">Activity</a></li>
    <li><a id="tab2">Organisation</a></li>
  	</ul> 
  	<div class="tabs-container" id="tab1C">
	<div class="xml-list-wrapper">
		<table class="xml-list-table" id="activity-xml">
			<thead>
				<tr>
					<th class="empty"><input type="checkbox" class="selectallactivity"></th>
					<th class="num">S.N.</th>
					<th class="filename">Filename</th>
				</tr>
			</thead>
			<tbody>
				<?php $index = 1; ?>
				<?php foreach ($this->activityXml as $xml): ?>
					<tr class="xml-row">
						<td><input type="checkbox" name="xml_<?php print $xml; ?>" value="<?php print $xml; ?>" /></td>
						<td class="sn"><?php print $index; ?></td>
						<td class="filename"><a href="/files/xml/<?php print $xml; ?>" target="_blank"><?php print $xml; ?></a></td>
					</tr>
				<?php $index++; ?>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	</div>
	<div class="tabs-container" id="tab2C">
	<div class="xml-list-wrapper">
	<table class="xml-list-table" id="organisation-xml">
		<thead>
			<tr>
				<th class="empty"><input type="checkbox" class="selectallorganisation"></th>
				<th class="num">S.N.</th>
				<th class="filename">Filename</th>
			</tr>
		</thead>
		<tbody>
			<?php $index = 1; ?>
			<?php foreach ($this->organisationXml as $xml): ?>
				<tr class="xml-row">
					<td><input type="checkbox" name="xml_<?php print $xml; ?>" value="<?php print $xml; ?>" /></td>
					<td class="sn"><?php print $index; ?></td>
					<td class="filename"><a href="/files/xml/<?php print $xml; ?>" target="_blank"><?php print $xml; ?></a></td>
				</tr>
			<?php $index++; ?>
			<?php endforeach; ?>
		</tbody>
	</table>
	</div>
	</div>
</div>
<?php endif; ?>

<?php if (isset($this->errors)): ?>
<div id="validation-errors">
	<p>Validation Report:</p>
	<a href="/admin/validate-xml-files" class="xml-back">Go Back</a>
	<div class="xml-list-wrapper">
	<table class="xml-validation-table">
		<thead>
			<tr>
				<th class="num">S.N.</th><th class="filename">Filename</th><th class="xmlerror">Errors</th>
			</tr>
		</thead>
		<tbody>
			<?php if (count($this->errors)): ?>
				<?php $index = 1; ?>
				<?php foreach ($this->errors as $filename => $errors): ?>
					<tr class="xml-row">
						<td class="sn"><?php print $index; ?></td>
						<td class="filename"><a href="/files/xml/<?php print $filename; ?>" target="_blank"><?php print $filename; ?></a></td>
						<td class="xmlerror">
							<?php 
								if ($errors): 
									foreach ($errors as $error):
										echo $error;
										echo "<br>";
									endforeach;
								else:
									echo "Validation unsucessful, check XML file manually.";
								endif; 
							?>
						</td>
					</tr>
				<?php $index++; ?>
				<?php endforeach; ?>
			<?php else: ?>
				<tr class="xml-row">
					<td class="noerror" colspan="3">Validation Successful.</td>
				</tr>
			<?php endif; ?>
		</tbody>
	</table>
</div>
</div>
<?php endif; ?>