<?php $this->headScript()->appendFile($this->baseUrl() . '/js/common.js', $type = 'text/javascript');
$title = "(" ;
    $title .= ($this->activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>

<div class="activity-title">
    <span class="activity_identifier"> <?php print $this->activityInfo['iati_identifier']; ?> </span>
    <span class="activity_title"> <?php print $title;?> </span>
</div>
<?php
    $url = Zend_Controller_Front::getInstance()->getRequest()->getParams();
    $separator = new Zend_Filter_Word_CamelCaseToSeparator();
    $separator->setSeparator(" ");
    $class = $separator->filter($url['class']);
?>
<div class="second-title">Editing <span><?php print $class ?>...</span>
</div>

<?php print $this->form;?>