<div class = "activity-info-wrapper">
<span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activities_id='
                                                            . $this->activities_id)?></span>
    <div class="title">Activity Default</div>
    <div class = "activity-info">
        <table class ="activity-info-table">
            <tr>
                <th>Default Language:</th><td><?php echo $this->activity_info['@xml_lang'];?></td>
            </tr>
            <tr>
                <th>Default Currency:</th><td><?php echo $this->activity_info['@default_currency'];?></td>
            </tr>
            <tr>
                <th>Hierarchy:</th><td><?php echo $this->activity_info['@hierarchy'];?></td>
            </tr>
        </table>
    
    </div>
</div>

<div>
<?php echo $this->form;?>
</div> 