<?php 
    $title = "(" ;
    $title .= ($this->activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>

<div class="activity-title">
    <div class="element-edit-activity-info-wrapper">
        <span class="activity_identifier"> <?php print $this->activityInfo['activity_identifier']; ?> </span>
        <span class="activity_title"> <?php print $title;?> </span>
    </div>
    <span class="viewer-link"><?php echo $this->l('View Activity', 'wep/view-activity/'. $this->activityInfo['id'])?></span>
    <div class="clear"></div>
</div>
<?php
    $url = Zend_Controller_Front::getInstance()->getRequest()->getParams();
    $separator = new Zend_Filter_Word_CamelCaseToSeparator();
    $separator->setSeparator("_");
    $ele = strtolower($separator->filter($url['class']));
    if(Iati_WEP_ActivityConstants::hasDisplayName($ele)){
        $elementName = Iati_WEP_ActivityConstants::getDisplayName($ele);
    } else {
        $elementName = $url['class'];
    }
    $separator->setSeparator(" ");
    $class = $separator->filter($elementName);
?>
<div class="second-title">Editing <span><?php print $class ?>...</span>
</div>

<?php print $this->form;?>