<?php
    $identity = $this->userInfo();
    $published_data = $this->published_data;
    $file_path = $this->file_path;
?>

<div class="dashboard-content">

<?php if($published_data):?>
    <div class='publish-item'>
        <div class="publis-item-title">Published Files</div>
        <table class="activity-list-table">
            <tr>
                <th>File</th>
                <th>Published Date</th>
            </tr>
        <?php foreach($published_data as $data):?>
            <tr>
                <td>
                    <a href ="<?php echo $this->baseUrl().$file_path.$data['filename'] ?>" target = "_blank"> <?php echo $data['filename'] ?></a>
                </td>
                <td><?php echo $data['published_date'] ?></td>
            </tr>
        <?php endforeach;?>
        </table>
        <div class="go-to-link"><?php print $this->l('View Published Files' , 'wep/view-published-files'); ?></div>
    </div>
<?php else: ?>
<div class="no-data">No activity has been published.</div>
<?php endif;?>

</div>
