<div class="download-activities">

	<div class="default-info">
	If you are looking to download XML files to host in your own server and link to <a href="http://iatiregistry.org" target="__blank"><u><i>IATI Registry</i></u></a>, then ensure that your activities are published. Go to <a href="/wep/list-published-files"><u><i>List Published Files</i></u></a>, right click on the XML link and select "Save Link As..." to save the IATI XML file in your computer.
	</div>

	<ul class="download-links">
		<li><?php echo $this->l('Complete' , 'wep/download-csv?type=complete'); ?> 
		<div class="download-activity">Contains a row for each aid activity. Each activity contains total figures for each type of transaction. Useful for quick verification of the data.</div></li>
		
		<li><?php echo $this->l('Simple' , 'wep/download-csv?type=simple'); ?> 
		<div class="download-activity">Contains full information for each activity with one row per activity. Multiple values for a column (e.g. multiple transactions, multiple sectors) are separated by ";".</div></li>
		
		<li><?php echo $this->l('Transactions' , "wep/download-csv?type=transaction"); ?> <div class="download-activity">Contains a detail list of transactions for all activities with currencies, amounts and classifications. A row for each transaction.</div></li>
		
		<li><?php echo $this->l('Budgets' , "wep/download-csv?type=budget"); ?> <div class="download-activity">Contains a detail list of budgets for all activites with currencies, amounts and dates. A row for each budget entry.</div></li>
	</ul>

</div>