<div class="download-activities">

	<div class="download-xml">
		<h3>Download XML</h3>	
		<ul class="download-links">
			<li><?php echo $this->l('Activity', 'wep/download-xml?name=Activity'); ?><div class="download-activity">XML containting all your activities in any state with all the recent updates. The content of this XML might differ from published activity XML files.</div></li>

			<li><?php echo $this->l('Organisation', 'wep/download-xml?name=Organisation'); ?><div class="download-activity">XML containing your organisation data in any state with all the recent updates. The content of this XML might differ from published organisation data XML file.</div></li>
		</ul>
	</div>

	<div class="download-csv">
		<h3>Download CSV</h3>
		<ul class="download-links">
			<li><?php echo $this->l('Complete' , 'wep/download-csv?type=complete'); ?> 
			<div class="download-activity">Contains a row for each aid activity. Each activity contains total figures for each type of transaction. Useful for quick verification of the data.</div></li>
			
			<li><?php echo $this->l('Simple' , 'wep/download-csv?type=simple'); ?> 
			<div class="download-activity">Contains full information for each activity with one row per activity. Multiple values for a column (e.g. multiple transactions, multiple sectors) are separated by ";".</div></li>
			
			<li><?php echo $this->l('Transactions' , "wep/download-csv?type=transaction"); ?> <div class="download-activity">Contains a detail list of transactions for all activities with currencies, amounts and classifications. A row for each transaction.</div></li>
			
			<li><?php echo $this->l('Budgets' , "wep/download-csv?type=budget"); ?> <div class="download-activity">Contains a detail list of budgets for all activites with currencies, amounts and dates. A row for each budget entry.</div></li>
		</ul>
	</div>

</div>