<?php $this->headScript()->appendFile($this->baseUrl() . '/js/common.js', $type = 'text/javascript');
?>


<?php if($this->activityInfo):?>
<div class = "activity-info-wrapper">
<span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            . $this->activityInfo['id'])?></span>
<div class = "activity-info">
<table>
<tr>
    <td>Language: </td><td><?php print $this->activityInfo['@xml_lang'];?></td>
</tr>
<tr>
    <td>Default Currency: </td><td><?php print $this->activityInfo['@default_currency'];?></td>
</tr>
<tr>
    <td>Hierarchy: </td><td><?php print $this->activityInfo['@hierarchy'];?></td>
</tr>
<tr>
    <td>Last Updated Date Time: </td><td><?php print $this->activityInfo['@last_updated_datetime'];?></td>
</tr>
</table>
</div>
</div>

<?php endif;?>

<?php print $this->form;?>
<!--<?php 
    /*print $this->form;
    print $this->form1;
    print $this->form2;*/
    //foreach($this->forms as $key => $eachForm):?>
   <div>
    <div><?php //print $key;?></div>
    <div>
    <?php //if(($key == 'Activity Date')):?>
    <div></div>
    <?php //print $eachForm;?>
    </div>
    </div>
<?php //endforeach;?>-->