
<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/common.js', $type = 'text/javascript');
?>
<div class="default-info">
On this page you can record default values and settings that will be used for all your activities.
You can also specify which parts of the standard you are going to use,
and how your data will be published. Click on the (?) for more detailed help on each item.
</div>
<div class="defaults-forms">
<? echo $this->form; ?>
</div>
