<?php if(!empty($this->docs)):?>
<?php
    $docs = array();
    foreach($this->usedDocs as $doc){
        $docName = basename($doc['@url']);
        $docs[$docName][] = $doc;
    }
    $found = array();
?>
<h2>Documents uploaded to AidStream</h2>
<table class="uploaded-docs">
    <thead>
        <tr>
            <th>S No.</th>
            <th>Document Link</th>
            <th>Activity Identifier </th>
        </tr>
    </thead>
    <tbody>
        <?php $count = 1;?>
        <?php foreach($this->docs as $document):?>
        <?php $url = "http://" . $_SERVER['HTTP_HOST']. $this->baseUrl().'/files/documents/'.$document['filename'];?>
        <tr>
            <td><?php echo $count;?></td>
            <td><?php echo $url?></td>
            <?php
                $identifiers = '';
                if($docs[$document['filename']]){
                    foreach($docs[$document['filename']] as $doc){
                        $idents[] = $this->l($doc['activity_identifier'] , 'activity/view-activity-info/?activity_id='.$doc['activity_id']);
                    }
                    $identifiers = implode(',' , $idents);
                    unset($docs[$document['filename']]);
                }
            ?>
            <td><?php echo ($identifiers)?$identifiers:'';?></td>
        </tr>
        <?php $count++;?>
        <?php endforeach;?>
    </tbody>
</table>
<?php else:?>
    You have not uploaded any document to AidStream.
<?php endif;?>

<?php if(!empty($docs)):?>
<h2>Other Docs</h2>
    <table class="uploaded-docs">
        <thead>
            <th>S No.</th>
            <th>Document Link</th>
            <th>Activity Identifier </th>
        </thead>
        <tbody>
            <?php $count = 1;?>
            <?php foreach($docs as $docName => $docData):?>
                <?php if(!empty($docData)):?>
                <tr>
                    <td><?php echo $count;?></td>
                    <td><?php echo $docData[0]['@url']; ?></td>
                    <?php
                    $idents = array();
                    foreach($docData as $doc){
                        $idents[] = $this->l($doc['activity_identifier'] ,
                                             'activity/view-activity-info/?activity_id='.$doc['activity_id']
                                            );
                    }
                    $identifiers = implode(',' , $idents);
                    ?>
                    <td><?php echo ($identifiers)?$identifiers:''; ?></td>
                    <?php $count++;?>
                </tr>
                <?php endif;?>
            <?php endforeach;?>
        </tbody>
    </table>
<?php endif;?>