<?
    $publishedFiles = $this->published_files;
?>
<div class="files">
    <? if(empty($publishedFiles)): ?>
        <div class="no-data">You haven't published any files yet. Please go to
        <? print $this->l('List Activities' , 'wep/view-activities') ?>
        to publish your completed activities. </div>

    <? else: ?>
        <table class="activity-list-table published-files-list-table">
            <thead>
                <? if($this->publish_permission): ?>
                <th></th>
                <? endif; ?>
                <th>Filename</th>
                <th>Published Date</th>
                <th>Registered in IATI Regsitry</th>
                <th></th>
            </thead>
            <?php foreach ($publishedFiles as $file): ?>
            <tr>
                <? if($this->publish_permission): ?>
                <td><? if(!$this->update_to_registry): ?><input type="checkbox" name="file_<?php echo $file['id']?>" value="<?php echo $file['id']?>"<?php ($file['status'])? print("checked='checked'") : print("disabled='disabled'"); ?>" /><? endif; ?></td>
                <? endif; ?>

                <td><a href="<?php echo Zend_Registry::get('config')->xml_folder.$file['filename']?>" target="_blank"><?php echo $file['filename'] ?></a></td>
                <td><?php echo $file['published_date'] ?></td>
                <td>
                <?php if( $file['pushed_to_registry']): ?>
                	<?php $response = unserialize($file['response']);?>
                	<a href='<?php echo $response->ckan_url?>' target='_blank' title="view file in IATI Registry">Yes</a>
                <?php else:?>
                	No
                <?php endif; ?>
                </td>
                <?php
                    $class = "delete-files";
                    if($file['pushed_to_registry']){
                        $class .= " published";
                    } else {
                        $class .= " unpublished";
                    }
                ?>
                <td><?php (!$file['status'])? print $this->l('Delete' , 'wep/delete-published-file?file_id='.$file['id'] , array('attributes'=>array('class'=>"$class" , 'title' => 'delete file'))):''; ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
        <? if(!$this->update_to_registry): ?>
            <? if($this->publish_permission): ?>
                <?php echo $this->form; ?>
            <? endif; ?>
        <? endif; ?>
    <? endif; ?>
</div>

