<?php if($this->docs):?>
<table class="uploaded-docs">
    <thead>
        <tr>
            <th>S No.</th>
            <th>Document Link</th>
            <th>Activity Identifier </th>
        </tr>
    </thead>
    <tbody>
        <?php $count = 1;?>
        <?php foreach($this->docs as $document):?>
        <?php $url = "http://" . $_SERVER['HTTP_HOST']. $this->baseUrl().'/files/documents/'.$document['filename'];?>
        <tr>
            <td><?php echo $count;?></td>
            <td><?php echo $url?></td>
            <td></td>
        </tr>
        <?php $count++;?>
        <?php endforeach;?>
    </tbody>
</table>
<?php endif;?>