<!--Starts of Displaying Published Files of an Organisation-->
<?php echo $this->partial("partials/published-files/organisation-published-files.phtml" , array(
                                                                                            'published_files_organisation'=>$this->published_files_organisation,
                                                                                            'publish_permission' => $this->publish_permission,
                                                                                            'formForOrganisation' => $this->formForOrganisation  
                                                                                            )
                          );
?>
<!--Ends of Displaying Published Files of an Organisation-->

<!--Starts of Displaying Published Files of an Activities-->
<?php echo $this->partial("partials/published-files/activities-published-files.phtml" , array(
                                                                                            'published_files_activities'=>$this->published_files_activities,
                                                                                            'publish_permission' => $this->publish_permission,
                                                                                            'formForActivities' => $this->formForActivities 
                                                                                            )
                          );
?>
<!--Ends of Displaying Published Files of an Activities-->

