<?
$publishedFiles = $this->published_files;
?>
<div class="files">
<table class="activity-list-table">
    <thead>
        <th>Filename</th>
        <th>Published Date</th>
        <th></th>
    </thead>
    <?php foreach ($publishedFiles as $file): ?>
    <tr>
        <td><?= $file['filename'] ?></td>
        <td><?= $file['published_date'] ?></td>
        <td><?php (!$file['status'])? print $this->l('Delete' , 'wep/delete-published-file?file_id='.$file['id'] , array('attributes'=>array('class'=>'delete-files'))):''; ?></td>
    </tr>
    <?php endforeach; ?>
</table>
</div>

