<div class = 'default-info default-notice'>
  This is read only version of Aidstream that supports IATI standard version 1.03. Any changes done here will be lost. please go to version 2.01 <a href="http://aidstream.org" target="_blank">Aidstream</a> to add and update activities.
</div>
<?php
    $identity = $this->userInfo();
    if($identity->role == 'user'){
        $model = new Model_Wep();
        $userPermission = $model->getUserPermission($identity->user_id);
    }
    $model_user = new Model_User();
    
?>

<?php if($this->activities_info):?>
<div>
<table>
<tr>
    <td>Version: </td><td><?php print $this->activities_info['@version'];?></td>
</tr>
<tr>
    <td>Generated Date Time: </td><td><?php print $this->activities_info['@generated_datetime'];?></td>
</tr>
</table>
</div>
<?php endif;?>

<?php $i = 1;?>

<?php if($this->activity_array):?>
<div class = "activity-list">
    <table class ="activity-list-table">
        <thead>
            <tr>
                <th></th><th>S.N.</th><th>Title</th><th>Activity Identifier</th><th>Last Updated</th><th>State</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->activity_array as $eachActivity):?>
            <tr class="activity-row1">
               <td><input type="checkbox" name="activity_<?php echo $eachActivity['id']?>" value="<?php echo $eachActivity['id']?>"<?php ($eachActivity['status_id'] == Iati_WEP_ActivityState::STATUS_VERIFIED)? print("checked='checked'"): print("disabled='disabled'");?> /></td>
                <td class="sn"><?php print $i;?></td>
                <td class="title"><div class='title-activity'><?php print $eachActivity['title'];?></div>
                <?php if($userPermission):?>
                    <div class = "list-action">
                        <?php $permission = $userPermission->hasPermission(Iati_WEP_PermissionConts::VIEW_ACTIVITIES);
                        if($permission == '1'){
                            print $this->l('View', 'activity/view-activity-info/?activity_id='.$eachActivity['id']);
                        }
                        $permission = $userPermission->hasPermission(Iati_WEP_PermissionConts::ADD_ACTIVITY);
                        if ($permission == '1'){
                            print $this->l('Duplicate', 'activity/duplicate-activity/?activity_id='.$eachActivity['id']);
                        }
                        $permission = $userPermission->hasPermission(Iati_WEP_PermissionConts::DELETE_ACTIVITY);
                        if($permission == '1'){
                            print $this->l('Delete', 'activity/delete-activity/?className=Activity&activity_id='.$eachActivity['id'],
                           array('attributes' => array('onclick' => "javascript: return confirm('Do you really want to delete?')")));
                        }
                        ?>
                        
                    </div>
                <?php endif;?>
                
                <?php if(!$userPermission):?>
                <div class = "list-action">
                <?php print $this->l('View', 'activity/view-activity-info/?activity_id='.$eachActivity['id'])?>
                <?php //print $this->l('Edit', 'wep/edit-activity/?activity_id='.$eachActivity['id'])?>
                <?php print $this->l('Duplicate', 'activity/duplicate-activity/?activity_id='.$eachActivity['id'])?>
                <?php print $this->l('Delete', 'activity/delete-activity/?className=Activity&activity_id='.$eachActivity['id'],
                                     array('attributes' => array('onclick' => "javascript: return confirm('Do you really want to delete?')")))?>
                </div>
                <?php endif; ?>
                <div class='clearfix'></div>
                </td>
                <td class="iati-identifier"><?php print $eachActivity['identifier'];?></td>
                <td class="last-updated"><?php print $eachActivity['last_updated_datetime'];?></td>
                <td class="status <?php echo strtolower(str_replace(" ", "-",Iati_WEP_ActivityState::getStatus($eachActivity['status_id'])));?>"><div><?php echo Iati_WEP_ActivityState::getStatus($eachActivity['status_id']);?></div></td>
            </tr>
            
         <?php $i++;?>
        <?php endforeach;?>
        </tbody>
    </table>
</div>
<?php print ($this->status_form);?>
<?php if(!Model_User::checkHasPublished() && !$model_user->getHelpState(Iati_WEP_ActivityState::STATUS_PUBLISHED)): ?>
    <div class="tooltip-wrapper">
        <div id="publish-button" class="custom-tooltip-dialog tooltip-up">
            <span id="close-dialog" class="close-dialog close-dialog-button">X</span>
            <div class="custom-tooltip-wrapper">
            <span class="custom-tooltip-pointer"></span>
            <div class="dialog-content close-dialog-button">
                <p><?php echo Model_Help::getHelpMessagesForPublishButton(); ?></p>
                <div class="close close-dialog-button" value="4">Got it. Thanks</div>
            </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php else: ?>
<div class="no-data">No activity has been created. Please click on <?php echo $this->l('Add New Activity' , 'wep/add-activity');?> to create new activity.</div>
<?php endif;?>

