<?php
    $this->headScript()->appendFile($this->baseUrl() . '/js/common.js', $type = 'text/javascript');
    $activity = $this->activity;
    $activity_id = $activity->getAttrib('id');
    $change_status_form = $this->status_form;
    $model_wep = new Model_Wep();
?>

<div class= "activity-state">
    <div class="state-display">
        <div class='label'>State: <span class="<?php print strtolower(str_replace(" ", "_", Iati_WEP_ActivityState::getStatus($this->state)))?>"><?php print(Iati_WEP_ActivityState::getStatus($this->state));?></div>
    </div>
    <div class='change-state'>
        <?php print($change_status_form)?>
    </div>
    <?php if($userPermission && $permission == '1'):?>
    <span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            . $this->activityInfo['id'])?></span>
  
<?php endif; ?>
<?php if(!$userPermission): ?>
<span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            . $this->activityInfo['id'])?></span>
  
<?php endif; ?>
</div>
<?php         
    $title = "(" ;
    $title .= ($this->activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>

<div class="activity-title">
    <span class="activity_identifier"> <?php print $this->activityInfo['iati_identifier']; ?> </span>
    <span class="activity_title"> <?php print $title;?> </span>
</div>

<div class="element-title">Activity Default</div>
<table class="activity-detail-table">
<tr>
    <td>

<div class = "activity-info">
<table class ="activity-info-table">
<tr class="element-value-even">
    <td class="label">Language: </td><td><?php print $this->activityInfo['@xml_lang'];?></td>
</tr>
<tr class="element-value-odd">
    <td class="label">Default Currency: </td><td><?php print $this->activityInfo['@default_currency'];?></td>
</tr>
<tr class="element-value-even">
    <td class="label">Hierarchy: </td><td><?php print $this->activityInfo['@hierarchy'];?></td>
</tr>
<tr class="element-value-odd">
    <td class="label">Last Updated Date Time: </td><td><?php print $this->activityInfo['@last_updated_datetime'];?></td>
</tr>
</table>

</div>
</div>
<!-- Transaction Starts -->
<?php
$transactions=$activity->getElementsByType(Iati_Activity_Element::TYPE_TRANSACTION);
$value = $transactions[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Transaction</div>
<div class='element-values'>
<?php foreach($transactions as $transaction):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Ref</td><td class='attrib-value'> <?php if($transaction->getAttrib('@ref')) print ($transaction->getAttribValue('@ref'));?></td></tr>
<tr>
<td colspan=2>

<div class='sub_element'><!-- Sub element Starts -->

<!-- TransactionType Starts -->
<?php
$transactiontypes=$transaction->getElementsByType('TransactionType');
$value = $transactiontypes[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>TransactionType</div>
<div class='element-values'>
<?php foreach($transactiontypes as $transactiontype):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($transactiontype->getAttrib('text')) print ($transactiontype->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($transactiontype->getAttrib('@code')) print ($transactiontype->getAttribValue('@code'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- TransactionType Ends -->


<!-- ProviderOrg Starts -->
<?php
$providerorgs=$transaction->getElementsByType('ProviderOrg');
$value = $providerorgs[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>ProviderOrg</div>
<div class='element-values'>
<?php foreach($providerorgs as $providerorg):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($providerorg->getAttrib('text')) print ($providerorg->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Ref</td><td class='attrib-value'> <?php if($providerorg->getAttrib('@ref')) print ($providerorg->getAttribValue('@ref'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Provider_activity_id</td><td class='attrib-value'> <?php if($providerorg->getAttrib('@provider_activity_id')) print ($providerorg->getAttribValue('@provider_activity_id'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- ProviderOrg Ends -->


<!-- ReceiverOrg Starts -->
<?php
$receiverorgs=$transaction->getElementsByType('ReceiverOrg');
$value = $receiverorgs[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>ReceiverOrg</div>
<div class='element-values'>
<?php foreach($receiverorgs as $receiverorg):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($receiverorg->getAttrib('text')) print ($receiverorg->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Ref</td><td class='attrib-value'> <?php if($receiverorg->getAttrib('@ref')) print ($receiverorg->getAttribValue('@ref'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Receiver_activity_id</td><td class='attrib-value'> <?php if($receiverorg->getAttrib('@receiver_activity_id')) print ($receiverorg->getAttribValue('@receiver_activity_id'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- ReceiverOrg Ends -->


<!-- Value Starts -->
<?php
$values=$transaction->getElementsByType('Value');
$value = $values[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Value</div>
<div class='element-values'>
<?php foreach($values as $value):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($value->getAttrib('text')) print ($value->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Value_date</td><td class='attrib-value'> <?php if($value->getAttrib('@value_date')) print ($value->getAttribValue('@value_date'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Currency</td><td class='attrib-value'> <?php if($value->getAttrib('@currency')) print ($value->getAttribValue('@currency'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Value Ends -->


<!-- Description Starts -->
<?php
$descriptions=$transaction->getElementsByType('Description');
$value = $descriptions[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Description</div>
<div class='element-values'>
<?php foreach($descriptions as $description):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($description->getAttrib('text')) print ($description->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($description->getAttrib('@xml_lang')) print ($description->getAttribValue('@xml_lang'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Description Ends -->


<!-- TransactionDate Starts -->
<?php
$transactiondates=$transaction->getElementsByType('TransactionDate');
$value = $transactiondates[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>TransactionDate</div>
<div class='element-values'>
<?php foreach($transactiondates as $transactiondate):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($transactiondate->getAttrib('text')) print ($transactiondate->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Iso_date</td><td class='attrib-value'> <?php if($transactiondate->getAttrib('@iso_date')) print ($transactiondate->getAttribValue('@iso_date'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- TransactionDate Ends -->


<!-- FlowType Starts -->
<?php
$flowtypes=$transaction->getElementsByType('FlowType');
$value = $flowtypes[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>FlowType</div>
<div class='element-values'>
<?php foreach($flowtypes as $flowtype):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($flowtype->getAttrib('text')) print ($flowtype->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($flowtype->getAttrib('@xml_lang')) print ($flowtype->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($flowtype->getAttrib('@code')) print ($flowtype->getAttribValue('@code'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- FlowType Ends -->


<!-- FinanceType Starts -->
<?php
$financetypes=$transaction->getElementsByType('FinanceType');
$value = $financetypes[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>FinanceType</div>
<div class='element-values'>
<?php foreach($financetypes as $financetype):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($financetype->getAttrib('text')) print ($financetype->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($financetype->getAttrib('@xml_lang')) print ($financetype->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($financetype->getAttrib('@code')) print ($financetype->getAttribValue('@code'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- FinanceType Ends -->


<!-- AidType Starts -->
<?php
$aidtypes=$transaction->getElementsByType('AidType');
$value = $aidtypes[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>AidType</div>
<div class='element-values'>
<?php foreach($aidtypes as $aidtype):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($aidtype->getAttrib('text')) print ($aidtype->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($aidtype->getAttrib('@xml_lang')) print ($aidtype->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($aidtype->getAttrib('@code')) print ($aidtype->getAttribValue('@code'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- AidType Ends -->


<!-- DisbursementChannel Starts -->
<?php
$disbursementchannels=$transaction->getElementsByType('DisbursementChannel');
$value = $disbursementchannels[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>DisbursementChannel</div>
<div class='element-values'>
<?php foreach($disbursementchannels as $disbursementchannel):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($disbursementchannel->getAttrib('text')) print ($disbursementchannel->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($disbursementchannel->getAttrib('@code')) print ($disbursementchannel->getAttribValue('@code'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- DisbursementChannel Ends -->


<!-- TiedStatus Starts -->
<?php
$tiedstatuss=$transaction->getElementsByType('TiedStatus');
$value = $tiedstatuss[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>TiedStatus</div>
<div class='element-values'>
<?php foreach($tiedstatuss as $tiedstatus):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($tiedstatus->getAttrib('text')) print ($tiedstatus->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($tiedstatus->getAttrib('@xml_lang')) print ($tiedstatus->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($tiedstatus->getAttrib('@code')) print ($tiedstatus->getAttribValue('@code'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- TiedStatus Ends -->


</div><!-- Sub element Ends -->

</td></tr></table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Transaction Ends -->


<!-- Conditions Starts -->
<?php
$conditionss=$activity->getElementsByType(Iati_Activity_Element::TYPE_CONDITIONS);
$value = $conditionss[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Conditions</div>
<div class='element-values'>
<?php foreach($conditionss as $conditions):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Attached</td><td class='attrib-value'> <?php if($conditions->getAttrib('@attached')) print ($conditions->getAttribValue('@attached'));?></td></tr>
<tr>
<td colspan=2>

<div class='sub_element'><!-- Sub element Starts -->

<!-- Condition Starts -->
<?php
$conditions=$conditions->getElementsByType('Condition');
$value = $conditions[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Condition</div>
<div class='element-values'>
<?php foreach($conditions as $condition):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($condition->getAttrib('text')) print ($condition->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($condition->getAttrib('@xml_lang')) print ($condition->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Type</td><td class='attrib-value'> <?php if($condition->getAttrib('@type')) print ($condition->getAttribValue('@type'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Condition Ends -->


</div><!-- Sub element Ends -->

</td></tr></table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Conditions Ends -->


<!-- DocumentLink Starts -->
<?php
$documentlinks=$activity->getElementsByType(Iati_Activity_Element::TYPE_DOCUMENT_LINK);
$value = $documentlinks[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>DocumentLink</div>
<div class='element-values'>
<?php foreach($documentlinks as $documentlink):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Url</td><td class='attrib-value'> <?php if($documentlink->getAttrib('@url')) print ($documentlink->getAttribValue('@url'));?></td></tr>
<tr>
<td colspan=2>

<div class='sub_element'><!-- Sub element Starts -->

<!-- Category Starts -->
<?php
$categorys=$documentlink->getElementsByType('Category');
$value = $categorys[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Category</div>
<div class='element-values'>
<?php foreach($categorys as $category):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($category->getAttrib('text')) print ($category->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($category->getAttrib('@code')) print ($category->getAttribValue('@code'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($category->getAttrib('@xml_lang')) print ($category->getAttribValue('@xml_lang'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Category Ends -->


<!-- Title Starts -->
<?php
$titles=$documentlink->getElementsByType('Title');
$value = $titles[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Title</div>
<div class='element-values'>
<?php foreach($titles as $title):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($title->getAttrib('text')) print ($title->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($title->getAttrib('@xml_lang')) print ($title->getAttribValue('@xml_lang'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Title Ends -->


</div><!-- Sub element Ends -->

</td></tr></table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- DocumentLink Ends -->


<!-- Result Starts -->
<?php
$results=$activity->getElementsByType(Iati_Activity_Element::TYPE_RESULT);
$value = $results[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Result</div>
<div class='element-values'>
<?php foreach($results as $result):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Type</td><td class='attrib-value'> <?php if($result->getAttrib('@type')) print ($result->getAttribValue('@type'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Result Ends -->


<!-- PlannedDisbursement Starts -->
<?php
$planneddisbursements=$activity->getElementsByType(Iati_Activity_Element::TYPE_PLANNED_DISBURSEMENT);
$value = $planneddisbursements[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>PlannedDisbursement</div>
<div class='element-values'>
<?php foreach($planneddisbursements as $planneddisbursement):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Updated</td><td class='attrib-value'> <?php if($planneddisbursement->getAttrib('@updated')) print ($planneddisbursement->getAttribValue('@updated'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- PlannedDisbursement Ends -->


<!-- Identifier Starts -->
<?php
$identifiers=$activity->getElementsByType(Iati_Activity_Element::TYPE_IDENTIFIER);
$value = $identifiers[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Identifier</div>
<div class='element-values'>
<?php foreach($identifiers as $identifier):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($identifier->getAttrib('text')) print ($identifier->getAttribValue('text'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Identifier Ends -->


<!-- ContactInfo Starts -->
<?php
$contactinfos=$activity->getElementsByType(Iati_Activity_Element::TYPE_CONTACT_INFO);
$value = $contactinfos[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>ContactInfo</div>
<div class='element-values'>
<?php foreach($contactinfos as $contactinfo):?>
<table class='element-values-items'>
<tr>
<td colspan=2>

<div class='sub_element'><!-- Sub element Starts -->

<!-- Organisation Starts -->
<?php
$organisations=$contactinfo->getElementsByType('Organisation');
$value = $organisations[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Organisation</div>
<div class='element-values'>
<?php foreach($organisations as $organisation):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($organisation->getAttrib('text')) print ($organisation->getAttribValue('text'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Organisation Ends -->


<!-- PersonName Starts -->
<?php
$personnames=$contactinfo->getElementsByType('PersonName');
$value = $personnames[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>PersonName</div>
<div class='element-values'>
<?php foreach($personnames as $personname):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($personname->getAttrib('text')) print ($personname->getAttribValue('text'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- PersonName Ends -->


<!-- Telephone Starts -->
<?php
$telephones=$contactinfo->getElementsByType('Telephone');
$value = $telephones[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Telephone</div>
<div class='element-values'>
<?php foreach($telephones as $telephone):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($telephone->getAttrib('text')) print ($telephone->getAttribValue('text'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Telephone Ends -->


<!-- Email Starts -->
<?php
$emails=$contactinfo->getElementsByType('Email');
$value = $emails[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Email</div>
<div class='element-values'>
<?php foreach($emails as $email):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($email->getAttrib('text')) print ($email->getAttribValue('text'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Email Ends -->


<!-- MailingAddress Starts -->
<?php
$mailingaddresss=$contactinfo->getElementsByType('MailingAddress');
$value = $mailingaddresss[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>MailingAddress</div>
<div class='element-values'>
<?php foreach($mailingaddresss as $mailingaddress):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($mailingaddress->getAttrib('text')) print ($mailingaddress->getAttribValue('text'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- MailingAddress Ends -->


</div><!-- Sub element Ends -->

</td></tr></table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- ContactInfo Ends -->


<!-- ReportingOrg Starts -->
<?php
$reportingorgs=$activity->getElementsByType(Iati_Activity_Element::TYPE_REPORTING_ORG);
$value = $reportingorgs[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>ReportingOrg</div>
<div class='element-values'>
<?php foreach($reportingorgs as $reportingorg):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($reportingorg->getAttrib('text')) print ($reportingorg->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($reportingorg->getAttrib('@xml_lang')) print ($reportingorg->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Ref</td><td class='attrib-value'> <?php if($reportingorg->getAttrib('@ref')) print ($reportingorg->getAttribValue('@ref'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Type</td><td class='attrib-value'> <?php if($reportingorg->getAttrib('@type')) print ($reportingorg->getAttribValue('@type'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- ReportingOrg Ends -->


<!-- OtherIdentifier Starts -->
<?php
$otheridentifiers=$activity->getElementsByType(Iati_Activity_Element::TYPE_OTHER_ACTIVITY_IDENTIFIER);
$value = $otheridentifiers[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>OtherIdentifier</div>
<div class='element-values'>
<?php foreach($otheridentifiers as $otheridentifier):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($otheridentifier->getAttrib('text')) print ($otheridentifier->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Owner_ref</td><td class='attrib-value'> <?php if($otheridentifier->getAttrib('@owner_ref')) print ($otheridentifier->getAttribValue('@owner_ref'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Owner_name</td><td class='attrib-value'> <?php if($otheridentifier->getAttrib('@owner_name')) print ($otheridentifier->getAttribValue('@owner_name'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- OtherIdentifier Ends -->


<!-- Title Starts -->
<?php
$titles=$activity->getElementsByType(Iati_Activity_Element::TYPE_TITLE);
$value = $titles[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Title</div>
<div class='element-values'>
<?php foreach($titles as $title):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($title->getAttrib('text')) print ($title->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($title->getAttrib('@xml_lang')) print ($title->getAttribValue('@xml_lang'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Title Ends -->


<!-- Title Starts -->
<?php
$titles=$activity->getElementsByType(Iati_Activity_Element::TYPE_TITLE);
$value = $titles[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Title</div>
<div class='element-values'>
<?php foreach($titles as $title):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($title->getAttrib('text')) print ($title->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($title->getAttrib('@xml_lang')) print ($title->getAttribValue('@xml_lang'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Title Ends -->


<!-- Description Starts -->
<?php
$descriptions=$activity->getElementsByType(Iati_Activity_Element::TYPE_DESCRIPTION);
$value = $descriptions[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Description</div>
<div class='element-values'>
<?php foreach($descriptions as $description):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($description->getAttrib('text')) print ($description->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($description->getAttrib('@xml_lang')) print ($description->getAttribValue('@xml_lang'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Description Ends -->


<!-- ActivityStatus Starts -->
<?php
$activitystatuss=$activity->getElementsByType(Iati_Activity_Element::TYPE_ACTIVITY_STATUS);
$value = $activitystatuss[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>ActivityStatus</div>
<div class='element-values'>
<?php foreach($activitystatuss as $activitystatus):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($activitystatus->getAttrib('text')) print ($activitystatus->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($activitystatus->getAttrib('@xml_lang')) print ($activitystatus->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($activitystatus->getAttrib('@code')) print ($activitystatus->getAttribValue('@code'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- ActivityStatus Ends -->


<!-- ActivityDate Starts -->
<?php
$activitydates=$activity->getElementsByType(Iati_Activity_Element::TYPE_ACTIVITY_DATE);
$value = $activitydates[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>ActivityDate</div>
<div class='element-values'>
<?php foreach($activitydates as $activitydate):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($activitydate->getAttrib('text')) print ($activitydate->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Type</td><td class='attrib-value'> <?php if($activitydate->getAttrib('@type')) print ($activitydate->getAttribValue('@type'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Iso_date</td><td class='attrib-value'> <?php if($activitydate->getAttrib('@iso_date')) print ($activitydate->getAttribValue('@iso_date'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($activitydate->getAttrib('@xml_lang')) print ($activitydate->getAttribValue('@xml_lang'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- ActivityDate Ends -->


<!-- ParticipatingOrg Starts -->
<?php
$participatingorgs=$activity->getElementsByType(Iati_Activity_Element::TYPE_PARTICIPATING_ORG);
$value = $participatingorgs[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>ParticipatingOrg</div>
<div class='element-values'>
<?php foreach($participatingorgs as $participatingorg):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($participatingorg->getAttrib('text')) print ($participatingorg->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($participatingorg->getAttrib('@xml_lang')) print ($participatingorg->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Ref</td><td class='attrib-value'> <?php if($participatingorg->getAttrib('@ref')) print ($participatingorg->getAttribValue('@ref'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Type</td><td class='attrib-value'> <?php if($participatingorg->getAttrib('@type')) print ($participatingorg->getAttribValue('@type'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- ParticipatingOrg Ends -->


<!-- RecipientCountry Starts -->
<?php
$recipientcountrys=$activity->getElementsByType(Iati_Activity_Element::TYPE_RECIPIENT_COUNTRY);
$value = $recipientcountrys[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>RecipientCountry</div>
<div class='element-values'>
<?php foreach($recipientcountrys as $recipientcountry):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($recipientcountry->getAttrib('text')) print ($recipientcountry->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($recipientcountry->getAttrib('@xml_lang')) print ($recipientcountry->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Percentage</td><td class='attrib-value'> <?php if($recipientcountry->getAttrib('@percentage')) print ($recipientcountry->getAttribValue('@percentage'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($recipientcountry->getAttrib('@code')) print ($recipientcountry->getAttribValue('@code'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- RecipientCountry Ends -->


<!-- RecipientRegion Starts -->
<?php
$recipientregions=$activity->getElementsByType(Iati_Activity_Element::TYPE_RECIPIENT_REGION);
$value = $recipientregions[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>RecipientRegion</div>
<div class='element-values'>
<?php foreach($recipientregions as $recipientregion):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($recipientregion->getAttrib('text')) print ($recipientregion->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($recipientregion->getAttrib('@xml_lang')) print ($recipientregion->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Percentage</td><td class='attrib-value'> <?php if($recipientregion->getAttrib('@percentage')) print ($recipientregion->getAttribValue('@percentage'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($recipientregion->getAttrib('@code')) print ($recipientregion->getAttribValue('@code'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- RecipientRegion Ends -->


<!-- Location Starts -->
<?php
$locations=$activity->getElementsByType(Iati_Activity_Element::TYPE_LOCATION);
$value = $locations[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Location</div>
<div class='element-values'>
<?php foreach($locations as $location):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Percentage</td><td class='attrib-value'> <?php if($location->getAttrib('@percentage')) print ($location->getAttribValue('@percentage'));?></td></tr>
<tr>
<td colspan=2>

<div class='sub_element'><!-- Sub element Starts -->

<!-- LocationType Starts -->
<?php
$locationtypes=$location->getElementsByType('LocationType');
$value = $locationtypes[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>LocationType</div>
<div class='element-values'>
<?php foreach($locationtypes as $locationtype):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($locationtype->getAttrib('text')) print ($locationtype->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($locationtype->getAttrib('@xml_lang')) print ($locationtype->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($locationtype->getAttrib('@code')) print ($locationtype->getAttribValue('@code'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- LocationType Ends -->


<!-- Name Starts -->
<?php
$names=$location->getElementsByType('Name');
$value = $names[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Name</div>
<div class='element-values'>
<?php foreach($names as $name):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($name->getAttrib('text')) print ($name->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($name->getAttrib('@xml_lang')) print ($name->getAttribValue('@xml_lang'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Name Ends -->


<!-- Description Starts -->
<?php
$descriptions=$location->getElementsByType('Description');
$value = $descriptions[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Description</div>
<div class='element-values'>
<?php foreach($descriptions as $description):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($description->getAttrib('text')) print ($description->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($description->getAttrib('@xml_lang')) print ($description->getAttribValue('@xml_lang'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Description Ends -->


<!-- Administrative Starts -->
<?php
$administratives=$location->getElementsByType('Administrative');
$value = $administratives[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Administrative</div>
<div class='element-values'>
<?php foreach($administratives as $administrative):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($administrative->getAttrib('text')) print ($administrative->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($administrative->getAttrib('@xml_lang')) print ($administrative->getAttribValue('@xml_lang'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Administrative Ends -->


<!-- Coordinates Starts -->
<?php
$coordinatess=$location->getElementsByType('Coordinates');
$value = $coordinatess[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Coordinates</div>
<div class='element-values'>
<?php foreach($coordinatess as $coordinates):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Latitude</td><td class='attrib-value'> <?php if($coordinates->getAttrib('@latitude')) print ($coordinates->getAttribValue('@latitude'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Longitude</td><td class='attrib-value'> <?php if($coordinates->getAttrib('@longitude')) print ($coordinates->getAttribValue('@longitude'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Precision</td><td class='attrib-value'> <?php if($coordinates->getAttrib('@precision')) print ($coordinates->getAttribValue('@precision'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Coordinates Ends -->


<!-- GazetteerEntry Starts -->
<?php
$gazetteerentrys=$location->getElementsByType('GazetteerEntry');
$value = $gazetteerentrys[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>GazetteerEntry</div>
<div class='element-values'>
<?php foreach($gazetteerentrys as $gazetteerentry):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($gazetteerentry->getAttrib('text')) print ($gazetteerentry->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Gazetteer_ref</td><td class='attrib-value'> <?php if($gazetteerentry->getAttrib('@gazetteer_ref')) print ($gazetteerentry->getAttribValue('@gazetteer_ref'));?></td></tr>
</table>
<?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- GazetteerEntry Ends -->


</div><!-- Sub element Ends -->

</td></tr></table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Location Ends -->


<!-- Sector Starts -->
<?php
$sectors=$activity->getElementsByType(Iati_Activity_Element::TYPE_SECTOR);
$value = $sectors[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Sector</div>
<div class='element-values'>
<?php foreach($sectors as $sector):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($sector->getAttrib('text')) print ($sector->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($sector->getAttrib('@xml_lang')) print ($sector->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Vocabulary</td><td class='attrib-value'> <?php if($sector->getAttrib('@vocabulary')) print ($sector->getAttribValue('@vocabulary'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($sector->getAttrib('@code')) print ($sector->getAttribValue('@code'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Percentage</td><td class='attrib-value'> <?php if($sector->getAttrib('@percentage')) print ($sector->getAttribValue('@percentage'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Sector Ends -->


<!-- PolicyMarker Starts -->
<?php
$policymarkers=$activity->getElementsByType(Iati_Activity_Element::TYPE_POLICY_MARKER);
$value = $policymarkers[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>PolicyMarker</div>
<div class='element-values'>
<?php foreach($policymarkers as $policymarker):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($policymarker->getAttrib('text')) print ($policymarker->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($policymarker->getAttrib('@xml_lang')) print ($policymarker->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Significance</td><td class='attrib-value'> <?php if($policymarker->getAttrib('@significance')) print ($policymarker->getAttribValue('@significance'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($policymarker->getAttrib('@code')) print ($policymarker->getAttribValue('@code'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Vocabulary</td><td class='attrib-value'> <?php if($policymarker->getAttrib('@vocabulary')) print ($policymarker->getAttribValue('@vocabulary'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- PolicyMarker Ends -->


<!-- CollaborationType Starts -->
<?php
$collaborationtypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_COLLABORATION_TYPE);
$value = $collaborationtypes[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>CollaborationType</div>
<div class='element-values'>
<?php foreach($collaborationtypes as $collaborationtype):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($collaborationtype->getAttrib('text')) print ($collaborationtype->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($collaborationtype->getAttrib('@code')) print ($collaborationtype->getAttribValue('@code'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($collaborationtype->getAttrib('@xml_lang')) print ($collaborationtype->getAttribValue('@xml_lang'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- CollaborationType Ends -->


<!-- DefaultFlowType Starts -->
<?php
$defaultflowtypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_FLOW_TYPE);
$value = $defaultflowtypes[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>DefaultFlowType</div>
<div class='element-values'>
<?php foreach($defaultflowtypes as $defaultflowtype):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($defaultflowtype->getAttrib('@code')) print ($defaultflowtype->getAttribValue('@code'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($defaultflowtype->getAttrib('text')) print ($defaultflowtype->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($defaultflowtype->getAttrib('@xml_lang')) print ($defaultflowtype->getAttribValue('@xml_lang'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- DefaultFlowType Ends -->


<!-- DefaultFinanceType Starts -->
<?php
$defaultfinancetypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_FINANCE_TYPE);
$value = $defaultfinancetypes[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>DefaultFinanceType</div>
<div class='element-values'>
<?php foreach($defaultfinancetypes as $defaultfinancetype):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($defaultfinancetype->getAttrib('@code')) print ($defaultfinancetype->getAttribValue('@code'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($defaultfinancetype->getAttrib('text')) print ($defaultfinancetype->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($defaultfinancetype->getAttrib('@xml_lang')) print ($defaultfinancetype->getAttribValue('@xml_lang'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- DefaultFinanceType Ends -->


<!-- DefaultAidType Starts -->
<?php
$defaultaidtypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_AID_TYPE);
$value = $defaultaidtypes[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>DefaultAidType</div>
<div class='element-values'>
<?php foreach($defaultaidtypes as $defaultaidtype):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($defaultaidtype->getAttrib('@code')) print ($defaultaidtype->getAttribValue('@code'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($defaultaidtype->getAttrib('text')) print ($defaultaidtype->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($defaultaidtype->getAttrib('@xml_lang')) print ($defaultaidtype->getAttribValue('@xml_lang'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- DefaultAidType Ends -->


<!-- DefaultTiedStatus Starts -->
<?php
$defaulttiedstatuss=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_TIED_STATUS);
$value = $defaulttiedstatuss[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>DefaultTiedStatus</div>
<div class='element-values'>
<?php foreach($defaulttiedstatuss as $defaulttiedstatus):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($defaulttiedstatus->getAttrib('@code')) print ($defaulttiedstatus->getAttribValue('@code'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($defaulttiedstatus->getAttrib('text')) print ($defaulttiedstatus->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($defaulttiedstatus->getAttrib('@xml_lang')) print ($defaulttiedstatus->getAttribValue('@xml_lang'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- DefaultTiedStatus Ends -->


<!-- Budget Starts -->
<?php
$budgets=$activity->getElementsByType(Iati_Activity_Element::TYPE_BUDGET);
$value = $budgets[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>Budget</div>
<div class='element-values'>
<?php foreach($budgets as $budget):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Type</td><td class='attrib-value'> <?php if($budget->getAttrib('@type')) print ($budget->getAttribValue('@type'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- Budget Ends -->


<!-- ActivityWebsite Starts -->
<?php
$activitywebsites=$activity->getElementsByType(Iati_Activity_Element::TYPE_ACTIVITY_WEBSITE);
$value = $activitywebsites[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>ActivityWebsite</div>
<div class='element-values'>
<?php foreach($activitywebsites as $activitywebsite):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($activitywebsite->getAttrib('text')) print ($activitywebsite->getAttribValue('text'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- ActivityWebsite Ends -->


<!-- RelatedActivity Starts -->
<?php
$relatedactivitys=$activity->getElementsByType(Iati_Activity_Element::TYPE_RELATED_ACTIVITY);
$value = $relatedactivitys[0]->getAttribs();
if(!empty($value)): ?>
<div class='element-item'><div class='element-title'>RelatedActivity</div>
<div class='element-values'>
<?php foreach($relatedactivitys as $relatedactivity):?>
<table class='element-values-items'>
<tr class='element-value element-value-even'><td class='attrib-label'>Text</td><td class='attrib-value'> <?php if($relatedactivity->getAttrib('text')) print ($relatedactivity->getAttribValue('text'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Xml_lang</td><td class='attrib-value'> <?php if($relatedactivity->getAttrib('@xml_lang')) print ($relatedactivity->getAttribValue('@xml_lang'));?></td></tr>
<tr class='element-value element-value-even'><td class='attrib-label'>Ref</td><td class='attrib-value'> <?php if($relatedactivity->getAttrib('@ref')) print ($relatedactivity->getAttribValue('@ref'));?></td></tr>
<tr class='element-value element-value-odd'><td class='attrib-label'>Code</td><td class='attrib-value'> <?php if($relatedactivity->getAttrib('@code')) print ($relatedactivity->getAttribValue('@code'));?></td></tr>
</table><?php endforeach;?>
</div>
</div>
<?php endif;?>
<!-- RelatedActivity Ends -->

    </td>
</tr>
</table>