<?php $this->headScript()->appendFile($this->baseUrl() . '/js/common.js', $type = 'text/javascript');
?>

<?php if($this->activities_info):?>
<div>
<table>
<tr>
    <td>Version: </td><td><?php print $this->activities_info['@version'];?></td>
</tr>
<tr>
    <td>Generated Date Time: </td><td><?php print $this->activities_info['@generated_datetime'];?></td>
</tr>
</table>
</div>
<?php endif;?>

<?php $i = 1;?>

<?php if($this->activity_array):?>
<div>
    <table>
        <thead>
            <tr>
                <th>S.N.</th><th>Title</th><th>Iati Identifier</th><th>Last Updated</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->activity_array as $eachActivity):?>
            <tr class="activity-row1">
                <td class="sn"><?php print $i;?></td>
                <td class="title"><?php print $eachActivity['title'];?>
                <div class = "list-action"><?php print $this->l('View', 'wep/edit-activity-elements/?activity_id='.$eachActivity['id'])?>
        <?php //print $this->l('Edit', 'wep/edit-activity/?activity_id='.$eachActivity['id'])?>
                            
        <?php print $this->l('Delete', 'wep/delete-activity/?classname=Activity&activity_id='.$eachActivity['id'])?>
                </div></td>
                <td class="iati-identifier"><?php print $eachActivity['identifier'];?></td>
                <td class="last-updated"><?php print $eachActivity['last_updated_datetime'];?></td>
            </tr>
            
         <?php $i++;?>
        <?php endforeach;?>
        </tbody>
    </table>
</div>
<?php endif;?>

<?php print $this->l('Add new', 'wep/add-activity?activities_id='.$this->activities_id,
                                             array('attributes' => array('class' => 'button')));?>
