<?php
    $this->headScript()->appendFile($this->baseUrl() . '/js/common.js', $type = 'text/javascript');
    $activity = $this->activity;
    $activity_id = $activity->getAttrib('id');
    $change_status_form = $this->status_form;
    $model_wep = new Model_Wep();
?>

<div class= "activity-state">
    <div class="state-display">
        <div class='label'>State: <?php print(Iati_WEP_ActivityState::getStatus($this->state));?></div>
    </div>
    <div class='change-state'>
        <?php print($change_status_form)?>
    </div>
</div>
<div class="clear"></div>
<table class="activity-detail-table">
<tr>
    <td>
        
<?php if($userPermission && $permission == '1'):?>
    <span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            . $this->activityInfo['id'])?></span>
  
<?php endif; ?>
<?php if(!$userPermission): ?>
<span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            . $this->activityInfo['id'])?></span>
  
<?php endif; ?>
<div class="title">Activity Default</div>
<div class = "activity-info">
<table class ="activity-info-table">
<tr>
    <td class="label">Language: </td><td><?php print $this->activityInfo['@xml_lang'];?></td>
</tr>
<tr>
    <td class="label">Default Currency: </td><td><?php print $this->activityInfo['@default_currency'];?></td>
</tr>
<tr>
    <td class="label">Hierarchy: </td><td><?php print $this->activityInfo['@hierarchy'];?></td>
</tr>
<tr>
    <td class="label">Last Updated Date Time: </td><td><?php print $this->activityInfo['@last_updated_datetime'];?></td>
</tr>

<tr>
    <td>

    </td>
</tr>
</table>

</div>
</div>
<!-- Transaction Starts -->
<?php
$transactions=$activity->getElementsByType(Iati_Activity_Element::TYPE_TRANSACTION);
$value = $transactions[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>Transaction</legend>
<dl class='element-values'>
<?php foreach($transactions as $transaction):?>
<dt class='element-value element-value-1'>Ref</dt><dd> <?php print ($transaction->getAttrib('@ref'));?></dd><div class="clear"></div>

<?php
    $dbLayer = new Iati_WEP_DbLayer();
    $oTransaction = $dbLayer->getRowSet('Transaction', 'id', $transaction->getAttrib('id'), true, true);
?>
    <div class="sub_element">
        <!-- TransactionType Starts -->
        <?php
        $transactiontypes=$oTransaction->getElementsByType('TransactionType');
        $value = $transactiontypes[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>TransactionType</legend>
        <dl class='element-values'>
        <?php foreach($transactiontypes as $transactiontype):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($transactiontype->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Code</dt><dd> <?php if($transactiontype->getAttrib('@code')) { print ($model_wep->fetchValueById('TransactionType',$transactiontype->getAttrib('@code'),null));}?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- TransactionType Ends -->
        
        
        <!-- ProviderOrg Starts -->
        <?php
        $providerorgs=$oTransaction->getElementsByType('ProviderOrg');
        $value = $providerorgs[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>ProviderOrg</legend>
        <dl class='element-values'>
        <?php foreach($providerorgs as $providerorg):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($providerorg->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Ref</dt><dd> <?php print ($providerorg->getAttrib('@ref'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Provider_activity_id</dt><dd> <?php print ($providerorg->getAttrib('@provider_activity_id'));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- ProviderOrg Ends -->
        
        
        <!-- ReceiverOrg Starts -->
        <?php
        $receiverorgs=$oTransaction->getElementsByType('ReceiverOrg');
        $value = $receiverorgs[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>ReceiverOrg</legend>
        <dl class='element-values'>
        <?php foreach($receiverorgs as $receiverorg):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($receiverorg->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Ref</dt><dd> <?php print ($receiverorg->getAttrib('@ref'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Receiver_activity_id</dt><dd> <?php print ($receiverorg->getAttrib('@receiver_activity_id'));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- ReceiverOrg Ends -->
        
        
        <!-- Value Starts -->
        <?php
        $values=$oTransaction->getElementsByType('Value');
        $value = $values[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>Value</legend>
        <dl class='element-values'>
        <?php foreach($values as $value):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($value->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Value_date</dt><dd> <?php print ($value->getAttrib('@value_date'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Currency</dt><dd> <?php print ($value->getAttrib('@currency'));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- Value Ends -->
        
        
        <!-- Description Starts -->
        <?php
        $descriptions=$oTransaction->getElementsByType('Description');
        $value = $descriptions[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>Description</legend>
        <dl class='element-values'>
        <?php foreach($descriptions as $description):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($description->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$description->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- Description Ends -->
        
        
        <!-- TransactionDate Starts -->
        <?php
        $transactiondates=$oTransaction->getElementsByType('TransactionDate');
        $value = $transactiondates[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>TransactionDate</legend>
        <dl class='element-values'>
        <?php foreach($transactiondates as $transactiondate):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($transactiondate->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Iso_date</dt><dd> <?php print ($transactiondate->getAttrib('@iso_date'));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- TransactionDate Ends -->
        
        
        <!-- FlowType Starts -->
        <?php
        $flowtypes=$oTransaction->getElementsByType('FlowType');
        $value = $flowtypes[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>FlowType</legend>
        <dl class='element-values'>
        <?php foreach($flowtypes as $flowtype):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($flowtype->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$flowtype->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Code</dt><dd> <?php if($flowtype->getAttrib('@code')){print ($model_wep->fetchValueById('FlowType',$flowtype->getAttrib('@code'),null));}?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- FlowType Ends -->
        
        
        <!-- FinanceType Starts -->
        <?php
        $financetypes=$oTransaction->getElementsByType('FinanceType');
        $value = $financetypes[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>FinanceType</legend>
        <dl class='element-values'>
        <?php foreach($financetypes as $financetype):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($financetype->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$financetype->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Code</dt><dd> <?php if($financetype->getAttrib('@code')){print ($model_wep->fetchValueById('FinanceType',$financetype->getAttrib('@code'),null));} ?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- FinanceType Ends -->
        
        
        <!-- AidType Starts -->
        <?php
        $aidtypes=$oTransaction->getElementsByType('AidType');
        $value = $aidtypes[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>AidType</legend>
        <dl class='element-values'>
        <?php foreach($aidtypes as $aidtype):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($aidtype->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$aidtype->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Code</dt><dd> <?php if($aidtype->getAttrib('@code')){print ($model_wep->fetchValueById('AidType',$aidtype->getAttrib('@code'),null));}?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- AidType Ends -->
        
        
        <!-- DisbursementChannel Starts -->
        <?php
        $disbursementchannels=$oTransaction->getElementsByType('DisbursementChannel');
        $value = $disbursementchannels[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>DisbursementChannel</legend>
        <dl class='element-values'>
        <?php foreach($disbursementchannels as $disbursementchannel):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($disbursementchannel->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Code</dt><dd> <?php if($disbursementchannel->getAttrib('@code')){print ($model_wep->fetchValueById('DisbursementChannel',$disbursementchannel->getAttrib('@code'),null));}?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- DisbursementChannel Ends -->
        
        
        <!-- TiedStatus Starts -->
        <?php
        $tiedstatuss=$oTransaction->getElementsByType('TiedStatus');
        $value = $tiedstatuss[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>TiedStatus</legend>
        <dl class='element-values'>
        <?php foreach($tiedstatuss as $tiedstatus):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($tiedstatus->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$tiedstatus->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Code</dt><dd> <?php if($tiedstatus->getAttrib('@code')){ print( $model_wep->fetchValueById('TiedStatus',$tiedstatus->getAttrib('@code'),null));}?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- TiedStatus Ends -->

        
    </div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- Transaction Ends -->


<!-- Conditions Starts -->
<?php
$conditionss=$activity->getElementsByType(Iati_Activity_Element::TYPE_CONDITIONS);
$value = $conditionss[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>Conditions</legend>
<dl class='element-values'>
<?php foreach($conditionss as $conditions):?>
<dt class='element-value element-value-1'>Attached</dt><dd> <?php print ($conditions->getAttrib('@attached'));?></dd><div class="clear"></div>
<?php
    $dbLayer = new Iati_WEP_DbLayer();
    $oConditions = $dbLayer->getRowSet('Conditions', 'id', $conditions->getAttrib('id'), true, true);
?>
    <div class="sub_element">
        <!-- Condition Starts -->
	<?php
	$conditions=$oConditions->getElementsByType('Condition');
	$value = $conditions[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>Condition</legend>
	<dl class='element-values'>
	<?php foreach($conditions as $condition):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($condition->getAttrib('text'));?></dd><div class="clear"></div>
	<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$condition->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
	<dt class='element-value element-value-3'>Type</dt><dd> <?php print ($condition->getAttrib('@type'));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- Condition Ends -->
    </div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- Conditions Ends -->


<!-- DocumentLink Starts -->
<?php
$documentlinks=$activity->getElementsByType(Iati_Activity_Element::TYPE_DOCUMENT_LINK);
$value = $documentlinks[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>DocumentLink</legend>
<dl class='element-values'>
<?php foreach($documentlinks as $documentlink):?>
<dt class='element-value element-value-1'>Url</dt><dd> <?php print ($documentlink->getAttrib('@url'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Url</dt><dd> <?php print ($documentlink->getAttrib('@format'));?></dd><div class="clear"></div>

<?php
    $dbLayer = new Iati_WEP_DbLayer();
    $oDocumentlink = $dbLayer->getRowSet('DocumentLink', 'id', $documentlink->getAttrib('id'), true, true);
?>
    <div class="sub_element">
    <!-- Category Starts -->
	<?php
	$categorys=$oDocumentlink->getElementsByType('Category');
	$value = $categorys[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>Category</legend>
	<dl class='element-values'>
	<?php foreach($categorys as $category):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($category->getAttrib('text'));?></dd><div class="clear"></div>
	<dt class='element-value element-value-2'>Code</dt><dd> <?php if($category->getAttrib('@code')){ print ($model_wep->fetchValueById('DocumentCategory',$category->getAttrib('@code'),null));}?></dd><div class="clear"></div>
	<dt class='element-value element-value-3'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$category->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- Category Ends -->


	<!-- Title Starts -->
	<?php
	$titles=$oDocumentlink->getElementsByType('Title');
	$value = $titles[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>Title</legend>
	<dl class='element-values'>
	<?php foreach($titles as $title):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($title->getAttrib('text'));?></dd><div class="clear"></div>
	<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$title->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- Title Ends -->
    </div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- DocumentLink Ends -->


<!-- Result Starts -->
<?php
$results=$activity->getElementsByType(Iati_Activity_Element::TYPE_RESULT);
$value = $results[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>Result</legend>
<dl class='element-values'>
<?php foreach($results as $result):?>
<dt class='element-value element-value-1'>Type</dt><dd> <?php print ($result->getAttrib('@type'));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- Result Ends -->


<!-- PlannedDisbursement Starts -->
<?php
$planneddisbursements=$activity->getElementsByType(Iati_Activity_Element::TYPE_PLANNED_DISBURSEMENT);
$value = $planneddisbursements[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>PlannedDisbursement</legend>
<dl class='element-values'>
<?php foreach($planneddisbursements as $planneddisbursement):?>
<dt class='element-value element-value-1'>Updated</dt><dd> <?php print ($planneddisbursement->getAttrib('@updated'));?></dd><div class="clear"></div>
<?php
    $dbLayer = new Iati_WEP_DbLayer();
    $oPlanneddisbursement = $dbLayer->getRowSet('PlannedDisbursement', 'id', $planneddisbursement->getAttrib('id'), true, true);
?>
    <div class="sub_element">
        <!-- PeriodEnd Starts -->
	<?php
	$periodends=$oPlanneddisbursement->getElementsByType('PeriodEnd');
	$value = $periodends[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>PeriodEnd</legend>
	<dl class='element-values'>
	<?php foreach($periodends as $periodend):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($periodend->getAttrib('text'));?></dd><div class="clear"></div>
	<dt class='element-value element-value-2'>Iso_date</dt><dd> <?php print ($periodend->getAttrib('@iso_date'));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- PeriodEnd Ends -->


	<!-- PeriodStart Starts -->
	<?php
	$periodstarts=$oPlanneddisbursement->getElementsByType('PeriodStart');
	$value = $periodstarts[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>PeriodStart</legend>
	<dl class='element-values'>
	<?php foreach($periodstarts as $periodstart):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($periodstart->getAttrib('text'));?></dd><div class="clear"></div>
	<dt class='element-value element-value-2'>Iso_date</dt><dd> <?php print ($periodstart->getAttrib('@iso_date'));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- PeriodStart Ends -->


	<!-- Value Starts -->
	<?php
	$values=$oPlanneddisbursement->getElementsByType('Value');
	$value = $values[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>Value</legend>
	<dl class='element-values'>
	<?php foreach($values as $value):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($value->getAttrib('text'));?></dd><div class="clear"></div>
	<dt class='element-value element-value-2'>Value_date</dt><dd> <?php print ($value->getAttrib('@value_date'));?></dd><div class="clear"></div>
	<dt class='element-value element-value-3'>Currency</dt><dd> <?php print ($value->getAttrib('@currency'));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- Value Ends -->


    </div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- PlannedDisbursement Ends -->


<!-- ContactInfo Starts -->
<?php
$contactinfos=$activity->getElementsByType(Iati_Activity_Element::TYPE_CONTACT_INFO);
$value = $contactinfos[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>ContactInfo</legend>
<dl class='element-values'>
<?php foreach($contactinfos as $contactinfo):?>
<?php
    $dbLayer = new Iati_WEP_DbLayer();
    $oContactinfo = $dbLayer->getRowSet('ContactInfo', 'id', $contactinfo->getAttrib('id'), true, true);
?>
    <div class="sub-element">
    <!-- Organisation Starts -->
	<?php
	$organisations=$oContactinfo->getElementsByType('Organisation');
	$value = $organisations[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>Organisation</legend>
	<dl class='element-values'>
	<?php foreach($organisations as $organisation):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($organisation->getAttrib('text'));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- Organisation Ends -->


	<!-- PersonName Starts -->
	<?php
	$personnames=$oContactinfo->getElementsByType('PersonName');
	$value = $personnames[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>PersonName</legend>
	<dl class='element-values'>
	<?php foreach($personnames as $personname):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($personname->getAttrib('text'));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- PersonName Ends -->


	<!-- Telephone Starts -->
	<?php
	$telephones=$oContactinfo->getElementsByType('Telephone');
	$value = $telephones[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>Telephone</legend>
	<dl class='element-values'>
	<?php foreach($telephones as $telephone):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($telephone->getAttrib('text'));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- Telephone Ends -->


	<!-- Email Starts -->
	<?php
	$emails=$oContactinfo->getElementsByType('Email');
	$value = $emails[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>Email</legend>
	<dl class='element-values'>
	<?php foreach($emails as $email):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($email->getAttrib('text'));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- Email Ends -->


	<!-- MailingAddress Starts -->
	<?php
	$mailingaddresss=$oContactinfo->getElementsByType('MailingAddress');
	$value = $mailingaddresss[0]->getAttribs();
	if(!empty($value)): ?>
	<fieldset class='element-item'><legend class='element-title'>MailingAddress</legend>
	<dl class='element-values'>
	<?php foreach($mailingaddresss as $mailingaddress):?>
	<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($mailingaddress->getAttrib('text'));?></dd><div class="clear"></div>
	<?php endforeach;?>
	</dl>
	</fieldset>
	<?php endif;?>
	<!-- MailingAddress Ends -->
    </div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- ContactInfo Ends -->


<!-- ReportingOrg Starts -->
<?php
$reportingorgs=$activity->getElementsByType(Iati_Activity_Element::TYPE_REPORTING_ORG);
$value = $reportingorgs[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>ReportingOrg</legend>
<dl class='element-values'>
<?php foreach($reportingorgs as $reportingorg):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($reportingorg->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$reportingorg->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Ref</dt><dd> <?php print ($reportingorg->getAttrib('@ref'));?></dd><div class="clear"></div>
<dt class='element-value element-value-4'>Type</dt><dd> <?php print ($reportingorg->getAttrib('@type'));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- ReportingOrg Ends -->


<!-- Identifier Starts -->
<?php
$identifiers=$activity->getElementsByType(Iati_Activity_Element::TYPE_IDENTIFIER);
$value = $identifiers[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>Identifier</legend>
<dl class='element-values'>
<?php foreach($identifiers as $identifier):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($identifier->getAttrib('text'));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- Identifier Ends -->


<!-- OtherIdentifier Starts -->
<?php
$otheridentifiers=$activity->getElementsByType(Iati_Activity_Element::TYPE_OTHER_ACTIVITY_IDENTIFIER);
$value = $otheridentifiers[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>OtherIdentifier</legend>
<dl class='element-values'>
<?php foreach($otheridentifiers as $otheridentifier):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($otheridentifier->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Owner_ref</dt><dd> <?php print ($otheridentifier->getAttrib('@owner_ref'));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Owner_name</dt><dd> <?php print ($otheridentifier->getAttrib('@owner_name'));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- OtherIdentifier Ends -->


<!-- Title Starts -->
<?php
$titles=$activity->getElementsByType(Iati_Activity_Element::TYPE_TITLE);
$value = $titles[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>Title</legend>
<dl class='element-values'>
<?php foreach($titles as $title):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($title->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$title->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- Title Ends -->


<!-- Description Starts -->
<?php
$descriptions=$activity->getElementsByType(Iati_Activity_Element::TYPE_DESCRIPTION);
$value = $descriptions[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>Description</legend>
<dl class='element-values'>
<?php foreach($descriptions as $description):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($description->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$description->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- Description Ends -->


<!-- ActivityStatus Starts -->
<?php
$activitystatuss=$activity->getElementsByType(Iati_Activity_Element::TYPE_ACTIVITY_STATUS);
$value = $activitystatuss[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>ActivityStatus</legend>
<dl class='element-values'>
<?php foreach($activitystatuss as $activitystatus):?>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- ActivityStatus Ends -->


<!-- ActivityDate Starts -->
<?php
$activitydates=$activity->getElementsByType(Iati_Activity_Element::TYPE_ACTIVITY_DATE);
$value = $activitydates[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>ActivityDate</legend>
<dl class='element-values'>
<?php foreach($activitydates as $activitydate):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($activitydate->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Type</dt><dd> <?php print ($activitydate->getAttrib('@type'));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Iso_date</dt><dd> <?php print ($activitydate->getAttrib('@iso_date'));?></dd><div class="clear"></div>
<dt class='element-value element-value-4'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$activitydate->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- ActivityDate Ends -->


<!-- ParticipatingOrg Starts -->
<?php
$participatingorgs=$activity->getElementsByType(Iati_Activity_Element::TYPE_PARTICIPATING_ORG);
$value = $participatingorgs[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>ParticipatingOrg</legend>
<dl class='element-values'>
<?php foreach($participatingorgs as $participatingorg):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($participatingorg->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$participatingorg->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Ref</dt><dd> <?php print ($participatingorg->getAttrib('@ref'));?></dd><div class="clear"></div>
<dt class='element-value element-value-4'>Type</dt><dd> <?php print ($participatingorg->getAttrib('@type'));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- ParticipatingOrg Ends -->


<!-- RecipientCountry Starts -->
<?php
$recipientcountrys=$activity->getElementsByType(Iati_Activity_Element::TYPE_RECIPIENT_COUNTRY);
$value = $recipientcountrys[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>RecipientCountry</legend>
<dl class='element-values'>
<?php foreach($recipientcountrys as $recipientcountry):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($recipientcountry->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$recipientcountry->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Percentage</dt><dd> <?php print ($recipientcountry->getAttrib('@percentage'));?></dd><div class="clear"></div>
<dt class='element-value element-value-4'>Code</dt><dd> <?php if($recipientcountry->getAttrib('@code')){print ($model_wep->fetchValueById('Country',$recipientcountry->getAttrib('@code'),null));}?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- RecipientCountry Ends -->


<!-- RecipientRegion Starts -->
<?php
$recipientregions=$activity->getElementsByType(Iati_Activity_Element::TYPE_RECIPIENT_REGION);
$value = $recipientregions[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>RecipientRegion</legend>
<dl class='element-values'>
<?php foreach($recipientregions as $recipientregion):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($recipientregion->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$recipientregion->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Percentage</dt><dd> <?php print ($recipientregion->getAttrib('@percentage'));?></dd><div class="clear"></div>
<dt class='element-value element-value-4'>Code</dt><dd> <?php if($recipientregion->getAttrib('@code')){print ($model_wep->fetchValueById('Region',$recipientregion->getAttrib('@code'),null));}?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- RecipientRegion Ends -->


<!-- Location Starts -->
<?php
$locations=$activity->getElementsByType(Iati_Activity_Element::TYPE_LOCATION);
$value = $locations[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>Location</legend>
<dl class='element-values'>
<?php foreach($locations as $location):?>
<dt class='element-value element-value-2'>Percentage</dt><dd> <?php print ($location->getAttrib('@percentage'));?></dd><div class="clear"></div>
<?php
    $dbLayer = new Iati_WEP_DbLayer();
    $olocation = $dbLayer->getRowSet('Location', 'id', $location->getAttrib('id'), true, true);
?>
    <div class="sub-element">    
        <!-- LocationType Starts -->
        <?php
        $locationtypes=$olocation->getElementsByType('LocationType');
        $value = $locationtypes[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>LocationType</legend>
        <dl class='element-values'>
        <?php foreach($locationtypes as $locationtype):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($locationtype->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$locationtype->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Code</dt><dd> <?php if($locationtype->getAttrib('@code')){ print ($model_wep->fetchValueById('LocationType',$locationtype->getAttrib('@code'),null));};?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- LocationType Ends -->
        
        <!-- Name Starts -->
        <?php
        $names=$olocation->getElementsByType('Name');
        $value = $names[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>Name</legend>
        <dl class='element-values'>
        <?php foreach($names as $name):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($name->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$name->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- Name Ends -->
        
        <!-- Description Starts -->
        <?php
        $descriptions=$olocation->getElementsByType('Description');
        $value = $descriptions[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>Description</legend>
        <dl class='element-values'>
        <?php foreach($descriptions as $description):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($description->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$description->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- Description Ends -->
        
        
        <!-- Administrative Starts -->
        <?php
        $administratives=$olocation->getElementsByType('Administrative');
        $value = $administratives[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>Administrative</legend>
        <dl class='element-values'>
        <?php foreach($administratives as $administrative):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($administrative->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Adm 1</dt><dd> <?php print ($administrative->getAttrib('@adm1'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Adm 2</dt><dd> <?php print ($administrative->getAttrib('@adm2'));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- Administrative Ends -->
        
        <!-- Coordinates Starts -->
        <?php
        $coordinatess=$olocation->getElementsByType('Coordinates');
        $value = $coordinatess[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>Coordinates</legend>
        <dl class='element-values'>
        <?php foreach($coordinatess as $coordinates):?>
        <dt class='element-value element-value-1'>Latitude</dt><dd> <?php print ($coordinates->getAttrib('@latitude'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Longitude</dt><dd> <?php print ($coordinates->getAttrib('@longitude'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-3'>Precision</dt><dd> <?php print ($coordinates->getAttrib('@precision'));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- Coordinates Ends -->
        
        
        <!-- GazetteerEntry Starts -->
        <?php
        $gazetteerentrys=$olocation->getElementsByType('GazetteerEntry');
        $value = $gazetteerentrys[0]->getAttribs();
        if(!empty($value)): ?>
        <fieldset class='element-item'><legend class='element-title'>GazetteerEntry</legend>
        <dl class='element-values'>
        <?php foreach($gazetteerentrys as $gazetteerentry):?>
        <dt class='element-value element-value-1'>Text</dt><dd> <?php print ($gazetteerentry->getAttrib('text'));?></dd><div class="clear"></div>
        <dt class='element-value element-value-2'>Gazetteer_ref</dt><dd> <?php print ($gazetteerentry->getAttrib('@gazetteer_ref'));?></dd><div class="clear"></div>
        <?php endforeach;?>
        </dl>
        </fieldset>
        <?php endif;?>
        <!-- GazetteerEntry Ends -->
    </div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- Location Ends -->


<!-- Sector Starts -->
<?php
$sectors=$activity->getElementsByType(Iati_Activity_Element::TYPE_SECTOR);
$value = $sectors[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>Sector</legend>
<dl class='element-values'>
<?php foreach($sectors as $sector):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($sector->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$sector->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Vocabulary</dt><dd> <?php print ($sector->getAttrib('@vocabulary'));?></dd><div class="clear"></div>
<dt class='element-value element-value-4'>Code</dt><dd> <?php if($sector->getAttrib('@code')){ print ($model_wep->fetchValueById('',$sector->getAttrib('@code'),null));}?></dd><div class="clear"></div>
<dt class='element-value element-value-5'>Percentage</dt><dd> <?php print ($sector->getAttrib('@percentage'));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- Sector Ends -->


<!-- PolicyMarker Starts -->
<?php
$policymarkers=$activity->getElementsByType(Iati_Activity_Element::TYPE_POLICY_MARKER);
$value = $policymarkers[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>PolicyMarker</legend>
<dl class='element-values'>
<?php foreach($policymarkers as $policymarker):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($policymarker->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$policymarker->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Significance</dt><dd> <?php print ($policymarker->getAttrib('@significance'));?></dd><div class="clear"></div>
<dt class='element-value element-value-4'>Code</dt><dd> <?php if($policymarker->getAttrib('@code')){ print ($model_wep->fetchValueById('PolicyMarker',$policymarker->getAttrib('@code'),null));}?></dd><div class="clear"></div>
<dt class='element-value element-value-5'>Vocabulary</dt><dd> <?php print ($policymarker->getAttrib('@vocabulary'));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- PolicyMarker Ends -->


<!-- CollaborationType Starts -->
<?php
$collaborationtypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_COLLABORATION_TYPE);
$value = $collaborationtypes[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>CollaborationType</legend>
<dl class='element-values'>
<?php foreach($collaborationtypes as $collaborationtype):?>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- CollaborationType Ends -->


<!-- DefaultFlowType Starts -->
<?php
$defaultflowtypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_FLOW_TYPE);
$value = $defaultflowtypes[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>DefaultFlowType</legend>
<dl class='element-values'>
<?php foreach($defaultflowtypes as $defaultflowtype):?>
<dt class='element-value element-value-1'>Code</dt><dd> <?php if($defaultflowtype->getAttrib('type')){print ($model_wep->fetchValueById('FlowType',$defaultflowtype->getAttrib('@code'),null));}?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Text</dt><dd> <?php print ($defaultflowtype->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$defaultflowtype->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- DefaultFlowType Ends -->


<!-- DefaultFinanceType Starts -->
<?php
$defaultfinancetypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_FINANCE_TYPE);
$value = $defaultfinancetypes[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>DefaultFinanceType</legend>
<dl class='element-values'>
<?php foreach($defaultfinancetypes as $defaultfinancetype):?>
<dt class='element-value element-value-1'>Code</dt><dd> <?php print ($model_wep->fetchValueById('FinanceType',$defaultfinancetype->getAttrib('@code'),null));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Text</dt><dd> <?php print ($defaultfinancetype->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$defaultfinancetype->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- DefaultFinanceType Ends -->


<!-- DefaultAidType Starts -->
<?php
$defaultaidtypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_AID_TYPE);
$value = $defaultaidtypes[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>DefaultAidType</legend>
<dl class='element-values'>
<?php foreach($defaultaidtypes as $defaultaidtype):?>
<dt class='element-value element-value-1'>Code</dt><dd> <?php print ($model_wep->fetchValueById('AidType',$defaultaidtype->getAttrib('@code'),null));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Text</dt><dd> <?php print ($defaultaidtype->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$defaultaidtype->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- DefaultAidType Ends -->


<!-- DefaultTiedStatus Starts -->
<?php
$defaulttiedstatuss=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_TIED_STATUS);
$value = $defaulttiedstatuss[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>DefaultTiedStatus</legend>
<dl class='element-values'>
<?php foreach($defaulttiedstatuss as $defaulttiedstatus):?>
<dt class='element-value element-value-1'>Code</dt><dd> <?php if($defaulttiedstatus->getAttrib('@code')){print ($model_wep->fetchValueById('TiedStatus',$defaulttiedstatus->getAttrib('@code'),null));}?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Text</dt><dd> <?php print ($defaulttiedstatus->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$defaulttiedstatus->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- DefaultTiedStatus Ends -->


<!-- ActivityWebsite Starts -->
<?php
$activitywebsites=$activity->getElementsByType(Iati_Activity_Element::TYPE_ACTIVITY_WEBSITE);
$value = $activitywebsites[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>ActivityWebsite</legend>
<dl class='element-values'>
<?php foreach($activitywebsites as $activitywebsite):?>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- ActivityWebsite Ends -->


<!-- RelatedActivity Starts -->
<?php
$relatedactivitys=$activity->getElementsByType(Iati_Activity_Element::TYPE_RELATED_ACTIVITY);
$value = $relatedactivitys[0]->getAttribs();
if(!empty($value)): ?>
<fieldset class='element-item'><legend class='element-title'>RelatedActivity</legend>
<dl class='element-values'>
<?php foreach($relatedactivitys as $relatedactivity):?>
<dt class='element-value element-value-1'>Text</dt><dd> <?php print ($relatedactivity->getAttrib('text'));?></dd><div class="clear"></div>
<dt class='element-value element-value-2'>Xml_lang</dt><dd> <?php print ($model_wep->fetchValueById('Language',$relatedactivity->getAttrib('@xml_lang'),null));?></dd><div class="clear"></div>
<dt class='element-value element-value-3'>Ref</dt><dd> <?php print ($relatedactivity->getAttrib('@ref'));?></dd><div class="clear"></div>
<dt class='element-value element-value-4'>Code</dt><dd> <?php if($relatedactivity->getAttrib('@code')){print ($model_wep->fetchValueById('RelatedActivityType',$relatedactivity->getAttrib('@code'),null));}?></dd><div class="clear"></div>
<?php endforeach;?>
</dl>
</fieldset>
<?php endif;?>
<!-- RelatedActivity Ends -->

    </td>
</tr>
</table>