<?php 
    $activity = $this->activity;
    $activity_id = $activity->getAttrib('id');
    $change_status_form = $this->status_form;
    $model_wep = new Model_Wep();
?>

<div class= "activity-state">
    <?php if($userPermission && $permission == '1'):?>
    <span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            . $this->activityInfo['id'])?></span>

<?php endif; ?>
<?php if(!$userPermission): ?>
<span class = "override-link"><?php echo $this->l('Override Activity Default', 'wep/edit-activity/?activity_id='
                                                            . $this->activityInfo['id'])?></span>

<?php endif; ?>
</div>
<?php
    $title = "(" ;
    $title .= ($this->activityInfo['iati_title'])?$this->activityInfo['iati_title']:'No Title' ;
    $title .= ")";
?>

<div class="activity-title">
    <span class="activity_identifier"> <?php print $this->activityInfo['activity_identifier']; ?> </span>
    <span class="activity_title"> <?php print $title;?> </span>
</div>
<div class= "activity-state">
    <div class="state-display">
        <ul class='state-<?php echo $this->state;?>'>
            <li class='label'>Activity State</li>
            <?php foreach(Iati_WEP_ActivityState::getStatus() as $state_value => $state_name):?>
                <li <?php if($this->state == $state_value) {print "id='current-state'";}?> ><span class='<?php print (!in_array($state_value,Iati_WEP_ActivityState::getRemainingStates($this->state)))?'visited-state':'not-visited-state'; ?>'><?php print $state_name ?></span></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class='change-state'>
        <div class="change-state-info-section">This activity is in <span class="change-state-current-state"><?php print(Iati_WEP_ActivityState::getStatus($this->state));?></span> State. <?php if($this->state != Iati_WEP_ActivityState::STATUS_PUBLISHED): ?>Mark it as <?php print($change_status_form)?><?php endif; ?></div>
        <div class="change-state-help-section"><span class="change-state-help"><a href="#">what's this?</a></span></div>
    </div>
</div>

<div class="activity-container">

<?php echo $this->partial("partials/view-activity/activity-default.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                            )
                          );
?>


<!-- ReportingOrg Starts -->
<?php
$reportingorgs=$activity->getElementsByType(Iati_Activity_Element::TYPE_REPORTING_ORG);
$value = $reportingorgs[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/reporting-org.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,  
                                                                                'reportingorgs' => $reportingorgs ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- ReportingOrg Ends -->


<!-- Identifier Starts -->
<?php
$identifiers=$activity->getElementsByType(Iati_Activity_Element::TYPE_IDENTIFIER);
$value = $identifiers[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/identifier.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'identifiers' => $identifiers ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- Identifier Ends -->


<!-- OtherIdentifier Starts -->
<?php
$otheridentifiers=$activity->getElementsByType(Iati_Activity_Element::TYPE_OTHER_ACTIVITY_IDENTIFIER);
$value = $otheridentifiers[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/other-identifier.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'otheridentifiers' => $otheridentifiers ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- OtherIdentifier Ends -->


<!-- Title Starts -->
<?php
$titles=$activity->getElementsByType(Iati_Activity_Element::TYPE_TITLE);
$value = $titles[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/title.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'titles' => $titles ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- Title Ends -->


<!-- Description Starts -->
<?php
$descriptions=$activity->getElementsByType(Iati_Activity_Element::TYPE_DESCRIPTION);
$value = $descriptions[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/description.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'descriptions' => $descriptions ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- Description Ends -->


<!-- ActivityStatus Starts -->
<?php
$activitystatuss=$activity->getElementsByType(Iati_Activity_Element::TYPE_ACTIVITY_STATUS);
$value = $activitystatuss[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/activity-status.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'activitystatuss' => $activitystatuss ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- ActivityStatus Ends -->


<!-- ActivityDate Starts -->
<?php
$activitydates=$activity->getElementsByType(Iati_Activity_Element::TYPE_ACTIVITY_DATE);
$value = $activitydates[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/activity-date.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'activitydates' => $activitydates ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- ActivityDate Ends -->


<!-- ContactInfo Starts -->
<?php
$contactinfos=$activity->getElementsByType(Iati_Activity_Element::TYPE_CONTACT_INFO);
$value = $contactinfos[0]->getAttribs();
if(!empty($value)): ?>
   <?php echo $this->partial("partials/view-activity/contact-info.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'contactinfos' => $contactinfos ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- ContactInfo Ends -->


<!-- ParticipatingOrg Starts -->
<?php
$participatingorgs=$activity->getElementsByType(Iati_Activity_Element::TYPE_PARTICIPATING_ORG);
$value = $participatingorgs[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/participating-org.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'participatingorgs' => $participatingorgs ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- ParticipatingOrg Ends -->



<!-- RecipientCountry Starts -->
<?php
$recipientcountrys=$activity->getElementsByType(Iati_Activity_Element::TYPE_RECIPIENT_COUNTRY);
$value = $recipientcountrys[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/recipient-country.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'recipientcountrys' => $recipientcountrys ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- RecipientCountry Ends -->


<!-- RecipientRegion Starts -->
<?php
$recipientregions=$activity->getElementsByType(Iati_Activity_Element::TYPE_RECIPIENT_REGION);
$value = $recipientregions[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/recipient-region.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'recipientregions' => $recipientregions ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- RecipientRegion Ends -->


<!-- Location Starts -->
<?php
$locations=$activity->getElementsByType(Iati_Activity_Element::TYPE_LOCATION);
$value = $locations[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/location.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'locations' => $locations ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- Location Ends -->


<!-- Sector Starts -->
<?php
$sectors=$activity->getElementsByType(Iati_Activity_Element::TYPE_SECTOR);
$value = $sectors[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/sector.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'sectors' => $sectors ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- Sector Ends -->


<!-- PolicyMarker Starts -->
<?php
$policymarkers=$activity->getElementsByType(Iati_Activity_Element::TYPE_POLICY_MARKER);
$value = $policymarkers[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/policy-marker.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'policymarkers' => $policymarkers ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- PolicyMarker Ends -->


<!-- CollaborationType Starts -->
<?php
$collaborationtypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_COLLABORATION_TYPE);
$value = $collaborationtypes[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/collaboration-type.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'collaborationtypes' => $collaborationtypes ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- CollaborationType Ends -->


<!-- DefaultFlowType Starts -->
<?php
$defaultflowtypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_FLOW_TYPE);
$value = $defaultflowtypes[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/defaultFlow-type.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'defaultflowtypes' => $defaultflowtypes ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- DefaultFlowType Ends -->


<!-- DefaultFinanceType Starts -->
<?php
$defaultfinancetypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_FINANCE_TYPE);
$value = $defaultfinancetypes[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/defaultFinance-type.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'defaultfinancetypes' => $defaultfinancetypes ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- DefaultFinanceType Ends -->


<!-- DefaultAidType Starts -->
<?php
$defaultaidtypes=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_AID_TYPE);
$value = $defaultaidtypes[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/defaultAid-type.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'defaultaidtypes' => $defaultaidtypes ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- DefaultAidType Ends -->


<!-- DefaultTiedStatus Starts -->
<?php
$defaulttiedstatuss=$activity->getElementsByType(Iati_Activity_Element::TYPE_DEFAULT_TIED_STATUS);
$value = $defaulttiedstatuss[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/defaultTiedStatus.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'defaulttiedstatuss' => $defaulttiedstatuss ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- DefaultTiedStatus Ends -->


<!-- Budget Starts -->
<?php
$budgets=$activity->getElementsByType(Iati_Activity_Element::TYPE_BUDGET);
$value = $budgets[0]->getAttribs();
if(!empty($value)): ?>   
    <?php echo $this->partial("partials/view-activity/budget.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'budgets' => $budgets ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- Budget Ends -->



<!-- PlannedDisbursement Starts -->
<?php
$planneddisbursements=$activity->getElementsByType(Iati_Activity_Element::TYPE_PLANNED_DISBURSEMENT);
$value = $planneddisbursements[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/plannedDisbursements.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'planneddisbursements' => $planneddisbursements ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- PlannedDisbursement Ends -->


<!-- Transaction Starts -->
<?php
$transactions=$activity->getElementsByType(Iati_Activity_Element::TYPE_TRANSACTION);
$value = $transactions[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/transactions.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'transactions' => $transactions ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- Transaction Ends -->


<!-- DocumentLink Starts -->
<?php
$documentlinks=$activity->getElementsByType(Iati_Activity_Element::TYPE_DOCUMENT_LINK);
$value = $documentlinks[0]->getAttribs();
if(!empty($value)): ?>
     <?php echo $this->partial("partials/view-activity/documentLink.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'documentlinks' => $documentlinks ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- DocumentLink Ends -->


<!-- ActivityWebsite Starts -->
<?php
$activitywebsites=$activity->getElementsByType(Iati_Activity_Element::TYPE_ACTIVITY_WEBSITE);
$value = $activitywebsites[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/activityWebsite.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'activitywebsites' => $activitywebsites ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- ActivityWebsite Ends -->


<!-- RelatedActivity Starts -->
<?php
$relatedactivitys=$activity->getElementsByType(Iati_Activity_Element::TYPE_RELATED_ACTIVITY);
$value = $relatedactivitys[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/relatedActivity.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'relatedactivitys' => $relatedactivitys ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- RelatedActivity Ends -->


<!-- Conditions Starts -->
<?php
$conditionss=$activity->getElementsByType(Iati_Activity_Element::TYPE_CONDITIONS);
$value = $conditionss[0]->getAttribs();
if(!empty($value)): ?>
    <?php echo $this->partial("partials/view-activity/conditions.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'conditionss' => $conditionss ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- Conditions Ends -->


<!-- Result Starts -->
<?php
$results=$activity->getElementsByType(Iati_Activity_Element::TYPE_RESULT);
$value = $results[0]->getAttribs();
if(!empty($value)): ?>
     <?php echo $this->partial("partials/view-activity/result.phtml" , array(
                                                                                'activityInfo' => $this->activityInfo ,
                                                                                'results' => $results ,
                                                                            )
                          );
    ?>
<?php endif;?>
<!-- Result Ends -->

</div>