<div class="footer-container">
	<div class="footer">
		<span class="query">Got any queries?</span>
		<span class="query">Wish for new features?</span>
		<span class="query">Want to blog on AidStream?</span>
		<span class="email">Shoot an email at <a href="mailto:support@aidstream.org">support@aidstream.org</a></span>
		<span class="fork">Fork us on <a href="https://github.com/younginnovations/aidstream" target="_blank">GitHub</a></span>
		</p>
	</div>
</div>