<!--Starts Title block-->
<div class="activity-title">
    
    <!--Display title-->
    <div class="element-edit-activity-info-wrapper">
        <span class="activity_title"> <?php print $this->title;?> </span>
    </div>
    
    <!--Display link for view elements of an organisation-->
    <span class="viewer-link"><?php echo $this->l('View Elements', 'organisation/view-elements/parentId/'. $this->parentId)?></span>
    
    <div class="clear"></div>
    
</div>
<!--Ends Title block-->

<!--Extracting Display Name of an Element-->
<?php
    $url = Zend_Controller_Front::getInstance()->getRequest()->getParams();
    $classNameArray = split("_",$url['className']);
    $elementClass = "Iati_Aidstream_Element_Organisation_".$classNameArray[1];
    $elementClassObj = new $elementClass;
    $elementDisplayName = $elementClassObj->getDisplayName();
?>

<!--Show which element is adding-->
<div class="second-title">Editing <span><?php print $elementDisplayName ?>...</span></div>

<!--Display Form-->
<?php print $this->form; ?>