<!--Starts Title block-->
<div class="activity-title">
    
    <!--Display title-->
    <div class="element-edit-activity-info-wrapper">
        <span class="activity_title"> <?php print $this->title;?> </span>
    </div>
    
    <!--Display link for view elements of an organisation-->
    <span class="viewer-link"><?php echo $this->l('View Organisation Data', "organisation/view-elements/?parentId=$this->parentId"); ?></span>
    
    <div class="clear"></div>
    
</div>
<!--Ends Title block-->

<!--Show which element is editing-->
<div class="second-title">Editing <span><?php print $this->displayName ?>...</span></div>

<!--Display Form-->
<?php print $this->form; ?>