INSERT INTO  `Sector` (
`id` ,
`Code` ,
`Name` ,
`Description` ,
`CategoryCode` ,
`lang_id`
)
VALUES (NULL,'14021','Water supply - large systems','Potable water treatment plants; intake works; storage; water supply pumping stations; large scale transmission / conveyance and distribution systems.','140','1'),
        (NULL,'14022','Sanitation - large systems','Large scale sewerage including trunk sewers and sewage pumping stations; domestic and industrial waste water treatment plants.','140','1'),
        (NULL,'14031','Basic drinking water supply','Rural water supply schemes using handpumps, spring catchments, gravity-fed systems, rainwater collection and fog harvesting, storage tanks, small distribution systems typically with shared connections/points of use. Urban schemes using handpumps and local neighbourhood networks including those with shared connections.','140','1'),
        (NULL,'14032','Basic sanitation','Latrines, on-site disposal and alternative sanitation systems, including the promotion of household and community investments in the construction of these facilities. (Use code 12261 for activities promoting improved personal hygiene practices.)','140','1'),
        (NULL,'15111','Public finance management','Fiscal policy and planning; support to ministries of finance; strengthening financial and managerial accountability; public expenditure management; improving financial management systems; tax policy and administration; budget drafting; inter-governmental fiscal relations, public audit, public debt. (Use code 15114 for revenue-generating tax support and code 33120 for customs).','151','1'),
        (NULL,'15112','Decentralisation and support to subnational government','Decentralisation processes (including political, administrative and fiscal dimensions); intergovernmental relations and federalism; strengthening departments of regional and local government, regional and local authorities and their national associations. (Use specific sector codes for decentralisation of sector management and services.)','151','1'),
        (NULL,'15113','Anti-corruption organisations and institutions','Specialised organisations, institutions and frameworks for the prevention of and combat against corruption, bribery, money-laundering and other aspects of organised crime, with or without law enforcement powers, e.g. anti-corruption commissions and monitoring bodies, special investigation services, institutions and initiatives of integrity and ethics oversight, specialised NGOs, other civil society and citizens’ organisations directly concerned with corruption.','151','1'),
        (NULL,'15114','Tax policy and tax administration support','Support to the ministries of finance, revenue authorities or other local, regional or national public bodies on tax policy, analysis and administration (including “non-tax” public revenue).','151','1'),
        (NULL,'15151','Elections','	Electoral management bodies and processes, election observation, voters’ education. (Use code 15230 when in the context of an international peacekeeping operation.)','151','1'),
        (NULL,'15152','Legislatures and political parties','Assistance to strengthen key functions of legislatures/ parliaments including subnational assemblies and councils (representation; oversight; legislation), such as improving the capacity of legislative bodies, improving legislatures’ committees and administrative procedures,; research and information management systems; providing training programmes for legislators and support personnel. Assistance to political parties and strengthening of party systems.','151','1'),
        (NULL,'15153','Media and free flow of information','Activities that support free and uncensored flow of information on public issues; activities that increase the editorial and technical skills and the integrity of the print and broadcast media, e.g. training of journalists. (Use codes 22010-22040 for provision of equipment and capital assistance to media.)','151','1'),
        (NULL,'15160','Human rights','Measures to support specialised official human rights institutions and mechanisms at universal, regional, national and local levels in their statutory roles to promote and protect civil and political, economic, social and cultural rights as defined in international conventions and covenants; translation of international human rights commitments into national legislation; reporting and follow-up; human rights dialogue. Human rights defenders and human rights NGOs; human rights advocacy, activism, mobilisation; awareness raising and public human rights education. Human rights programming targeting specific groups, e.g. children, persons with disabilities, migrants, ethnic, religious, linguistic and sexual minorities, indigenous people and those suffering from caste discrimination, victims of trafficking, victims of torture. (Use code 15230 when in the context of a peacekeeping operation)','151','1'),
        (NULL,'15170','Women’s equality organisations and institutions','Support for institutions and organisations (governmental and non-governmental) working for gender equality and women’s empowerment.','151','1');