<?php include('session.php');?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title>AidStream</title>
  <link rel="stylesheet" href="markdown.css" type="text/css" />
</head>
<body>
<?php include('header.php');?>
<div class="toc-wrapper">
<div id="TOC">
<ul>
<li><a href="#registration">Registration</a></li>
<li><a href="#data-entry">Data Entry</a><ul>
<li><a href="#dashboard">Dashboard</a></li>
<li><a href="#change-defaults">Settings</a><ul>
<li><a href="#change-defaults---reporting-organisation">Settings - Reporting Organisation</a><ul>
<li><a href="#change-defaults---reporting-organisation-identifier">Settings - Reporting Organisation Identifier</a></li>
<li><a href="#change-defaults---reporting-organisation-type">Settings - Reporting Organisation Type</a></li>
</ul></li>
<li><a href="#change-defaults---publishing-type">Settings - Publishing Type</a></li>
<li><a href="#change-defaults---registry-info">Settings - Registry Info</a><ul>
<li><a href="#change-defaults---registry-info---publisher-id">Settings - Registry Info - Publisher Id</a></li>
<li><a href="#change-defaults---registry-info---api-key">Settings - Registry Info - API Key</a></li>
</ul></li>
<li><a href="#change-defaults---default-field-values">Settings - Default Field Values</a></li>
</ul></li>
<li><a href="#list-users">List Users</a></li>
<li><a href="#add-new-activity">Add new activity</a></li>
<li><a href="#simplified-aidstream-activity-states">Simplified Aidstream Activity States</a></li>
</ul></li>
<li><a href="#publishing-of-activities">Publishing of Activities</a><ul>
<li><a href="#registering-with-iati-registry">Registering with IATI Registry</a></li>
</ul></li>
</ul>
</div>
<h2 id="registration"><a href="#TOC">Registration</a></h2>
<p>Register at <a href="http://www.aidstream.org/user/user/register">www.aidstream.org</a>. However, you would have to additionally inform us at info@aidstream.org to have a simplified AidStream account.</p>
<p>Please contact us with the following details at info@aidstream.org:</p>
<ul>
<li>Organisation Info
<ul>
<li>Name of Organisation</li>
<li>Organisation Address</li>
<li>Account Identifier
<ul>
<li>A short abbreviation that uniquely identifies your organisation in Simplified AidStream e.g. if you organisation is AidInfo, suggested account identifier is ai All the users in Simplified AidStream will have Account Identifier as prefix, so that the usernames follow the standards]</li>
</ul></li>
</ul></li>
<li>User info
<ul>
<li>Name</li>
<li>Email
<ul>
<li>For newly registered user, the user identifier will be admin, and the username will be ai_admin</li>
</ul></li>
</ul></li>
</ul>
<h2 id="data-entry"><a href="#TOC">Data Entry</a></h2>
<h3 id="dashboard"><a href="#TOC">Dashboard</a></h3>
<p>Dashboard gives the overview of the activities.</p>
<div class="figure">
<img src="img/dashboard.png" title="Dashboard" /><p class="caption"></p>
</div>
<h3 id="change-defaults"><a href="#TOC">Settings</a></h3>
<p><strong>Settings</strong> allows to update defaults IATI values, organisation related information. The followings are covered in this section.</p>
<ul>
<li>Reporting Organisation Info</li>
<li>Publishing Type</li>
<li>Registry Info</li>
<li>Default Field Values</li>
</ul>
<h4 id="change-defaults---reporting-organisation"><a href="#TOC">Settings - Reporting Organisation</a></h4>
<p>The <strong>Reporting Organisation</strong> is a mandatory field which clearly identifies the organisation that is publishing the data. All activities recorded in an AidStream account must contain the same Reporting Organisation. The Reporting Organisation may report data on activities funded and/or implemented by different organisations.</p>
<p>As per IATI Standard, the following information is needed for the Reporting Organisation field.</p>
<ul>
<li>Reporting Organisation Identifier</li>
<li>Reporting Organisation Type</li>
<li>Reporting Organisation Name</li>
<li>Reporting Organisation Language - Optional</li>
</ul>
<div class="figure">
<img src="img/change.defaults-reporting.organisation.png" title="Reporting Organisation" /><p class="caption"></p>
</div>
<h5 id="change-defaults---reporting-organisation-identifier"><a href="#TOC">Settings - Reporting Organisation Identifier</a></h5>
<p>IATI requires each organisation to be referenced by a globally unique identifier. Some organisations may already have a code assigned to them in CRS. These codes can be found <a href="http://iatistandard.org/codelists/organisation">Organisation Codelist</a></p>
<p>However, many organisations will not have an existing code and one will need to be generated by the organisation for the purpose of IATI. This is done using a three-part key consisting of the followings</p>
<ul>
<li>Country
<ul>
<li>The country is the 3166-1 alpha-2 code for the country in which the registration agency is based. See <a href="http://iatistandard.org/codelists/country">Country Codelist</a> for the codes.</li>
</ul></li>
<li>Registration agency
<ul>
<li>The registration agency is a code for a recognised agency that registers organisations. Eg. in the UK,there are three registration agencies: Companies House, the Charities Commissioner, and Revenue &amp; Customs. Use their initials.</li>
</ul></li>
<li>Registration number
<ul>
<li>The registration number is the identifier issued by the relevant agency. Eg Oxfam-GB's identifier is GB-CHC-202918-LACA34 where GB-CHC refers to the UK Charity Commissioners)</li>
</ul></li>
</ul>
<h5 id="change-defaults---reporting-organisation-type"><a href="#TOC">Settings - Reporting Organisation Type</a></h5>
<p>The type of organisation that best describes the Reporting Organisation. As per <a href="http://iatistandard.org/codelists/organisation_type">Organisation Type Codelist</a>, choose one from the following that identifies your organisation.</p>
<ul>
<li>Government</li>
<li>Other Public Sector</li>
<li>International NGO</li>
<li>National NGO</li>
<li>Regional NGO</li>
<li>Public Private Partnership</li>
<li>Multilateral</li>
<li>Foundation</li>
<li>Private Sector</li>
<li>Academic, Training and Research</li>
</ul>
<h4 id="change-defaults---publishing-type"><a href="#TOC">Settings - Publishing Type</a></h4>
<p>Selecting unsegmented publishing type will publish all your activities into one file whereas segmented allows the files to be published country wise.</p>
<div class="figure">
<img src="img/change.defaults-publishing.type-segmented.png" title="Publishing Type" /><p class="caption"></p>
</div>
<h4 id="change-defaults---registry-info"><a href="#TOC">Settings - Registry Info</a></h4>
<p>Simplified AidStream will automatically register your published data on the IATI Registry. To do this it requires two pieces of information - Publisher Id and API Key.</p>
<div class="figure">
<img src="img/change.defaults-iatiregistry-no.png" title="Registry Info" /><p class="caption"></p>
</div>
<h5 id="change-defaults---registry-info---publisher-id"><a href="#TOC">Settings - Registry Info - Publisher Id</a></h5>
<p>Register into IATI registry and create a new Publisher. When you create a new Publisher in <a href="http://iatiregistry.org">IATI Registry</a>, you will have to fill up a form that includes <strong>publisher id</strong> - which is also required in AidStream to register automatically in the IATI Registry. You may also choose to do the register manually in the IATI Registry.</p>
<h5 id="change-defaults---registry-info---api-key"><a href="#TOC">Settings - Registry Info - API Key</a></h5>
<p>If you click on <strong>My account</strong> in IATI Registry, you should see <strong>API Key</strong> for use in AidStream.</p>
<p>By default, <strong>Automatically update the IATI Registry when publishing files</strong> is set to No. It means that when you publish files in Simplified AidStream, IATI XML files will be created but you will have to click <strong>Register with IATI Registry</strong> under <strong>List Published Files</strong> to register your XML files with IATI Registry. This option helps to create publish XML files without having to create account in IATI Registry.</p>
<p>By default, <strong>Automatically update the IATI Registry when publishing files</strong> is set to <strong>No</strong>. It means that when you publish files in AidStream, IATI XML files will be created but you will have to click <strong>Register with IATI Registry</strong> under <strong>List Published Files</strong> to register your XML files with IATI Registry. This option helps to create publish XML files without having to create account in IATI Registry.</p>
<h4 id="change-defaults---default-field-values"><a href="#TOC">Settings - Default Field Values</a></h4>
<div class="figure">
<img src="img/change.defaults-default.field.values.png" title="Default Field Values" /><p class="caption"></p>
</div>
<p>There are a number of pieces of information that remain the same for all your activities. By entering them in <strong>Default Field Values</strong> you will not have to re-enter them each time you enter a new activity. Enter only the mandatory field such as Default Currency and Default Language. The other fields would be useful only in the later phase.</p>
<h3 id="list-users"><a href="#TOC">List Users</a></h3>
<p>The users who have been created will be listed here.</p>
<p>While <strong>adding users</strong>, in the username field, appropriate name such as Chris, Dale can be entered and the account username for Chris would be account-identifier_Chris</p>
<h3 id="add-new-activity"><a href="#TOC">Add new activity</a></h3>
<p>Data can be entered to various field under different sections such as project information, location information, budget information etc. As you enter the data and save it, a new activity will be created. This activity can be viewed from <strong>List Activities</strong> section. Further changes can be made to the activity from <strong>Edit this activity</strong>.</p>
<div class="figure">
<img src="img/add-activity.png" title="Add Activity" /><p class="caption"></p>
</div>
<h3 id="simplified-aidstream-activity-states"><a href="#TOC">Simplified Aidstream Activity States</a></h3>
<p>Simplified AidStream maintains a simple workflow to ensure that the activities are properly verified before it gets registered in IATI Registry for public view. The following states are maintained in the activities. - Edit - Completed - Verified - Published When the activity is in any one of the states, any further changes in the activity will return its state back to <strong>Editing</strong>. The entire flow has to be followed before the changes gets updated in the activity xml files and registered in IATI Registry. It is recommended that different users are given access to each of these roles for the workflow.</p>
<h2 id="publishing-of-activities"><a href="#TOC">Publishing of Activities</a></h2>
<p>You may publish the activities only when it is <strong>Checked</strong>. As you may see below, the <strong>Checked</strong> activity only is applicable for publishing. Clicking <strong>Publish</strong> will generate XML file(s) with the checked activity along with those activities in published state.</p>
<div class="figure">
<img src="img/listactivities-publishing.png" title="Activities List - publish files" /><p class="caption"></p>
</div>
<h3 id="registering-with-iati-registry"><a href="#TOC">Registering with IATI Registry</a></h3>
<p>Please see the <strong>Settings - Registry Info</strong> for required information before registering with IATI Registry. If you have set above option to <strong>No</strong>,</p>
<div class="figure">
<img src="img/register.to.registry-no.png" title="Register to Registry No" /><p class="caption"></p>
</div>
<div class="figure">
<img src="img/listactivities-publishing.png" title="Activities List - publish files" /><p class="caption"></p>
</div>
<p>Clicking on <strong>Publish</strong> button will create the XML files. You will then get the option to <strong>Register your published files in IATI Registry</strong> from List Published Files</p>
<div class="figure">
<img src="img/list-published-files.png" title="List Published Files" /><p class="caption"></p>
</div>
<p>If you have set <strong>Auto register with IATI Registry</strong> to <strong>Yes</strong> in Settings as shown below, Publish action will generate the XML files and also register them with the IATI Registry.</p>
<div class="figure">
<img src="img/register.to.registry-yes.png" title="Register to Registry Yes" /><p class="caption"></p>
</div>
<div class="figure">
<img src="img/list.activities-register.yes.png" title="List Activities" /><p class="caption"></p>
</div>
<p>Activities list will allow to generate XML file(s) and register with IATI Registry. Also, you may see the published xml files in <strong>List Published Files</strong> but the <strong>Register with IATI Registry</strong> will be disabled as shown below.</p>
<div class="figure">
<img src="img/register.to.registry-disabled.png" title="Register to Registry Disabled" /><p class="caption"></p>
</div>
<p>When you publish files for the first time and register with the IATI Registry, you will not see <strong>Delete</strong>. However when you change the <strong>Publishing type</strong> from Segmented to Unsegmented or vice versa, there will both types of files - Segmented as well as Unsegmented. <strong>Delete</strong> option will allow you to delete the files in that case, however care needs to be taken as the files which are registered in IATI Registry may be in use by third party applications. E.g. you may see below there are segmented files viz yipl-bg.xml and yipl-998.xml as well as unsegemented file viz. yipl-activities.xml, after changing <strong>Publishing type</strong> from Segmented to Unsegmented. <strong>Delete</strong> link appears now, however it gives alerts before deleting the files from the server.</p>
<div class="figure">
<img src="img/list.published.files-delete.link.png" title="Delete Link" /><p class="caption"></p>
</div>
<p>Clicking <strong>Delete</strong> will alert you with the following message for the IATI Registry linked files.</p>
<div class="figure">
<img src="img/delete.confirmation.png" title="Delete confirmation" /><p class="caption"></p>
</div>
</div>
</body>
</html>
