<li class="element-activity">
    
    <div class="element-title">
        Activity Default

        <div class="element-info">
            <div class="element-values">
                <?php if($this->activityInfo['@xml_lang']): ?>
                    <span class="attrib-label">Lang:</span>					
                    <span class="attrib-value"><?php print $this->length()->adjustTripleLength(Iati_Core_Codelist::getCodeByAttrib('Activity' , '@xml_lang' , $this->activityInfo['@xml_lang'])); ?></span>
                <?php endif; ?>
            </div>
            <div class="element-values">
                <?php if($this->activityInfo['@default_currency']): ?>
                    <span class="attrib-label"> Curr:</span>
                    <span class="attrib-value"><?php print $this->length()->adjustTripleLength(Iati_Core_Codelist::getCodeByAttrib('Activity' , '@default_currency' , $this->activityInfo['@default_currency'])); ?></span>  
                <?php endif; ?>
            </div>
            <div class="element-values">
                <?php if($this->activityInfo['@last_updated_datetime']): ?>
                    <span class="attrib-label">Last updated date:</span>
                    <span class="attrib-value"><?php print $this->length()->adjustTripleLength($this->activityInfo['@last_updated_datetime']); ?></span>
                <?php endif; ?>
            </div>
        </div> 
        
    </div>
    
    <div class="edit"><a href="<?php echo $this->baseUrl()?>/activity/edit-element/?activity_id=<?php echo $this->activityInfo['id']?>&className=Activity">Edit</a></div>	
    
    <div class="highlight">
        <ul class="style-1">
            <li>
                <span class="name">Language:</span>
                <span class="infom"><?php 
                                                if ($this->activityInfo['@xml_lang'])
                                                {
                                                    printf("%s ", Iati_Core_Codelist::getCodeByAttrib('Activity' , '@xml_lang' , $this->activityInfo['@xml_lang']));
                                                }
                                            ?> 
                </span>
            </li>
            <li>
                <span class="name">Default Currency:</span>
                <span class="infom"><?php if($this->activityInfo['@default_currency']) (printf("%s ",Iati_Core_Codelist::getCodeByAttrib('Activity' , '@default_currency' , $this->activityInfo['@default_currency']))) ?></span>
            </li>
            <li>
                <span class="name">Hierarchy: </span>
                <span class="infom"><?php print $this->activityInfo['@hierarchy']; ?></span>
            </li>
            <li>
                <span class="name">Last Updated Date Time: </span>
                <span class="infom"><?php print $this->activityInfo['@last_updated_datetime']; ?></span>
            </li>
        </ul>
    </div>
</li><!-- end of element-activity -->

