<li class="element-activity">

    <div class="element-title element-current">
        Budget
    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_Budget">Edit</a></div>

    <?php foreach ($this->elements as $element): ?>
        <div class="current">
            <ul class="style-2 arrow">
                <li><span class="down-arrow"><?php if ($element['@type']) ( printf("%s [%s]" , $this->length()->adjustTripleTitleLength(Iati_Core_Codelist::getCodeByAttrib('Budget' , '@type' , $element['@type'],'Name')),Iati_Core_Codelist::getCodeByAttrib('Budget' , '@type' , $element['@type']))) ?>
                       <?php
                        $value = $element['Value'];
                        ?>
                        <?php if (!empty($value)): ?> 
                                <?php if ($element['@type'] && $value['text']) print "; "; ?>
                                <?php  ($value['@currency']) ? (printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity' , '@default_currency' , $value['@currency']))) : (printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity' , '@default_currency', $this->activityInfo['@default_currency']))); ?> 
                                <?php if ($value['text']) print($this->length()->adjustTripleTitleLength($this->numberFormat()->localization($value['text']))); ?>
                                <?php if ($value['text'] && $value['@value_date']) print "; "; ?>
                                <?php if ($value['@value_date']) print ($this->length()->adjustTripleTitleLength($value['@value_date'])); ?>
                        <?php endif; ?>
                    </span>
                    <ul class="style-4 none">
                        <li><span class="name">Text:</span>
                            <span class="infom"><?php if ($element['@type']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('Budget' , '@type' , $element['@type'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Budget' , '@type' , $element['@type']))) ?></span>
                        </li></ul>

                    <!-- PeriodEnd Starts -->
                    <?php
                    $periodend = $element['PeriodEnd'];
                    if (!empty($periodend)):
                        ?>
                        <ul class="style-1 style-4">
                            <h2>Period End</h2>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php if ($periodend['text']) print ($periodend['text']); ?></span>
                                </li>
                                <li>
                                    <span class="name">Iso_date:</span>
                                    <span class="infom"><?php if ($periodend['@iso_date']) print ($periodend['@iso_date']); ?></span>
                                </li>
                        </ul>
                    <?php endif; ?>
                    <!-- PeriodEnd Ends -->

                    <!-- PeriodStart Starts -->
                    <?php
                    $periodstart = $element['PeriodStart'];
                    if (!empty($periodstart)):
                        ?>

                        <ul class="style-1 style-4">
                            <h2>Period End</h2>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php if ($periodstart['text']) print ($periodstart['text']); ?></span>
                                </li>
                                <li>
                                    <span class="name">Iso_date:</span>
                                    <span class="infom"><?php if ($periodstart['@iso_date']) print ($periodstart['@iso_date']); ?></span>
                                </li>
                        </ul>
                    <?php endif; ?>
                    <!-- PeriodStart Ends -->

                    <!-- Value Starts -->
                    <?php
                    $value = $element['Value'];
                    ?>
                    <?php if (!empty($value)): ?>
                        <ul class="style-1 style-4">
                            <h2>Value</h2>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php if ($value['text']) print ($this->numberFormat()->localization($value['text'])); ?></span>
                                </li>
                                <li>
                                    <span class="name">Value_date:</span>
                                    <span class="infom"><?php if ($value['@value_date']) print ($value['@value_date']); ?></span>
                                </li>
                                <li>
                                    <span class="name">Currency:</span>
                                    <span class="infom"><?php if ($value['@currency']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('Activity' , '@default_currency', $value['@currency'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Activity' , '@default_currency', $value['@currency']))) ?></span>
                                </li>
                        </ul>
                    <?php endif; ?>
                    <!-- Value Ends -->
                </li>
            </ul>
        </div>
    <?php endforeach; ?>   

</li>

