<li class="element-activity">

    <div class="element-title">
        Collaboration Type

        <?php foreach ($this->collaborationtypes as $collaborationtype): ?>
            <div class="element-info">
                <div class="element-values">
                    <?php if($collaborationtype->getAttrib('@code')): ?>
                        <span class="attrib-label">Code:</span>
                        <span class="attrib-value"><?php if ($collaborationtype->getAttrib('@code')) ($collaborationtype->getAttribValue('@code' , 'Name') != $collaborationtype->getAttribValue('@code')) ? ( printf("%s [%s]" , $this->length()->adjustSingleLength($collaborationtype->getAttribValue('@code' , 'Name')) , $collaborationtype->getAttribValue('@code'))) : (print($collaborationtype->getAttribValue('@code'))); ?></span>
                    <?php endif; ?>
                </div>
            </div>
            <?php break; ?>
        <?php endforeach; ?>

    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/wep/edit-activity-elements/?activity_id=<?php echo $this->activityInfo['id'] ?>&class=CollaborationType">Edit</a></div>	

    <?php foreach ($this->collaborationtypes as $collaborationtype): ?>
        <div class="highlight">
            <ul class="style-1">
                <li>
                    <span class="name">Code:</span>
                    <span class="infom"><?php if ($collaborationtype->getAttrib('@code')) ($collaborationtype->getAttribValue('@code' , 'Name') != $collaborationtype->getAttribValue('@code')) ? ( printf("%s [%s]" , $collaborationtype->getAttribValue('@code' , 'Name') , $collaborationtype->getAttribValue('@code'))) : (print($collaborationtype->getAttribValue('@code'))); ?></span>
                </li>
                <li>
                    <span class="name">Text:</span>
                    <span class="infom"><?php if ($collaborationtype->getAttrib('text')) print ($collaborationtype->getAttribValue('text')); ?><?php if ($collaborationtype->getAttrib('@xml_lang')) printf(" [%s]" , ($collaborationtype->getAttribValue('@xml_lang'))); ?></span>
                </li>
            </ul>
        </div>
    <?php endforeach; ?>

</li><!-- end of element-activity -->

