<li class="element-activity drop">

    <div class="element-title">
        Contact Info
    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_ContactInfo">Edit</a></div>	

    <?php $i = 1; ?>
    <?php foreach ($this->elements as $element): ?>
        <?php if ($i == '1'): ?>
            <div class="highlight">
            <?php else: ?>
                <div class="highlight first">
                <?php endif; ?>

                <ul class="style-3">
                     <!-- contact info type -->
                    <?php $type = $element['@type']; ?>
                    <?php if ($type || $element['@xml_lang']): ?>                        
                        <li>
                            <span class="name">Type: </span>
                                <span class="infom">
                                    <?php print $type; ?>
                                     <?php if ($element['@xml_lang'])
                                                            {
                                                                printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('ContactInfo' , '@xml_lang' , $element['@xml_lang']));
                                                            }
                                                    ?> 
                                </span>
                        </li>
                    <?php endif; ?>
                    
                    <!-- Organisation Starts -->
                    <?php
                    $organisation = $element['Organisation'];
                    ?>
                    <?php if (!empty($organisation)): ?>  
                        <li>
                            <span class="name">Organisation Name:</span>
                                <span class="infom">
                                    <?php if ($organisation['text']) print ($organisation['text']); ?>
                                </span>
                        </li>              
                    <?php endif; ?>
                    <!-- Organisation Ends -->


                    <!-- PersonName Starts -->
                    <?php
                    $personname = $element['PersonName'];
                    ?>
                    <?php if (!empty($personname)): ?>                        
                        <li>
                            <span class="name">Person Name: </span>
                                <span class="infom">
                                    <?php if ($personname['text']) print ($personname['text']); ?>
                                </span>
                        </li>
                    <?php endif; ?>
                    <!-- PersonName Ends -->
                    
                    <!-- JobTitle Starts -->
                    <?php
                    $jobtitle = $element['JobTitle'];
                    ?>
                    <?php if (!empty($jobtitle)): ?>                        
                        <li>
                            <span class="name">Job Title: </span>
                                <span class="infom"><?php if ($jobtitle['text']) print ($jobtitle['text']); ?>
                                                    <?php if ($jobtitle['@xml_lang'])
                                                            {
                                                                printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('JobTitle' , '@xml_lang' , $jobtitle['@xml_lang']));
                                                            }
                                                    ?> 
                                </span>
                        </li>
                    <?php endif; ?>
                    <!-- JobTitle Ends -->


                    <!-- Telephone Starts -->
                    <?php
                    $telephones = $element['Telephone']
                    ?>
                    <?php if (!empty($telephones)): ?>                        
                        <li>
                            <span class="name">Telephone:</span>
                            <?php foreach ($telephones as $telephone): ?>
                                <span class="infom">
                                    <?php if ($telephone['text']) print ($telephone['text']); ?>

                                </span>
                            <?php endforeach; ?>
                        </li>                       
                    <?php endif; ?>
                    <!-- Telephone Ends -->

                    <!-- Email Starts -->
                    <?php
                    $emails = $element['Email']
                    ?>
                    <?php if (!empty($emails)): ?>                        
                        <li>
                            <span class="name">Email: </span>
                            <?php foreach ($emails as $email): ?>
                                <span class="infom">
                                    <?php if ($email['text']) print ($email['text']); ?>

                                </span>
                            <?php endforeach; ?>
                        </li>                        
                    <?php endif; ?>
                    <!-- Email Ends -->

                    <!-- MailingAddress Starts -->
                    <?php
                    $mailingaddresss = $element['MailingAddress'];
                    ?>
                    <?php if (!empty($mailingaddresss)): ?>                       
                        <li>
                            <span class="name">Mailing Address:</span>
                            <?php foreach ($mailingaddresss as $mailingaddress): ?>                                
                                <span class="infom">
                                    <?php if ($mailingaddress['text']) print ($mailingaddress['text']); ?>

                                </span>
                            <?php endforeach; ?>
                        </li>
                    <?php endif; ?>
                    <!-- MailingAddress Ends -->
                    
                    <!-- Website Starts -->
                    <?php
                    $websites = $element['Website'];
                    ?>
                    <?php if (!empty($websites)): ?>                       
                        <li>
                            <span class="name">Website:</span>
                            <?php foreach ($websites as $website): ?>                                
                                <span class="infom">
                                    <?php if ($website['text']) print ($website['text']); ?>

                                </span>
                            <?php endforeach; ?>
                        </li>
                    <?php endif; ?>
                    <!-- Website Ends -->
                    
                </ul> <!-- End .style-1 style-4 -->
            </div>
            <?php $i = $i + 1; ?>
        <?php endforeach; ?>

</li><!-- end of element-activity -->

