<?php $element = $this->countrybudgetitems;?>
<ul class="style-4 none">
                        <li>
                            <span class="name">Vocabulary:</span>
                            <span class="infom"><?php printf("%s[%s]",Iati_Core_Codelist::getCodeByAttrib('CountryBudgetItems' , '@vocabulary' , $element['@vocabulary'] , 'Name'),Iati_Core_Codelist::getCodeByAttrib('CountryBudgetItems' , '@vocabulary' , $element['@vocabulary'])) ;?></span>
                        </li>

                    </ul>
                    
                    <!-- Budget Items Starts -->
                    <?php
                    $budgetItems = $element['BudgetItem'];
                    if (!empty($budgetItems)):
                    ?>
                        <?php foreach($budgetItems as $budgetItem):?>
                        <ul class="style-1 style-4">
                            <h2>Budget Item</h2>
                                <li>
                                    <span class="name">Code:</span>
                                    <span class="infom"><?php if ($budgetItem['@code'])(printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('BudgetItem' , '@code', $budgetItem['@code'],'Name'),Iati_Core_Codelist::getCodeByAttrib('BudgetItem' , '@code', $budgetItem['@code']))) ?></span>
                                </li>
                                <li>
                                    <span class="name">Percentage:</span>
                                    <span class="infom"><?php if ($budgetItem['@percentage']) print $budgetItem['@percentage'] ?></span>
                                </li>
                        </ul>
                        
                            <!-- Description Starts -->
                            <?php
                            $descriptions = $budgetItem['Description'];
                            if (!empty($descriptions)):
                            ?>
                                <?php foreach($descriptions as $descriptionItem):?>
                                <ul class="style-1 style-4">
                                    <h2>Description</h2>
                                    <li>
                                        <span class="name">Text:</span>
                                        <span class="infom"> <?php if ($descriptionItem['text']) print ($descriptionItem['text']); ?>
                                            <?php
                                                            if ($descriptionItem['@xml_lang'])
                                                            {
                                                                printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('Description' , '@xml_lang' , $descriptionItem['@xml_lang']));
                                                            }
                                                        ?> 
                                        </span>
                                    </li>
                                    <li>
                                        <span class="name">Type:</span>
                                        <span class="infom"><?php if ($descriptionItem['@type']) (printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('Description' , '@type' , $descriptionItem['@type'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Description' , '@type' , $descriptionItem['@type']))) ?></span>
                                    </li>
                                </ul>
                                
                                
                                <?php endforeach;?>
                            <?php endif; ?>
                            <!-- Budget Item Ends -->
                        
                        <?php endforeach;?>
                    <?php endif; ?>
                    <!-- Budget Item Ends -->