<li class="element-activity">

    <div class="element-title ">
        Country Budget Items
            <div class="element-info">
                <div class="element-values">
                    <?php if($this->elements['@vocabulary']): ?>
                        <span class="attrib-label">Vocabulary:</span>
                        <span class="attrib-value"><?php if ($this->elements['@vocabulary']) (printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('CountryBudgetItems' , '@vocabulary' , $this->elements['@vocabulary'],'Name'),Iati_Core_Codelist::getCodeByAttrib('CountryBudgetItems' , '@vocabulary' , $this->elements['@vocabulary']))) ?></span>  
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_CountryBudgetItems">Edit</a></div>

        <div class="highlight">
            <ul class="style-1">
                <li>
                    <span class="name">Vocabulary:</span>
                    <span class="infom"><?php if ($this->elements['@vocabulary']) (printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('CountryBudgetItems' , '@vocabulary' , $this->elements['@vocabulary'],'Name'),Iati_Core_Codelist::getCodeByAttrib('CountryBudgetItems' , '@vocabulary' , $this->elements['@vocabulary']))) ?></span>
                </li>
                <li>
                    <span class="name"><h2>Budget Item:</h2>    </span>
                    <?php $budgetItems = $this->elements['BudgetItem']; ?>
                        <?php foreach ($budgetItems as $budgetItem): ?>
                        <ul class="country-budget-item">
                        <li>
                            <span class="name"> Code:</span>
                            <!-- <span class="infom"> <?php if ($budgetItem['@code'] != "") print ($budgetItem['@code']); ?>
                            </span> -->
                            <span class="infom">
                                <?php if ($budgetItem['@code']): ?>
                                    <?php if ($this->elements['@vocabulary'] == 1): ?>
                                        <?php (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('BudgetItem' , '@code' , $budgetItem['@code'],'Name'),Iati_Core_Codelist::getCodeByAttrib('BudgetItem' , '@code' , $budgetItem['@code']))) ?>
                                    <?php else : ?>
                                        <?php print ($budgetItem['@code']); ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </span>
                        </li>
                        <li>
                            <span class="name"> Percentage:</span>
                            <span class="infom"> <?php if ($budgetItem['@percentage'] != "") print ($budgetItem['@percentage']); ?>
                            </span>
                        </li>

                        <?php foreach ($budgetItem['Description'] as $description): ?>
                            <?php foreach($description['Narrative'] as $nar): ?>
                                <li>
                                    <span class="name"> Narrative:</span>
                                    <span class="infom"> <?php if ($nar['text'] != "") print ($nar['text']); ?>
                                        <?php
                                            if ($nar['@xml_lang'])
                                            {
                                                printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('CountryBudgetItems' , '@xml_lang' , $nar['@xml_lang']));
                                            }
                                        ?> 
                                    </span>
                                </li>
                            <?php endforeach; ?>
                        <?php endforeach;?>
                </ul>
                <?php endforeach; ?>
        </div>
</ul>

</li><!-- end of element-activity -->