<li class="element-activity">
    <div class="element-title">
        Default Flow Type

        <?php foreach ($this->defaultflowtypes as $defaultflowtype): ?>
            <div class="element-info">
                <div class="element-values">
                    <span class="attrib-label">Code:</span>
                    <span class="attrib-value"><?php if ($defaultflowtype->getAttrib('@code')) ($defaultflowtype->getAttribValue('@code' , 'Name') != $defaultflowtype->getAttribValue('@code')) ? ( printf("%s [%s]" , $this->length()->adjustSingleLength($defaultflowtype->getAttribValue('@code' , 'Name')) , $defaultflowtype->getAttribValue('@code'))) : (print($defaultflowtype->getAttribValue('@code'))); ?></span>
                </div>
            </div>
            <?php break; ?>
        <?php endforeach; ?>  

    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/wep/edit-activity-elements/?activity_id=<?php echo $this->activityInfo['id'] ?>&class=DefaultFlowType">Edit</a></div>	

    <?php foreach ($this->defaultflowtypes as $defaultflowtype): ?>
        <div class="highlight">
            <ul class="style-1">
                <li>
                    <span class="name">Code:</span>
                    <span class="infom"><?php if ($defaultflowtype->getAttrib('@code')) ($defaultflowtype->getAttribValue('@code' , 'Name') != $defaultflowtype->getAttribValue('@code')) ? ( printf("%s [%s]" , $defaultflowtype->getAttribValue('@code' , 'Name') , $defaultflowtype->getAttribValue('@code'))) : (print($defaultflowtype->getAttribValue('@code'))); ?></span>
                </li>
                <li>
                    <span class="name">Text:</span>
                    <span class="infom"><?php if ($defaultflowtype->getAttrib('text')) print ($defaultflowtype->getAttribValue('text')); ?><?php if ($defaultflowtype->getAttrib('@xml_lang')) printf(" [%s]" , ($defaultflowtype->getAttribValue('@xml_lang'))); ?></span>
                </li>
            </ul>
        </div>
    <?php endforeach; ?>

</li><!-- end of element-activity -->
