<li class="element-activity">
    
    <div class="element-title element-current">
        Description
    </div>
    
    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_Description">Edit</a></div>

    <?php foreach ($this->elements as $element): ?>
        <?php $narratives = $element['Narrative']; ?>
            <div class="current">
                <ul class="style-2 arrow">
                    <li> <span class="down-arrow"><?php if ($element['@type']) (printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('Description' , '@type' , $element['@type'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Description' , '@type' , $element['@type']))) ?></span>
                        <ul class="style-2-drop first">
                            <li>
                                <span class="name">Type:</span>
                                <span class="infom"><?php if ($element['@type']) (printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('Description' , '@type' , $element['@type'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Description' , '@type' , $element['@type']))) ?></span>
                            </li>
                            <?php foreach ($narratives as $narrative): ?>
                                <li>
                                    <span class="name"> Narrative Text:</span>
                                    <span class="infom"> <?php if ($narrative['text'] != "") print ($narrative['text']); ?>
                                        <?php
                                                        if ($narrative['@xml_lang'])
                                                        {
                                                            printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('Description' , '@xml_lang' , $narrative['@xml_lang']));
                                                        }
                                                    ?> 
                                    </span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                </ul>
            </div>   
    <?php endforeach; ?>
    
</li><!-- end of element-activity -->

