<li class="element-activity">

    <div class="element-title">
        Document Link
    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_DocumentLink">Edit</a></div>
    
    <?php $i=0; ?>
    <?php foreach ($this->elements as $element): ?>
         <?php if ($i == '0'): ?>
            <div class="highlight first">
            <?php else: ?>
                <div class="highlight">
                <?php endif; ?>
            <ul class="style-4 first">
                <li>
                    <span class="name">Url:</span>
                    <span class="infom sub-details"><?php if ($element['@url']) (print $element['@url'] )?></span>
                </li>
                <li>
                    <span class="name">Format:</span>
                    <span class="infom sub-details"><?php if ($element['@format'])(printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('DocumentLink' , '@format' , $element['@format'],'Name'),Iati_Core_Codelist::getCodeByAttrib('DocumentLink' , '@format' , $element['@format']))) ?></span>
                </li>
            </ul>

            <!-- Language Starts -->
            <?php $languages = $element['Language']; ?>
            <?php if (!empty($languages)): ?>
                <ul class="style-1 style-4">
                    <h2>Language</h2>
                    <?php foreach ($languages as $language): ?>
                        <li>
                            <span class="name">Code</span>
                            <span class="infom"><?php if ($language['@code'])
                                                        {
                                                            printf("%s [%s]" ,Iati_Core_Codelist::getCodeByAttrib('Language' , '@xml_lang' , $language['@code'],'Name'), Iati_Core_Codelist::getCodeByAttrib('Language' , '@xml_lang' , $language['@code']));
                                                        }
                                                ?> 
                            </span>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <!-- Language Ends -->

            <!-- Category Starts -->
            <?php $categorys = $element['Category']; ?>
            <?php if (!empty($categorys)): ?>
                <ul class="style-1 style-4">
                    <h2>Category</h2>
                    <?php foreach ($categorys as $category): ?>
                        <li>
                            <span class="name">Code:</span>
                            <span class="infom"><?php if ($category['@code']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('Category' , '@code' , $category['@code'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Category' , '@code' , $category['@code']))) ?></span>
                        </li>
                    <?php endforeach; ?>
                </ul>     
            <?php endif; ?>
            <!-- Category Ends -->

            <!-- Title Starts -->
            <?php $titles = $element['Title']; ?>
            <?php if (!empty($titles)): ?>
                <ul class="style-1 style-4">
                    <h2>Title</h2>
                    <?php foreach ($titles as $title): ?>
                        <li>
                            <span class="name">Text:</span>
                            <span class="infom"><?php if ($title['text'] != "") print ($title['text']); ?>
                                                <?php if ($title['@xml_lang'])
                                                    {
                                                        printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('Title' , '@xml_lang' , $title['@xml_lang']));
                                                    }
                                                ?> 
                            </span>
                        </li>
                    <?php endforeach; ?>
                </ul> 
            <?php endif; ?>
            <!-- Title Ends -->

        </div>
      <?php $i= $i+1; ?>
    <?php endforeach; ?>

</li><!-- end of element-activity -->