<li class="element-activity">

    <div class="element-title ">
        Identifier

            <div class="element-info">        
                <div class="element-values">
                    <?php if($this->elements['text']): ?>
                        <span class="attrib-label">Text:</span>					
                        <span class="attrib-value"><?php if ($this->elements['text']) print $this->length()->adjustSingleLength($this->elements['text']); ?></span>
                    <?php endif; ?>
                </div>
            </div>

        </div>   

        <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id ?>&className=Activity_IatiIdentifier">Edit</a></div>	

        <div class="highlight">
            <ul class="style-1">
                <li>
                    <span class="name">Text:</span>
                    <span class="infom"><?php if ($this->elements['text']) print ($this->elements['text']); ?></span>
                </li>        
            </ul>
        </div>
        
</li><!-- end of element-activity -->