<li class="element-activity">

    <div class="element-title ">
        Identifier

        <?php foreach ($this->identifiers as $identifier): ?>    
            <div class="element-info">        
                <div class="element-values">
                    <span class="attrib-label">Text:</span>					
                    <span class="attrib-value"><?php if ($identifier->getAttrib('text')) print $this->length()->adjustSingleLength($identifier->getAttrib('text')); ?></span>
                </div>
            </div>

        </div>   

        <div class="edit"><a href="<?php echo $this->baseUrl() ?>/wep/edit-activity-elements/?activity_id=<?php echo $this->activityInfo['id'] ?>&class=Identifier">Edit</a></div>	

        <div class="highlight">
            <ul class="style-1">
                <li>
                    <span class="name">Text:</span>
                    <span class="infom"><?php if ($identifier->getAttrib('text')) print ($identifier->getAttribValue('text')); ?></span>
                </li>        
            </ul>
        </div>

    <?php endforeach; ?>
</li><!-- end of element-activity -->