<li class="element-activity">

    <div class="element-title">
        Location
    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_Location">Edit</a></div>

    <?php $i = 0; ?>
    <?php foreach ($this->elements as $element): ?>
       <?php if ($i == '1'): ?>
            <div class="highlight">
            <?php else: ?>
                <div class="highlight first">
                <?php endif; ?>
                <ul class="style-4 first">
                    <li>
                        <span class="name">Percentage: </span>
                        <span class="infom sub-details"><?php if ($element['@percentage']) print ($element['@percentage']); ?></span>
                    </li>

                </ul>

                <!-- LocationType Starts -->
                <?php
                $locationtype = $element['LocationType'];
                ?>
                <?php if (!empty($locationtype)): ?>
                    <ul class="style-1 style-4">
                        <h2>Location Type</h2>
                            <li>
                                <span class="name">Text:</span>
                                <span class="infom"><?php if ($locationtype['text']) print ($locationtype['text']); ?>
                                    <?php
                                                if ($locationtype['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('LocationType' , '@xml_lang' , $locationtype['@xml_lang']));
                                                }
                                            ?> 
                                </span>
                            </li>
                            <li>
                                <span class="name">Code:</span>
                                <span class="infom"><?php if ($locationtype['@code']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('LocationType' , '@code' , $locationtype['@code'],'Name'),Iati_Core_Codelist::getCodeByAttrib('LocationType' , '@code' , $locationtype['@code']))) ?></span>
                            </li>
                    </ul>
                <?php endif; ?>
                <!-- LocationType Ends -->

                <!-- Name Starts -->
                <?php
                $names = $element['Name'];
                ?>
                <?php if (!empty($names)): ?>
                    <ul class="style-1 style-4">
                        <h2>Name</h2>
                        <?php foreach ($names as $name): ?>
                            <li>
                                <span class="name">Text:</span>
                                <span class="infom"><?php if ($name['text']) print ($name['text']); ?>
                                    <?php
                                                if ($name['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('Name' , '@xml_lang' , $name['@xml_lang']));
                                                }
                                            ?>
                                </span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <!-- Name Ends -->

                <!-- Description Starts -->
                <?php
                $descriptions = $element['Description'];
                ?>
                <?php if (!empty($descriptions)): ?>
                    <ul class="style-1 style-4">
                        <h2>Description</h2>
                        <?php foreach ($descriptions as $description): ?>
                            <li>
                                <span class="name">Text:</span>
                                <span class="infom"><?php if ($description['text']) print ($description['text']); ?>
                                    <?php
                                                if ($description['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('Location' , '@xml_lang' , $description['@xml_lang']));
                                                }
                                            ?>
                                </span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <!-- Description Ends -->

                <!-- Administrative Starts -->
                <?php
                $administrative = $element['Administrative'];
                ?>
                <?php if (!empty($administrative)): ?>
                    <ul class="style-1 style-4">
                        <h2>Administrative</h2>
                            <li>
                                <span class="name">Text:</span>
                                <span class="infom"><?php if ($administrative['text']) print ($administrative['text']); ?>
                                    <?php
                                                if ($administrative['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('Administrative' , '@xml_lang' , $administrative['@xml_lang']));
                                                }
                                            ?> 
                                </span>
                            </li>
                            <li>
                                <span class="name">Country:</span>
                                <span class="infom"><?php if ($administrative['@country']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('Administrative' , '@country' , $administrative['@country'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Administrative' , '@country' , $administrative['@country']))) ?></span>
                            </li>
                            <li>
                                <span class="name">Adm-1:</span>
                                <span class="infom"><?php if ($administrative['@adm1']) (print $administrative['@adm1']) ?></span>
                            </li>
                            <li>
                                <span class="name">Adm-2:</span>
                                <span class="infom"><?php if ($administrative['@adm2']) (print $administrative['@adm2']) ?></span>
                            </li>
                    </ul>
                <?php endif; ?>
                <!-- Description Ends -->
                
                <!-- Coordinates Starts -->
                <?php
                $coordinates=$element['Coordinates'];
                ?>
                <?php if (!empty($coordinates)): ?>
                    <ul class="style-1 style-4">
                        <h2>Coordinates</h2>
                            <li>
                                <span class="name">Latitude:</span>
                                <span class="infom"><?php if($coordinates['@latitude'])(print $coordinates['@latitude']) ?></span>
                            </li>
                            <li>
                                <span class="name">Longitude:</span>
                                <span class="infom"><?php if($coordinates['@longitude']) ( print $coordinates['@longitude'])?></span>
                            </li>
                            <li>
                                <span class="name">Precision:</span>
                                <span class="infom"> <?php if($coordinates['@precision']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('Coordinates' , '@precision' , $coordinates['@precision'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Coordinates' , '@precision' , $coordinates['@precision']))) ?></span>
                            </li>
                    </ul>
                <?php endif; ?>
                <!-- Coordinates Ends -->
                
                <!-- GazetteerEntry Starts -->
                <?php
                $gazetteerentrys=$element['GazetteerEntry']
                ?>
                <?php if (!empty($gazetteerentrys)): ?>
                    <ul class="style-1 style-4">
                        <h2>Gazetteer Entry</h2>
                        <?php foreach($gazetteerentrys as $gazetteerentry): ?>
                            <li>
                                <span class="name">Text:</span>
                                <span class="infom"><?php if($gazetteerentry['text']) print ($gazetteerentry['text']);?></span>
                            </li>
                            <li>
                                <span class="name">Gazetteer_ref:</span>
                                <span class="infom"><?php if($gazetteerentry['@gazetteer_ref']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('GazetteerEntry' , '@gazetteer_ref' , $gazetteerentry['@gazetteer_ref'],'Name'),Iati_Core_Codelist::getCodeByAttrib('GazetteerEntry' , '@gazetteer_ref' , $gazetteerentry['@gazetteer_ref'])))?></span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <!-- GazetteerEntry Ends -->
                
            </div>
            <?php $i = $i + 1; ?>
        <?php endforeach; ?>

</li><!-- end of element-activity -->