<li class="element-activity">

    <div class="element-title element-current">
        Other Activity Identifier     
    </div>     

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/wep/edit-activity-elements/?activity_id=<?php echo $this->activityInfo['id'] ?>&class=OtherActivityIdentifier">Edit</a></div>	

    <?php foreach ($this->otheridentifiers as $otheridentifier): ?>
        <div class="current">
            <ul class="style-2 arrow">
                <li> <span class="down-arrow"><?php if ($otheridentifier->getAttrib('text')) print ($this->length()->adjustTitleLength($otheridentifier->getAttribValue('text'))); ?></span>
                    <ul class="style-2-drop first">
                        <li>
                            <span class="name">Text:</span>
                            <span class="infom"><?php if ($otheridentifier->getAttrib('text')) print ($otheridentifier->getAttribValue('text')); ?></span>
                        </li>
                        <li>
                            <span class="name">Owner_ref:</span>
                            <span class="infom"><?php if ($otheridentifier->getAttrib('@owner_ref')) ($otheridentifier->getAttribValue('@owner_ref' , 'Name') != $otheridentifier->getAttribValue('@owner_ref')) ? ( printf("%s [%s]" , $otheridentifier->getAttribValue('@owner_ref' , 'Name') , $otheridentifier->getAttribValue('@owner_ref'))) : (print($otheridentifier->getAttribValue('@owner_ref'))); ?></span>
                        </li>
                        <li>
                            <span class="name">Owner_name:</span>
                            <span class="infom"><?php if ($otheridentifier->getAttrib('@owner_name')) ($otheridentifier->getAttribValue('@owner_name' , 'Name') != $otheridentifier->getAttribValue('@owner_name')) ? ( printf("%s [%s]" , $otheridentifier->getAttribValue('@owner_name' , 'Name') , $otheridentifier->getAttribValue('@owner_name'))) : (print($otheridentifier->getAttribValue('@owner_name'))); ?></span>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>    
    <?php endforeach; ?>

</li><!-- end of element-activity -->

