<li class="element-activity">

    <div class="element-title element-current">
        Planned Disbursement
    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/wep/edit-activity-elements/?activity_id=<?php echo $this->activityInfo['id'] ?>&class=PlannedDisbursement">Edit</a></div>

    <?php foreach ($this->planneddisbursements as $planneddisbursement): ?>
        <div class="current">
            <ul class="style-2 arrow">
                <li>
                    <span class="down-arrow"> 
                        <?php
                        $values = $planneddisbursement->getElementsByType('Value');
                        $value = $values[0]->getAttribs();
                        if (!empty($value)):
                            ?>
                            <?php foreach ($values as $value): ?>
                                <?php if ($value->getAttrib('text')) print ($value->getAttribValue('text')); ?> 
                                <?php if ($value->getAttrib('text') && $value->getAttrib('@value_date')) print "; "; ?>
                                <?php if ($value->getAttrib('@value_date')) print ($value->getAttribValue('@value_date')); ?>
                                <?php break; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </span>
                    <ul class="style-4 none">
                        <li>
                            <span class="name">Updated:</span>
                            <span class="infom"><?php if ($planneddisbursement->getAttrib('@updated')) print ($planneddisbursement->getAttribValue('@updated')); ?></span>
                        </li>

                    </ul>
                    <!-- PeriodEnd Starts -->
                    <?php
                    $periodends = $planneddisbursement->getElementsByType('PeriodEnd');
                    $value = $periodends[0]->getAttribs();
                    if (!empty($value)):
                        ?>
                        <ul class="style-1 style-4">
                            <h2>Period End</h2>
                            <?php foreach ($periodends as $periodend): ?>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php if ($periodend->getAttrib('text')) print ($periodend->getAttribValue('text')); ?></span>
                                </li>
                                <li>
                                    <span class="name">Iso_date:</span>
                                    <span class="infom"><?php if ($periodend->getAttrib('@iso_date')) print ($periodend->getAttribValue('@iso_date')); ?></span>
                                </li>
                            <?php endforeach; ?>

                        </ul>
                    <?php endif; ?>
                    <!-- PeriodEnd End -->

                    <!-- PeriodStart Starts -->
                    <?php
                    $periodstarts = $planneddisbursement->getElementsByType('PeriodStart');
                    $value = $periodstarts[0]->getAttribs();
                    if (!empty($value)):
                        ?>

                        <ul class="style-1 style-4">
                            <h2>Period End</h2>
                            <?php foreach ($periodstarts as $periodstart): ?>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php if ($periodstart->getAttrib('text')) print ($periodstart->getAttribValue('text')); ?></span>
                                </li>
                                <li>
                                    <span class="name">Iso_date:</span>
                                    <span class="infom"><?php if ($periodstart->getAttrib('@iso_date')) print ($periodstart->getAttribValue('@iso_date')); ?></span>
                                </li>
                            <?php endforeach; ?>

                        </ul>
                    <?php endif; ?>
                    <!-- PeriodStart Ends -->


                    <!-- Value Starts -->
                    <?php
                    $values = $planneddisbursement->getElementsByType('Value');
                    $value = $values[0]->getAttribs();
                    if (!empty($value)):
                        ?>
                        <ul class="style-1 style-4">
                            <h2>Value</h2>
                            <?php foreach ($values as $value): ?>
                                <li>
                                    <span class="name">Text:</span>
                                    <span class="infom"><?php if ($value->getAttrib('text')) print ($value->getAttribValue('text')); ?></span>
                                </li>
                                <li>
                                    <span class="name">Value_date:</span>
                                    <span class="infom"><?php if ($value->getAttrib('@value_date')) print ($value->getAttribValue('@value_date')); ?></span>
                                </li>
                                <li>
                                    <span class="name">Currency:</span>
                                    <span class="infom"><?php if ($value->getAttrib('@currency')) ($value->getAttribValue('@currency' , 'Name') != $value->getAttribValue('@currency')) ? ( printf("%s [%s]" , $value->getAttribValue('@currency' , 'Name') , $value->getAttribValue('@currency'))) : (print($value->getAttribValue('@currency'))); ?></span>
                                </li>
                            <?php endforeach; ?>

                        </ul>
                    <?php endif; ?>
                    <!-- Value Ends -->
                </li>
            </ul><!-- End .style-2 arrow -->
        </div>
    <?php endforeach; ?>

</li><!-- end of element-activity -->