<li class="element-activity">

    <div class="element-title element-current">
        Policy Marker
    </div>
    
    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_PolicyMarker">Edit</a></div>

    <?php foreach ($this->elements as $element): ?>
        <div class="current">
            <ul class="style-2 arrow">
                <li> <span class="down-arrow"><?php if ($element['@code']) ( printf("%s [%s]" , $this->length()->adjustSingleTitleLength(Iati_Core_Codelist::getCodeByAttrib('PolicyMarker' , '@code' , $element['@code'],'Name')) ,Iati_Core_Codelist::getCodeByAttrib('PolicyMarker' , '@code' , $element['@code'])))  ?></span>
                    <ul class="style-2-drop first">
                        <li>
                            <span class="name">Text:</span>
                            <span class="infom"><?php if ($element['text'] != "") print ($element['text']); ?>
                                <?php
                                                if ($element['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('PolicyMarker' , '@xml_lang' , $element['@xml_lang']));
                                                }
                                            ?> 
                            </span>
                        </li>
                        <li>
                            <span class="name">Significance:</span>
                            <span class="infom"><?php if ($element['@significance']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('PolicyMarker' , '@significance' , $element['@significance'],'Name'),Iati_Core_Codelist::getCodeByAttrib('PolicyMarker' , '@significance' , $element['@significance']))) ?></span>
                        </li>
                        <li>
                            <span class="name">Code:</span>
                            <span class="infom"><?php if ($element['@code']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('PolicyMarker' , '@code' , $element['@code'],'Name'),Iati_Core_Codelist::getCodeByAttrib('PolicyMarker' , '@code' , $element['@code']))) ?></span>
                        </li>
                        <!-- Hide Vocabulary (v1.2.7) --> 
                        <li style="display:none">
                            <span class="name">Vocabulary:</span>
                            <span class="infom"><?php if ($element['@vocabulary']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('PolicyMarker' , '@vocabulary' , $element['@vocabulary'],'Name'),Iati_Core_Codelist::getCodeByAttrib('PolicyMarker' , '@vocabulary' , $element['@vocabulary']))) ?></span>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    <?php endforeach; ?>

</li><!-- end of element-activity -->

