<li class="element-activity">

    <div class="element-title element-current">
        Recipient Country
    </div> 

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_RecipientCountry">Edit</a></div>

    <?php foreach ($this->elements as $element): ?> 
        <div class="current">
            <ul class="style-2 arrow">
                <li> <span class="down-arrow"><?php if ($element['@code']) ( printf("%s [%s]" , $this->length()->adjustDoubleTitleLength(Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@code' , $element['@code'],'Name')),Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@code' , $element['@code']))) ?>
                                              <?php if ($element['@code'] && $element['@percentage']) print "; "; ?>
                                              <?php if ($element['@percentage'] != "") print ($this->length()->adjustDoubleTitleLength($element['@percentage'])); ?></span>
                    <ul class="style-2-drop first">
                        <li>
                            <span class="name">Text:</span>
                            <span class="infom"><?php if ($element['text'] != "") print ($element['text']); ?>
                                <?php
                                                if ($element['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@xml_lang' , $element['@xml_lang']));
                                                }
                                            ?> 
                            </span>
                        </li>
                        <li>
                            <span class="name">Percentage:</span>
                            <span class="infom"><?php if ($element['@percentage'] != "") print ($element['@percentage']); ?></span>
                        </li>
                        <li>
                            <span class="name">Code:</span>
                            <span class="infom"><?php if ($element['@code']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@code' , $element['@code'],'Name'),Iati_Core_Codelist::getCodeByAttrib('RecipientCountry' , '@code' , $element['@code']))) ?></span>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    <?php endforeach; ?>
</li><!-- end of element-activity -->

