<li class="element-activity">

    <div class="element-title ">
        Reporting Organization

            <div class="element-info">
                <div class="element-values">
                    <?php if($this->elements['@ref']): ?>
                        <span class="attrib-label">Ref:</span>
                        <span class="attrib-value"><?php if ($this->elements['@ref']) (printf("%s" , $this->length()->adjustDoubleLength(Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@ref' , $this->elements['@ref'],'Name')))) ?></span>  
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="highlight">
            <ul class="style-1">
                <li>
                    <span class="name">Ref:</span>
                    <span class="infom"><?php if ($this->elements['@ref']) (printf("%s ",Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@ref' , $this->elements['@ref'],'Name'))) ?></span>
                </li>
                <li>
                    <span class="name">Type:</span>
                    <span class="infom"><?php if ($this->elements['@type']) (printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@type' , $this->elements['@type'],'Name'),Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@type' , $this->elements['@type']))) ?></span>
                </li>

                <?php $narratives = $this->elements['Narrative']; ?>
                <?php foreach ($narratives as $narrative): ?>
                    <li>
                        <span class="name"> Narrative Text:</span>
                        <span class="infom"> <?php if ($narrative['text'] != "") print ($narrative['text']); ?>
                            <?php
                                if ($narrative['@xml_lang'])
                                {
                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@xml_lang' , $narrative['@xml_lang']));
                                }
                            ?> 
                        </span>
                    </li>
                <?php endforeach; ?>
        </div>
</ul>

</li><!-- end of element-activity -->