<li class="element-activity">

    <div class="element-title ">
        Reporting Organization

            <div class="element-info">
                <div class="element-values">
                    <?php if($this->elements['text']): ?>
                        <span class="attrib-label">Text:</span>					
                        <span class="attrib-value"><?php if ($this->elements['text']) print $this->length()->adjustDoubleLength(Iati_Core_Codelist::getCodeByAttrib('ActivityDefault' , '@xml_lang' , $this->elements['@xml_lang'])); ?></span>
                    <?php endif; ?>
                </div>
                <div class="element-values">
                    <?php if($this->elements['@ref']): ?>
                        <span class="attrib-label">Ref:</span>
                        <span class="attrib-value"><?php if ($this->elements['@ref']) (printf("%s [%s]" , $this->length()->adjustDoubleLength(Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@ref' , $this->elements['@ref'],'Name')),Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@ref' , $this->elements['@ref']))) ?></span>  
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="highlight">
            <ul class="style-1">
                <li>
                    <span class="name">Text:</span>
                    <span class="infom"><?php if ($this->elements['text']) print ($this->elements['text']); ?>
                                        <?php if ($this->elements['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('ActivityDefault' , '@xml_lang' , $this->elements['@xml_lang']));
                                                }
                                            ?> 
                    </span>
                </li>
                <li>
                    <span class="name">Ref:</span>
                    <span class="infom"><?php if ($this->elements['@ref']) (printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@ref' , $this->elements['@ref'],'Name'),Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@ref' , $this->elements["@ref"]))) ?></span>
                </li>
                <li>
                    <span class="name">Type:</span>
                    <span class="infom"><?php if ($this->elements['@type']) (printf("%s [%s]",Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@type' , $this->elements['@type'],'Name'),Iati_Core_Codelist::getCodeByAttrib('ReportingOrg' , '@type' , $this->elements['@type']))) ?></span>
                </li>
        </div>
</ul>

</li><!-- end of element-activity -->