<li class="element-activity">
    
    <div class="element-title element-current">
        Sector
     </div>
    
    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_Sector">Edit</a></div>
   
    <?php foreach ($this->elements as $element): ?>
        <div class="current">
            <ul class="style-2 arrow">
                <li> <span class="down-arrow"><?php if ($element['@vocabulary']) ( printf("%s [%s]" , $this->length()->adjustDoubleTitleLength(Iati_Core_Codelist::getCodeByAttrib('Sector' , '@vocabulary' , $element['@vocabulary'],'Name')),Iati_Core_Codelist::getCodeByAttrib('Sector' , '@vocabulary' , $element['@vocabulary'])))?>
                         <?php if ( $element['@vocabulary'] && $element['@code'] ) print "; "; ?>
                               <?php if ($element['@code']): ?>
                                    <?php if (!$element['@vocabulary'] || $element['@vocabulary'] == 3): ?>
                                        <?php  ( printf("%s [%s]" , $this->length()->adjustDoubleTitleLength(Iati_Core_Codelist::getCodeByAttrib('Sector' , '@code' , $element['@code'],'Name')) , Iati_Core_Codelist::getCodeByAttrib('Sector' , '@code' , $element['@code'])))  ?>
                                    <?php else : ?>
                                        <?php print ($element['@code']); ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                    </span>
                    <ul class="style-2-drop first">
                        <li>
                            <span class="name">Text:</span>
                            <span class="infom"><?php if ($element['text'] != "") print ($element['text']); ?>
                                <?php
                                                if ($element['@xml_lang'])
                                                {
                                                    printf("[%s]" , Iati_Core_Codelist::getCodeByAttrib('Sector' , '@xml_lang' , $element['@xml_lang']));
                                                }
                                            ?> 
                            </span>
                        </li>
                        <li>
                            <span class="name">Vocabulary:</span>
                            <span class="infom"><?php if ($element['@vocabulary']) (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('Sector' , '@vocabulary' , $element['@vocabulary'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Sector' , '@vocabulary' , $element['@vocabulary']))) ?></span>
                        </li>
                        <li>
                            <span class="name">Code:</span>
                            <span class="infom">
                                <?php if ($element['@code']): ?>
                                    <?php if (!$element['@vocabulary'] || $element['@vocabulary'] == 3): ?>
                                        <?php (printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('Sector' , '@code' , $element['@code'],'Name'),Iati_Core_Codelist::getCodeByAttrib('Sector' , '@code' , $element['@code']))) ?>
                                    <?php else : ?>
                                        <?php print ($element['@code']); ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </span>
                        </li>
                        <li>
                            <span class="name">Percentage:</span>
                            <span class="infom"><?php if ($element['@percentage'] != "") print ($element['@percentage']); ?>
                            </span>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    <?php endforeach; ?>
    
</li><!-- end of element-activity -->

