<li class="element-activity">
    
    <div class="element-title element-current">
        Title
    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/edit-element/?activity_id=<?php echo $this->activity_id; ?>&className=Activity_Title">Edit</a></div>

        <?php $narratives = $this->elements['Narrative']; ?>
        <?php foreach ($narratives as $narrative): ?>
            <div class="current">
                <ul class="style-2 arrow">
                    <li> <span class="down-arrow"><?php if ($narrative['text'] != "") print ($this->length()->adjustSingleTitleLength($narrative['text'])); ?><?php if ($narrative['@xml_lang']) printf(" [%s]" , Iati_Core_Codelist::getCodeByAttrib('Title' , '@xml_lang' , $narrative['@xml_lang'])); ?></span>
                        <ul class="style-2-drop first">
                            <li>
                                <span class="name">Narrative Title:</span>
                                <span class="infom"><?php if ($narrative['text'] != "") print ($narrative['text']); ?>
                                                    <?php if ($narrative['@xml_lang'])
                                                        {
                                                            printf(" [%s]" , Iati_Core_Codelist::getCodeByAttrib('Title' , '@xml_lang' , $narrative['@xml_lang']));
                                                        }
                                                ?>  
                                </span>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        <?php endforeach; ?>
    
</li><!-- end of element-activity -->

