<li class="element-activity result">

    <div class="element-title element-current ">Transaction</div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/list-elements/?classname=Activity_Transaction&activity_id=<?php echo $this->activityInfo['id'] ?>">Edit</a></div>

    <?php $data = Iati_ElementSorter::sortElementsData($this->transactions , array('TransactionDate' =>'@iso_date') , array('TransactionValue' => '@value_date')); ?>
    
    <?php foreach ($data as $key=>$transaction): ?>
    <div class="current">
            <ul class="style-2 arrow">
                <li>
                    <span class="ajaxElement-down-arrow">
                        <div id="get-elementId" style="display:none"><?php echo $transaction['id'] ; ?></div>
                        <div id="get-index" style="display:none"><?php echo $key ; ?></div>
                        <div id="get-className" style="display:none"><?php echo "Transaction" ; ?></div>
                        <!--Starts Transaction Type-->
                        <?php
                        $code =  Null;
                        if (!empty($transaction["TransactionType"])):
                        ?>
                           <?php 
                                if($transaction["TransactionType"]["@code"])
                                { 
                                    printf(" %s [%s] ",$this->length()->adjustTripleTitleLength(Iati_Core_Codelist::getCodeByAttrib('TransactionType' , '@code' , $transaction["TransactionType"]["@code"],'Name')),Iati_Core_Codelist::getCodeByAttrib('TransactionType' , '@code' , $transaction["TransactionType"]["@code"]));
                                    $code = $transaction["TransactionType"]["@code"];                                           
                                }    
                          ?>
                        <?php endif; ?>
                        <!--Ends Transaction Type-->
                        
                        <!--Starts Transaction Value-->
                        <?php
                        $text = Null;
                        if (!empty($transaction["TransactionValue"])):
                            ?>   
                                <?php if ($code && $transaction["TransactionValue"]["text"]) print "; "; ?>
                                <?php  ($transaction["TransactionValue"]["@currency"]) ? (printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity' , '@default_currency' , $transaction["TransactionValue"]["@currency"]))) : (printf("[%s]",Iati_Core_Codelist::getCodeByAttrib('Activity' , '@default_currency' , $this->activityInfo['@default_currency']))) ?> 
                                <?php if ($transaction["TransactionValue"]["text"]) 
                                      {
                                       $text = $transaction["TransactionValue"]["text"];
                                       print ($this->length()->adjustTripleTitleLength($this->numberFormat()->localization($transaction["TransactionValue"]["text"]))); 
                                      }
                                ?> 
                        <?php endif; ?>
                        <!--Ends Transaction Value-->
                        
                         <!--Starts Transaction Date-->
                        <?php
                        if (!empty($transaction["TransactionDate"])):
                            ?>    
                                <?php if ($text && $transaction["TransactionDate"]["@iso_date"]) print "; "; ?>
                                <?php if ($transaction["TransactionDate"]["@iso_date"]) print ($this->length()->adjustTripleTitleLength($transaction["TransactionDate"]["@iso_date"])); ?> 
                           
                        <?php endif; ?>
                        <!--Ends Transaction Date-->
                        
                    </span>
                    <!--Transaction content is loaded through ajax in div-->
                    <div id="view-activity-ajaxElement"style="display:none"></div>
                </li>
            </ul><!--Ends .style-2-->
        </div><!--Ends .current-->
    <?php endforeach; ?>

</li><!-- Ends .element-activity -->
