<?php $transaction = $this->transaction; ?>
<ul class="style-4 none">
    <li>
        <span class="name">Ref:</span>
        <span class="infom"><?php if ($transaction['@ref']){ print $transaction['@ref']; } ?></span>
    </li>

</ul>

<!-- TransactionType Starts -->
<?php
if (!empty($transaction["TransactionType"])):
    ?>
    <?php $transactiontype = $transaction["TransactionType"]; ?>
    <ul class="style-1 style-4">
        <h2>Transaction Type</h2>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($transactiontype["text"]) print ($transactiontype["text"]); ?></span>
            </li>
            <li>
                <span class="name">Code:</span>
                <span class="infom"><?php 
                                        if($transactiontype["@code"])
                                        {
                                            printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('TransactionType' , '@code' , $transactiontype["@code"],'Name'),Iati_Core_Codelist::getCodeByAttrib('TransactionType' , '@code' , $transactiontype["@code"]));
                                        }    
                                    ?>
                </span>
            </li>
    </ul>
<?php endif; ?>
<!-- TransactionType Ends -->

<!-- ProviderOrg Starts -->
<?php
if (!empty($transaction["ProviderOrganisation"])):
    ?>

    <ul class="style-1 style-4">
        <h2>Provider Organisation</h2>
        <?php $providerorg = $transaction["ProviderOrganisation"];  ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($providerorg['text']) print ($providerorg['text']); ?></span>
            </li>
            <li>
                <span class="name">Ref:</span>
                <span class="infom"><?php if ($providerorg["@ref"]) print ($providerorg["@ref"]); ?></span>
            </li>
            <li>
                <span class="name">Provider_activity_id:</span>
                <span class="infom"><?php if ($providerorg['@provider_activity_id']) print ($providerorg['@provider_activity_id']); ?></span>
            </li>
    </ul>

<?php endif; ?>
<!-- ProviderOrg Ends -->


<!-- ReceiverOrg Starts -->
<?php
if (!empty($transaction["ReceiverOrganisation"])):
    ?>

    <ul class="style-1 style-4">
        <h2>Receiver Organisation</h2>
        <?php $receiverorg = $transaction["ReceiverOrganisation"]; ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($receiverorg['text']) print ($receiverorg['text']); ?></span>
            </li>
            <li>
                <span class="name">Ref:</span>
                <span class="infom"><?php if ($receiverorg['@ref']) print ($receiverorg['@ref']);?></span>
            </li>
            <li>
                <span class="name">Receiver_activity_id:</span>
                <span class="infom"><?php if ($receiverorg['@receiver_activity_id']) print ($receiverorg['@receiver_activity_id']); ?></span>
            </li>
    </ul>

<?php endif; ?>
<!-- ReceiverOrg Ends -->

<!-- Value Starts -->
<?php
if (!empty($transaction["TransactionValue"])):
    ?>
    <ul class="style-1 style-4">
        <h2>Value</h2>
        <?php $value = $transaction["TransactionValue"]; ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($value["text"]) print (Zend_Locale_Format::toNumber($value["text"],array('number_format' => '##,##0.00'))); ?></span>
            </li>
            <li>
                <span class="name">Value_date:</span>
                <span class="infom"><?php if ($value["@value_date"]) print ($value["@value_date"]); ?></span>
            </li>
            <li>
                <span class="name">Currency:</span>
                <span class="infom"><?php echo Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $value["@currency"],"Name");
                                      if($value["@currency"]) 
                                      {
                                            printf(" [%s]",Iati_Core_Codelist::getCodeByAttrib('Activity_default' , '@currency' , $value["@currency"])); 
                                      }
                                   ?>
                </span>
            </li>
    </ul>
<?php endif; ?>
<!-- Value Ends -->

<!-- Description Starts -->
<?php
if (!empty($transaction["Description"])):
    ?>
    <ul class="style-1 style-4">
        <h2>Description</h2>
        <?php $description = $transaction["Description"]; ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($description["text"]) print ($description["text"]);
                                    if($description["@xml_lang"])
                                     {
                                        printf(" [%s]",Iati_Core_Codelist::getCodeByAttrib('Transaction_Description' , '@xml_lang' , $description["@xml_lang"]));
                                     }
                                    ?>
                </span>               
            </li>
    </ul>
<?php endif; ?>
<!-- Description Ends -->

<!-- TransactionDate Starts -->
<?php
if (!empty($transaction["TransactionDate"])):
    ?>
    <ul class="style-1 style-4">
        <h2>Transaction Date</h2>
        <?php $transactionDate = $transaction["TransactionDate"]; ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($transactionDate["text"]) print ($transactionDate["text"]); ?></span>
            </li>
            <li>
                <span class="name">Iso Date:</span>
                <span class="infom"><?php if ($transactionDate["@iso_date"]) print ($transactionDate["@iso_date"]); ?></span>
            </li>
    </ul>
<?php endif; ?>
<!-- TransactionDate Ends -->

<!-- FlowType Starts -->
<?php
if (!empty($transaction["FlowType"])):
    ?>
    <ul class="style-1 style-4">
        <h2>Flow Type</h2>
        <?php $flowType = $transaction["FlowType"]; ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($flowType["text"]) print ($flowType["text"]); 
                                    if($flowType["@xml_lang"])
                                     {
                                        printf(" [%s]",Iati_Core_Codelist::getCodeByAttrib('Transaction_FlowType' , '@xml_lang' , $flowType["@xml_lang"]));
                                     }
                                    ?>
                </span>               
            </li>
            <li>
                <span class="name">Code:</span>
                <span class="infom"><?php 
                                        if($flowType["@code"])
                                        {
                                            printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('FlowType' , '@code' , $flowType["@code"],'Name'),Iati_Core_Codelist::getCodeByAttrib('TransactionType' , '@code' , $flowType["@code"]));
                                        }    
                                    ?>
                </span>
            </li>
    </ul>
<?php endif; ?>
<!-- FlowType Ends -->

<!-- FinanceType Starts -->
<?php
if (!empty($transaction["FinanceType"])):
    ?>
    <ul class="style-1 style-4">
        <h2>Finance Type</h2>
        <?php $financeType = $transaction["FinanceType"]; ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($financeType["text"]) print ($financeType["text"]); 
                                     if($financeType["@xml_lang"])
                                     {
                                        printf(" [%s]",Iati_Core_Codelist::getCodeByAttrib('Transaction_FinanceType' , '@xml_lang' , $financeType["@xml_lang"]));
                                     }
                                    ?>
                </span>               
            </li>
            <li>
                <span class="name">Code:</span>
                <span class="infom"><?php 
                                        if($flowType["@code"])
                                        {
                                            printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('FinanceType' , '@code' , $financeType["@code"],'Name'),Iati_Core_Codelist::getCodeByAttrib('FinanceType' , '@code' , $financeType["@code"]));
                                        }    
                                    ?>
                </span>               
            </li>
    </ul>
<?php endif; ?>
<!-- FinanceType Ends -->

<!-- AidType Starts -->
<?php
if (!empty($transaction["AidType"])):
    ?>
    <ul class="style-1 style-4">
        <h2>Aid Type</h2>
        <?php $aidType = $transaction["AidType"]; ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($aidType["text"]) print ($aidType["text"]); 
                                    if($aidType["@xml_lang"])
                                     {
                                        printf(" [%s]",Iati_Core_Codelist::getCodeByAttrib('Transaction_AidType' , '@xml_lang' , $aidType["@xml_lang"]));
                                     }
                                    ?>
                </span>               
            </li>
            <li>
                <span class="name">Code:</span>
                <span class="infom"><?php 
                                        if($aidType["@code"])
                                        {
                                            printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('AidType' , '@code' , $aidType["@code"],'Name'),Iati_Core_Codelist::getCodeByAttrib('AidType' , '@code' , $aidType["@code"]));
                                        }    
                                    ?>
                </span> 
            </li>
    </ul>
<?php endif; ?>
<!-- AidType Ends -->

<!-- DisbursementChannel Starts -->
<?php
if (!empty($transaction["AidType"])):
    ?>
    <ul class="style-1 style-4">
        <h2>Disbursement Channel</h2>
        <?php $disbursementChannel = $transaction["DisbursementChannel"]; ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($disbursementChannel["text"]) print ($disbursementChannel["text"]); 
                                     if($disbursementChannel["@xml_lang"])
                                     {
                                        printf(" [%s]",Iati_Core_Codelist::getCodeByAttrib('Transaction_DisbursementChannel' , '@xml_lang' , $disbursementChannel["@xml_lang"]));
                                     }
                                    ?>
                </span>               
            </li>
            <li>
                <span class="name">Code:</span>
                <span class="infom"><?php 
                                        if($disbursementChannel["@code"])
                                        {
                                            printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('DisbursementChannel' , '@code' , $disbursementChannel["@code"],'Name'),Iati_Core_Codelist::getCodeByAttrib('DisbursementChannel' , '@code' , $disbursementChannel["@code"]));
                                        }    
                                    ?>
                </span> 
            </li>
    </ul>
<?php endif; ?>
<!-- DisbursementChannel Ends -->

<!-- TiedStatus Starts -->
<?php
if (!empty($transaction["TiedStatus"])):
    ?>
    <ul class="style-1 style-4">
        <h2>Tied Status</h2>
        <?php $tiedStatus = $transaction["TiedStatus"]; ?>
            <li>
                <span class="name">Text:</span>
                <span class="infom"><?php if ($tiedStatus["text"]) print ($tiedStatus["text"]); 
                                     if($tiedStatus["@xml_lang"])
                                     {
                                        printf(" [%s]",Iati_Core_Codelist::getCodeByAttrib('Transaction_TiedStatus' , '@xml_lang' , $tiedStatus["@xml_lang"]));
                                     }
                                    ?>
                </span>
            </li>
            <li>
                <span class="name">Code:</span>
                <span class="infom"><?php 
                                     if($tiedStatus["@code"])
                                     {
                                        printf(" %s [%s] ",Iati_Core_Codelist::getCodeByAttrib('TiedStatus' , '@code' , $tiedStatus["@code"],'Name'),Iati_Core_Codelist::getCodeByAttrib('TiedStatus' , '@code' , $tiedStatus["@code"]));
                                     }
                                     ?>
                </span>
            </li>
    </ul>
<?php endif; ?>
<!-- TiedStatus Ends -->
