<li class="element-activity">

    <div class="element-title element-current">
        Transaction
    </div>

    <div class="edit"><a href="<?php echo $this->baseUrl() ?>/activity/list-elements/?classname=Activity_Transaction&activity_id=<?php echo $this->activityInfo['id'] ?>">Edit</a></div>

    <?php foreach ($this->transactions as $key=> $transaction): ?>
        <div class="current">
            <ul class="style-2 arrow">
                <li>

                    <span class="transaction-down-arrow transaction">  
                        <div id="get-activityId" style="display:none"><?php echo $this->activityInfo['id'] ; ?></div>
                        <div id="get-index" style="display:none"><?php echo $key ; ?></div>
                        <!--Starts Transaction Type-->
                        <?php
                        $code =  Null;
                        $transactiontypes = $transaction->getElementsByType('TransactionType');
                        $value = $transactiontypes[0]->getAttribs();
                        if (!empty($value)):
                        ?>
                            <?php foreach ($transactiontypes as $transactiontype): ?>
                                <?php if ($transactiontype->getAttrib('@code')){ $code = $transactiontype->getAttrib('@code'); ($transactiontype->getAttribValue('@code' , 'Name') != $transactiontype->getAttribValue('@code')) ? ( printf("%s [%s]" ,$this->length()->adjustTripleTitleLength($transactiontype->getAttribValue('@code' , 'Name')) , $transactiontype->getAttribValue('@code'))) : (print($this->length()->adjustTripleTitleLength($transactiontype->getAttribValue('@code'))));} ?> 
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <!--Ends Transaction Type-->
                        <!--Starts Transaction Value-->
                        <?php
                        $text = Null;
                        $values = $transaction->getElementsByType('Value');
                        $value = $values[0]->getAttribs();
                        if (!empty($value)):
                            ?>    
                            <?php foreach ($values as $value): ?>
                                <?php if ($code && $value->getAttrib('text')) print "; "; ?>
                                <?php  ($value->getAttrib('@currency')) ? (printf("[%s]",$value->getAttribValue('@currency'))) : (printf("[%s]",$this->activityInfo['@default_currency'])); ?> 
                                <?php if ($value->getAttrib('text')) 
                                      {
                                       $text = $value->getAttribValue('text');
                                       print ($this->length()->adjustTripleTitleLength($this->numberFormat()->localization($value->getAttribValue('text')))); 
                                      }
                                ?> 
                                <?php break; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <!--Ends Transaction Value-->
                        <!--Starts Transaction Date-->
                        <?php
                        $values = $transaction->getElementsByType('TransactionDate');
                        $value = $values[0]->getAttribs();
                        if (!empty($value)):
                            ?>    
                            <?php foreach ($values as $value): ?>
                                <?php if ($text && $value->getAttrib('@iso_date')) print "; "; ?>
                                <?php if ($value->getAttrib('@iso_date')) print ($this->length()->adjustTripleTitleLength($value->getAttribValue('@iso_date'))); ?> 
                                <?php break; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <!--Ends Transaction Date-->
                    </span>
                    
                    <!--Transaction content is loaded through ajax in div-->
                    <div id="view-activity-transaction"style="display:none"></div>
                   
                </li>
            </ul>
        </div>
    <?php endforeach; ?>
</li><!-- end of element-activity -->