<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>IATI</title>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <?php 
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/style.css');
            
            echo $this->headLink();
    ?>
    <?php
     $this->headScript()->prependFile($this->baseUrl() . '/js/jquery-1.3.2.min.js', $type = 'text/javascript');
     $this->headScript()->appendFile($this->baseUrl() . '/js/collapsable.js', $type = 'text/javascript');
     $this->headScript()->appendFile($this->baseUrl() . '/js/xmltab.js', $type = 'text/javascript');
     $this->headScript()->appendFile($this->baseUrl() . '/js/backtotop.js', $type = 'text/javascript');
     $this->headScript()->appendFile($this->baseUrl() . '/js/headerfix.js', $type = 'text/javascript');
       
       print $this->headScript();
    ?>
</head>
    <body <?php if($this->body_id){print "id =". $this->body_id;}?>>
    <?php //print $this->bodyTag() ?>
            <div id="flash-messages"><?php $flashMessenger = $this->flashMessages();
print $flashMessenger->getMessages();?></div>
        
        <div class="container-wrapper">
    <div id="wrapper" class="">


        <div class="page-content">
            <div class="content">
                    <?php print $this->layout()->content;?>
            </div>
            <div class="rightbar">
            </div>
        </div>
    </div>
    <div id="footer-wrapper" >
        <div id="footer"><!--
        Copyright 2010 YoungInnovations Pvt. Ltd.
        --></div>
    </div>
    <div id="backtotop"><a href="#top"></a></div>
</div>
<div id = 'contact'></div>
</body>

</html>

