<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>IATI</title>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <script type="text/javascript">
   var APP_BASEPATH = '<?php echo $this->baseUrl();?>';
</script>
    <script src="<?php echo $this->baseUrl()?>/js/dojo-1.5.0/dojo/dojo.js" djConfig="parseOnLoad: true">
</script>
<!--<link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>-->
    <?php 
    
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/960.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/reset.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/style.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/js/dojo-1.5.0/dijit/themes/claro/claro.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/style_wep.css');
    
             print $this->headLink();
    
    ?>
    
    <?php 
       //$this->headScript()->prependFile($this->baseUrl() . '/js/jquery-1.3.2.min.js', $type = 'text/javascript');
        //$this->headScript()->appendFile($this->baseUrl() . '/js/ui.datepicker.js', $type = 'text/javascript');
//        $this->headScript()->appendFile($this->baseUrl() . '/js/backtotop.js', $type = 'text/javascript');
     $this->headScript()->appendFile($this->baseUrl() . '/js/common.js', $type = 'text/javascript');

       
        print $this->headScript();
    ?>
</head>

<body class="claro">
    <div id="wrapper">
        <div id="header">
            <a name="top"></a>
            <div id="nav-logo-section">
                <div class="container_12">
                    <div id="logo-nav" class="grid_12">
                        <div class="logo"> <a href="<?php print($this->baseUrl(). "/user/user/login");?>/"><img alt="logo" src="<?php print($this->baseUrl());?>/stylesheet/images/aid-stream-logo.png"></a>
                        </div><!----close logo----->
                        <div class="nav">
                            <ul class="menu">
                                <li class="support">Support</li>
                                <li><a href="#section3"><span class="title">Contact</span><br /><span>Comments,Suggestions</span></a></li>
                                <li><a href="#section2"><span class="title">How</span><br /><span>How to use AidStream?</span></a></li>
                                <li><a href="#section1"><span class="title">What</span><br /><span>What is AidStream?</span></a></li>
                            </ul>
                        </div><!-----Close nav------->                                 
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            
            <div class="login-section">
                <div class="container_12">
                    <div id="login" class="grid_7">
                        <!--<form>
                            <table>                   	
                                <tr>
                                    <td><label>Username</label></td>
                                    <td><label>Password</label></td>
                                </tr>
                                <tr>
                                    <td><input name="username" type="text" value="" /></td>
                                    <td><input name="password" type="password" value="" /></td>
                                    <td><input id="login-bottom" name="login" type="button" value="Login" /></td>
                                </tr>
                            </table>
                        </form>-->
                        <div id="login-nav">
                        <!--<a id="signup" href="#">Signup</a>-->
                        <!--login tab-->    
                        <!--<img alt="logo" src="<?php //print $this->baseUrl()?>/images/logo.png">-->
                        <!--<h1></h1>-->
                        <?$auth = Zend_Auth::getInstance();
                            if ($auth->hasIdentity()):?>
                            <?php $identity = $auth->getIdentity();?>
                            <?php $session = new Zend_Session_Namespace('superadmin')?>
                            <?php if($session->identity): ?>
                                <?php echo $this->l('Switch back', 'user/user/switch-back')?>
                                You are masquerading as  <?php echo $this->l($identity->user_name, 'user/user/myaccount',array('attributes' => array('class' => 'user-name')));?>
                                <?php print " , (". $this->l('Logout', 'user/user/logout') . ")";?>
                            <?php else : ?>
                                You are logged in as  <?php echo $this->l($identity->user_name, 'user/user/myaccount',array('attributes' => array('class' => 'user-name')));?>
                                <?php print " , (". $this->l('Logout', 'user/user/logout') . ")";?>
                            <?php endif;?>
                                
                        <?endif;?>                                                                
                        <? //if (!$auth->hasIdentity()):?>
<!--                        <a class="user-login" href="<?php //print $this->baseUrl() ?>/user/user/login">Login</a>                                  -->
                        <?//endif;?>                                                                                                                  
                    </div>
                    <div class = "user-nav">
                    <?php if ($auth->hasIdentity())
                         print $this->partial('partial/section/top-bar.phtml');
                    ?>
                    </div>
                    </div><!-----Close login---->
                </div>
                <div class="clear"></div>
            </div><!---Close login-section--->
            <!--<div class="container_12 grid_12">
                <div class="login-parent"><a href="#">Login</a></div>
            </div>-->
            <div class="clear"></div>
            <!--search div start-->


            <!--<div class="logo"> <a href="<?php print($this->baseUrl(). "/user/user/login");?>/"><img alt="logo" src="<?php print($this->baseUrl());?>/stylesheet/images/aid-stream-logo.png"></a>
            </div> <!-- losog -->
            <!--<div class="site-name"><?php //print $this->placeholder('title')?></div>-->
            <div id="navigation-wrapper">
                    <!--<div id="wrapper">
                        <div id="navigation" class="menu">
                            <ul class="menu-list">
                                <li class="menu-item"><a class="active" href="#">Home</a></li>
                                <li class="menu-item"><a href="#">The IATI Standard</a></li>
                                <li class="menu-item"><a href="#">Guidance Material</a></li>
                                <li class="menu-item"><a href="#">Downloads</a></li>
                                <li class="menu-item" id="nav-border"><a href="#">Knowledge Base</a></li>
                                </ul>
                        </div>
                </div>-->
            </div>
        </div><!--header closed-->

        <div class="clear"></div>

        <div id="content-section"><!--Start content-section--->
            <div class="container_12">
                <div class="grid_12">
                    <!--contain div start-->
                    <div id="main-content-top"></div>
                    <div id="contain-body">
                        <div id="contain-left">
                            <div id="contain-area">
                                <div id="contain">
                                    <div id="flash-messages"><?php $flashMessenger = $this->flashMessages();
                                        print $flashMessenger->getMessages();?>
                                    </div>
                                    <!--<h1>IATI Code Lists</h1>-->
                                    <div id="breadcrumb">
                                        <?php print $this->partial('partial/breadcrumbs.phtml', $this->getVars())?>
                                    </div><!-- end of the breadcrumb -->
                                    <?php if ($this->placeholder('title') != ""):?>
                                    <h1><?php print $this->placeholder('title')?></h1>
                                    <? endif;?>
                                    <?php print $this->layout()->content;?>
                                </div>
                            </div>
                        </div><!---Close Content left-->

                        <div id="sidebar-right">
                            <div id="sidebar-right-inner">
                            <?php //var_dump($auth->hasIdentity());?>
                                <?php if ($auth->hasIdentity())
                                //print "df";exit;
                                    print $this->partial('partial/section/left-bar.phtml');
                                ?>
                            </div>
                        </div><!--Close sidebar-right-->
                        <div class="clear"></div>
                        <div id="main-content-bottom"></div>
                    </div><!---Close contain-body--->
                </div><!--close grid 12--->
            </div>
            <div class="clear"></div>
        </div><!---Close content-section-->

        <div class="clear"></div>

        <div id="footer"><!--Start footer-->
            <div class="container_12">
            	<div class="grid_12">
        	    <h2 class="footer-title">Who's using it?</h1>
                    <img src="stylesheet/images/unicef-logo.png" alt="unicef" title="" />
            	</div>
            </div>
            <div class="clearfix"></div>
        </div><!---Close footer--->

    </div><!--Close Wrapper-->
</body>
</html>
