<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>AidStream</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

	
    <?php 
            $this->headLink()->headLink(array('rel' => 'shortcut icon', 
                                    'type' => 'image/png', 
                                  'href' => $this->baseUrl() . '/favicon.ico'),
                                  'PREPEND');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/960.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/reset.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/style.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/style_wep.css');
            $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Roboto:400,300');
    
            print $this->headLink();
    
    ?>
    <script type="text/javascript">
	var APP_BASEPATH = '<?php echo $this->baseUrl();?>';
        
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-30707725-1']);
        _gaq.push(['_trackPageview']);
      
        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
        
    </script>
    <script src="<?php echo $this->baseUrl()?>/js/dojo-release/dojo/dojo/dojo.js" djConfig="locale:'en-us'" djConfig="parseOnLoad: true"></script>
    <?php
	$this->headScript()->appendFile($this->baseUrl() . '/js/dojo-release/nls/iati_en-us.js', $type = 'text/javascript');
	$this->headScript()->appendFile($this->baseUrl() . '/js/dojo-release/iati.js', $type = 'text/javascript');
	$this->headScript()->appendFile($this->baseUrl() . '/js/home.js', $type = 'text/javascript');
	
        print $this->headScript();
    ?>
</head>

<body class="login-layout">
    <div id="wrapper">
	
    <div class="login-wrapper">
      <div id="login-form-wrapper" style="display:none">
	<?php $form = new User_Form_User_Login(); ?>
	<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" id="<?php echo $form->getId() ?>" >
	    <table>
		<tr>
		    <td><?php echo $form->username->renderViewHelper();?><span id='username-error' class="error" ></span></td>
		</tr>
		<tr>
		    <td><?php echo $form->password->renderViewHelper();?><span id='password-error' class="error" ></span></td>
		</tr>
		<tr>
		    <td><?php echo $this->formSubmit('login','Secure Login'); ?> </td>
		</tr>
		<tr> <td><div class="login-register">Not registered yet? <?php echo $this->l('Register now', 'user/user/register');?> </div><div class='forgot-password'><?php echo $this->l('Forgot Password?', 'user/user/forgotpassword');?></div></td></tr>
	    </table>
	</form>
    </div><!--Close login-form-container-->
    </div>
	<div id="hidden-overlay"></div>
	<div id="login-hidden-overlay"></div>

	<div id="static-header">
	    <div id="home-user-nav">
		<div class="container_12">
		    	<?php $auth = Zend_Auth::getInstance();  ?>
			<?php   if ($auth->hasIdentity()):?>
			<div class="nav_container">
			    <?php $identity = $auth->getIdentity();?>
			    <?php $session = new Zend_Session_Namespace('superadmin')?>
			    <?php if($session->identity): ?>
				<?php echo $this->l('Switch back', 'user/user/switch-back')?>
				You are masquerading as  <?php echo $this->l($identity->user_name, 'user/user/myaccount',array('attributes' => array('class' => 'user-name')));?>
				|
				<?php echo $this->l('Dashboard ', 'wep/dashboard')?>
				<?php print " , (". $this->l('Logout', 'user/user/logout') . ")";?>
			    <?php else : ?>
				You are logged in as  <?php echo $this->l($identity->user_name, 'user/user/myaccount',array('attributes' => array('class' => 'user-name')));?> |
				<?php if($identity->role_id == 3): ?>
				    <?php echo $this->l(' Dashboard', 'admin/dashboard');?>
				<?php else : ?>
				    <?php echo $this->l(' Dashboard', 'wep/dashboard');?>
				<?php endif; ?>
				<?php print " , (". $this->l('Logout', 'user/user/logout') . ")";?>
			    <?php endif;?>
			</div>
			<?php endif;?>
		</div>
	    </div>
	   <div class="header-container">
		<div class="header">
			<div class="logo">
				<a href="<?php print($this->baseUrl()) ?>/"><img alt="logo" src="<?php print($this->baseUrl());?>/images/logo.png" alt="Aidstream"></a>
			</div>
			<?php $url = $_SERVER['REQUEST_URI'];?>
			<div class="nav">
				<ul>
					<li class="<?php echo ($url === $this->baseUrl().'/about')? 'active-menu':'';?>"><?php echo $this->l(' About', 'about');?></li>
					<li><?php echo $this->l("How to Use", 'how-to');?></li>
					<li class="<?php echo ($url === $this->baseUrl().'/organisations')? 'active-menu':'';?>"><?php echo $this->l("Who's Using", 'organisations');?></li>
					<li class="<?php echo ($url === $this->baseUrl().'/organisation?reporting_org=all')? 'active-menu':'';?>"><?php echo $this->l('Snapshot', 'snapshot');?></li>
					<li><a href='http://blog.aidstream.org' target="_blank">Blog</a></li>
					<li id="demo-link"><a href='http://demo.aidstream.org' target="_blank">Demo</a></li>
				</ul>
				<?php if(!$auth->hasIdentity()):?>
				<div class="login" id="login-register-popup">
					<?php echo $this->l('Login / Register', 'user/user/login');?>
				</div>
				<?php endif;?>
			</div>
		</div>
	</div>
		<div class="clear"></div>
	    </div><!--Close login-section-->
	    <div id="index-flash-messages">
		<div class="message-wrapper container_12">
		<?php $flashMessenger = $this->flashMessages();
		  print $flashMessenger->getMessages();?>
		</div>
	    </div>
	    <div class="clear"></div>
	</div><!--header closed-->

	<div class="clear"></div>
	</div>
         <div id="content-section"><!--Start content-section--->
            <div class="container_12">
                <div class="grid_12">
                    <!--contain div start-->
                    <div id="main-content-top"></div>
                    <div id="contain-body">
                        <div id="contain-left">
                            <div id="contain-area">
                                <div id="contain">
                                    
                                    <?php if ($this->placeholder('title') != ""):?>
                                    <h1><?php print $this->placeholder('title')?></h1>
                                    <?php endif;?>
                                    <?php print $this->layout()->content;?>
                                </div>
                            </div>
                        </div><!--Close Content left-->

                        <div id="sidebar-right">
                            <div id="sidebar-right-inner">
                                <?php if ($auth->hasIdentity())
                                    print $this->partial('partial/section/left-bar.phtml');
                                ?>
                            </div>
                        </div><!--Close sidebar-right-->
                        <div class="clear"></div>
                        <div id="main-content-bottom"></div>
                    </div><!--Close contain-body--->
                </div><!--close grid 12--->
            </div>
            <div class="clear"></div>
        </div><!--Close content-section-->

        <div class="clear"></div>

        <div id="footer"><!--Start footer-->
            <div class="container_12">
            	<div class="grid_12">
        	    <h2 class="footer-title">Who's using it?</h1>
            	</div>
            </div>
            <div class="clearfix"></div>
        </div><!--Close footer-->

    </div><!--Close Wrapper-->
</body>
</html>
