<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>IATI</title>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <script type="text/javascript">
   var APP_BASEPATH = '<?php echo $this->baseUrl();?>';
</script>
    <script src="<?php echo $this->baseUrl()?>/js/dojo-1.5.0/dojo/dojo.js" djConfig="parseOnLoad: true">
</script>
<!--<link href='http://fonts.googleapis.com/css?family=Amaranth' rel='stylesheet' type='text/css'>-->
    <?php 
    		/**
    		 * @todo if dojo and jquery is being used in the same page use jquery.noconflict
    		 */
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/960.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/reset.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/style.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/js/dojo-1.5.0/dijit/themes/claro/claro.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/style_wep.css');
    
             print $this->headLink();
    
    ?>
    
    <?php 
	//$this->headScript()->prependFile($this->baseUrl() . '/js/jquery-1.3.2.min.js', $type = 'text/javascript');
        //$this->headScript()->appendFile($this->baseUrl() . '/js/ui.datepicker.js', $type = 'text/javascript');
	//$this->headScript()->appendFile($this->baseUrl() . '/js/backtotop.js', $type = 'text/javascript');
     $this->headScript()->appendFile($this->baseUrl() . '/js/common.js', $type = 'text/javascript');
       
        print $this->headScript();
    ?>
</head>

<body class="claro">
    <div id="wrapper">
			<div id="support-container" class="container_12">
				<div id="support-wrapper" class="grid_5 push_7">
					<div class="support-form">
						<?php $supportForm = new Form_General_Support()?>
						<?php echo $supportForm;?>
					</div>
					<div class="support">Support</div>
				</div>
			</div>
        <div id="header">
            <a name="top"></a>
            <div id="nav-logo-section">
                <div class="container_12">
                    <div id="logo-nav" class="grid_12">
                        <div class="logo"> <a href="<?php print($this->baseUrl());?>/"><img alt="logo" src="<?php print($this->baseUrl());?>/stylesheet/images/aid-stream-logo.png"></a>
                        </div><!----close logo----->
                        <div class="support">Support</div>
                        <div class="nav">
                            <ul class="menu">
                                <li><a href="#Contacts"><span class="title">Contact</span><br /><span>Comments,Suggestions</span></a></li>
                                <li><a href="#How-to-use-AidStream"><span class="title">How</span><br /><span>How to use AidStream?</span></a></li>
                                <li><a href="#What-is-AidStream"><span class="title">What</span><br /><span>What is AidStream?</span></a></li>
                            </ul>
                        </div><!-----Close nav------->
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            
            <div class="login-section"><!---Start login-section--->
                <div class="container_12">
                    <div id="login-form-section" class="grid_7">
                            <? $auth = Zend_Auth::getInstance();?>
                            <? if (!$auth->hasIdentity()):?>
                            <? $form = new User_Form_User_Login(); ?>
                        <div id="login-form-container">
			    <form method="<? echo $form->getMethod() ?>" action="<? echo $form->getAction()?>" id="<? echo $form->getId() ?>" >
				<table>
				    <tr>
					<td><label><? echo $form->username->renderLabel();?></label></td>
					<td><label><? echo $form->password->renderLabel();?></label></td>
				    </tr>
				    <tr>
					<td><? echo $form->username->renderViewHelper();?><span id='username-error' class="error" ></span></td>
					<td><? echo $form->password->renderViewHelper();?><span id='password-error' class="error" ></span></td>
					<td><? echo $this->formSubmit('login','Login'); ?> </td>
				    </tr>
				</table>
			    </form>
			</div><!--Close login-form-container-->
                        <a class="login-parent" href="#">Login</a>
                        <? endif;?>
                    </div><!-----Close login-form-section---->
                </div>
                <div class="clear"></div>
            </div><!---Close login-section--->
            <div class="clear"></div>
        </div><!--header closed-->

        <div class="clear"></div>

        <div id="content-section"><!--Start content-section--->
                <?php if ($this->placeholder('title') != ""):?>
                <h1><?php print $this->placeholder('title')?></h1>
                <? endif;?>
                <?php print $this->layout()->content;?>
            <div class="clear"></div>
        </div><!---Close content-section-->

        <div class="clear"></div>

        <div id="footer"><!--Start footer-->
            <div class="container_12">
            	<div class="grid_12">
        	    <h2 class="footer-title">Who's using it?</h1>
                    <img src="stylesheet/images/unicef-logo.png" alt="unicef" title="" />
            	</div>
            </div>
            <div class="clearfix"></div>
        </div><!---Close footer--->

    </div><!--Close Wrapper-->
</body>
</html>
