<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>IATI</title>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
	<?php 
	
	/*		$this->headLink()->appendStylesheet($this->baseUrl() . '/css/text.css');
			$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui-1.7.2.custom.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/css/ui.core.css');
            $this->headLink()->appendStylesheet($this->baseUrl() . '/css/ui.datepicker.css');*/
			//$this->headLink()->appendStylesheet($this->baseUrl() . '/contactable/contactable.css');
           	//$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui-1.7.2.custom.css');
			//echo $this->headLink();
			$this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/960.css');
			$this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/reset.css');
			$this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/style1.css');
			$this->headLink()->appendStylesheet($this->baseUrl() . '/stylesheet/style.css');
	
			 print $this->headLink();
	
	?>
	
	<?php 
	   $this->headScript()->prependFile($this->baseUrl() . '/js/jquery-1.3.2.min.js', $type = 'text/javascript');
        $this->headScript()->appendFile($this->baseUrl() . '/js/ui.datepicker.js', $type = 'text/javascript');
		$this->headScript()->appendFile($this->baseUrl() . '/js/backtotop.js', $type = 'text/javascript');
       	// $this->headScript()->appendFile($this->baseUrl() . '/contactable/jquery.contactable.js', $type = 'text/javascript');
     	//$this->headScript()->appendFile($this->baseUrl() . '/contactable/jquery.contactable.min.js', $type = 'text/javascript');
       	//$this->headScript()->appendFile($this->baseUrl() . '/contactable/jquery.validate.pack.js', $type = 'text/javascript');
       	//$this->headScript()->appendFile($this->baseUrl() . '/contactable/contact.js', $type = 'text/javascript');
        
        print $this->headScript();
	?>
</head>

<body class="login">
	<div id="login-wrapper">
	<!--<div class="logo"> <a href="<?php //print($this->baseUrl());?>/"><img alt="logo" src="<?php print($this->baseUrl());?>/stylesheet/images/logo.jpg"></a>
					  </div>--> <!-- losog -->
	<?php print $this->layout()->content;?>
	</div>

</body>
</html>